# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsage Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsage <- R6::R6Class(
  'AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsage',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageObject <- list()

      AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageObject
    },
    fromJSON = function(AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageJson) {
      AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageObject <- jsonlite::fromJSON(AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageJson) {
      AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageObject <- jsonlite::fromJSON(AllOfEfirDataHubModelsRequestsV2InfoClassificationCodesRequestUsageJson)
    }
  )
)
