# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSource Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSource <- R6::R6Class(
  'AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSource',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceObject <- list()

      AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceObject
    },
    fromJSON = function(AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceJson) {
      AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceObject <- jsonlite::fromJSON(AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceJson) {
      AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceObject <- jsonlite::fromJSON(AllOfBondCalculatorAccruedInterestModelsRequestsAccruedInterestOnPeriodRequestShiftTypeSourceJson)
    }
  )
)
