# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ArchiveCurrencyRateBody Class
#'
#' @field from 
#' @field to 
#' @field date 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArchiveCurrencyRateBody <- R6::R6Class(
  'ArchiveCurrencyRateBody',
  public = list(
    `from` = NULL,
    `to` = NULL,
    `date` = NULL,
    initialize = function(`from`, `to`, `date`){
      if (!missing(`from`)) {
        stopifnot(is.character(`from`), length(`from`) == 1)
        self$`from` <- `from`
      }
      if (!missing(`to`)) {
        stopifnot(is.character(`to`), length(`to`) == 1)
        self$`to` <- `to`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
    },
    toJSON = function() {
      ArchiveCurrencyRateBodyObject <- list()
      if (!is.null(self$`from`)) {
        ArchiveCurrencyRateBodyObject[['from']] <- self$`from`
      }
      if (!is.null(self$`to`)) {
        ArchiveCurrencyRateBodyObject[['to']] <- self$`to`
      }
      if (!is.null(self$`date`)) {
        ArchiveCurrencyRateBodyObject[['date']] <- self$`date`
      }

      ArchiveCurrencyRateBodyObject
    },
    fromJSON = function(ArchiveCurrencyRateBodyJson) {
      ArchiveCurrencyRateBodyObject <- jsonlite::fromJSON(ArchiveCurrencyRateBodyJson)
      if (!is.null(ArchiveCurrencyRateBodyObject$`from`)) {
        self$`from` <- ArchiveCurrencyRateBodyObject$`from`
      }
      if (!is.null(ArchiveCurrencyRateBodyObject$`to`)) {
        self$`to` <- ArchiveCurrencyRateBodyObject$`to`
      }
      if (!is.null(ArchiveCurrencyRateBodyObject$`date`)) {
        self$`date` <- ArchiveCurrencyRateBodyObject$`date`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "from": %s,
           "to": %s,
           "date": %s
        }',
        self$`from`,
        self$`to`,
        self$`date`
      )
    },
    fromJSONString = function(ArchiveCurrencyRateBodyJson) {
      ArchiveCurrencyRateBodyObject <- jsonlite::fromJSON(ArchiveCurrencyRateBodyJson)
      self$`from` <- ArchiveCurrencyRateBodyObject$`from`
      self$`to` <- ArchiveCurrencyRateBodyObject$`to`
      self$`date` <- ArchiveCurrencyRateBodyObject$`date`
    }
  )
)
