# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ArchiveHistoryBody Class
#'
#' @field issId 
#' @field isin 
#' @field dateFrom 
#' @field dateTo 
#' @field step 
#' @field rowNum 
#' @field fields 
#' @field official 
#' @field sort 
#' @field tradeSite 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArchiveHistoryBody <- R6::R6Class(
  'ArchiveHistoryBody',
  public = list(
    `issId` = NULL,
    `isin` = NULL,
    `dateFrom` = NULL,
    `dateTo` = NULL,
    `step` = NULL,
    `rowNum` = NULL,
    `fields` = NULL,
    `official` = NULL,
    `sort` = NULL,
    `tradeSite` = NULL,
    initialize = function(`issId`, `isin`, `dateFrom`, `dateTo`, `step`, `rowNum`, `fields`, `official`, `sort`, `tradeSite`){
      if (!missing(`issId`)) {
        stopifnot(is.numeric(`issId`), length(`issId`) == 1)
        self$`issId` <- `issId`
      }
      if (!missing(`isin`)) {
        stopifnot(is.character(`isin`), length(`isin`) == 1)
        self$`isin` <- `isin`
      }
      if (!missing(`dateFrom`)) {
        stopifnot(is.character(`dateFrom`), length(`dateFrom`) == 1)
        self$`dateFrom` <- `dateFrom`
      }
      if (!missing(`dateTo`)) {
        stopifnot(is.character(`dateTo`), length(`dateTo`) == 1)
        self$`dateTo` <- `dateTo`
      }
      if (!missing(`step`)) {
        stopifnot(is.character(`step`), length(`step`) == 1)
        self$`step` <- `step`
      }
      if (!missing(`rowNum`)) {
        stopifnot(is.numeric(`rowNum`), length(`rowNum`) == 1)
        self$`rowNum` <- `rowNum`
      }
      if (!missing(`fields`)) {
        stopifnot(is.list(`fields`), length(`fields`) != 0)
        lapply(`fields`, function(x) stopifnot(is.character(x)))
        self$`fields` <- `fields`
      }
      if (!missing(`official`)) {
        self$`official` <- `official`
      }
      if (!missing(`sort`)) {
        stopifnot(is.character(`sort`), length(`sort`) == 1)
        self$`sort` <- `sort`
      }
      if (!missing(`tradeSite`)) {
        stopifnot(is.character(`tradeSite`), length(`tradeSite`) == 1)
        self$`tradeSite` <- `tradeSite`
      }
    },
    toJSON = function() {
      ArchiveHistoryBodyObject <- list()
      if (!is.null(self$`issId`)) {
        ArchiveHistoryBodyObject[['issId']] <- self$`issId`
      }
      if (!is.null(self$`isin`)) {
        ArchiveHistoryBodyObject[['isin']] <- self$`isin`
      }
      if (!is.null(self$`dateFrom`)) {
        ArchiveHistoryBodyObject[['dateFrom']] <- self$`dateFrom`
      }
      if (!is.null(self$`dateTo`)) {
        ArchiveHistoryBodyObject[['dateTo']] <- self$`dateTo`
      }
      if (!is.null(self$`step`)) {
        ArchiveHistoryBodyObject[['step']] <- self$`step`
      }
      if (!is.null(self$`rowNum`)) {
        ArchiveHistoryBodyObject[['rowNum']] <- self$`rowNum`
      }
      if (!is.null(self$`fields`)) {
        ArchiveHistoryBodyObject[['fields']] <- self$`fields`
      }
      if (!is.null(self$`official`)) {
        ArchiveHistoryBodyObject[['official']] <- self$`official`
      }
      if (!is.null(self$`sort`)) {
        ArchiveHistoryBodyObject[['sort']] <- self$`sort`
      }
      if (!is.null(self$`tradeSite`)) {
        ArchiveHistoryBodyObject[['tradeSite']] <- self$`tradeSite`
      }

      ArchiveHistoryBodyObject
    },
    fromJSON = function(ArchiveHistoryBodyJson) {
      ArchiveHistoryBodyObject <- jsonlite::fromJSON(ArchiveHistoryBodyJson)
      if (!is.null(ArchiveHistoryBodyObject$`issId`)) {
        self$`issId` <- ArchiveHistoryBodyObject$`issId`
      }
      if (!is.null(ArchiveHistoryBodyObject$`isin`)) {
        self$`isin` <- ArchiveHistoryBodyObject$`isin`
      }
      if (!is.null(ArchiveHistoryBodyObject$`dateFrom`)) {
        self$`dateFrom` <- ArchiveHistoryBodyObject$`dateFrom`
      }
      if (!is.null(ArchiveHistoryBodyObject$`dateTo`)) {
        self$`dateTo` <- ArchiveHistoryBodyObject$`dateTo`
      }
      if (!is.null(ArchiveHistoryBodyObject$`step`)) {
        self$`step` <- ArchiveHistoryBodyObject$`step`
      }
      if (!is.null(ArchiveHistoryBodyObject$`rowNum`)) {
        self$`rowNum` <- ArchiveHistoryBodyObject$`rowNum`
      }
      if (!is.null(ArchiveHistoryBodyObject$`fields`)) {
        self$`fields` <- ArchiveHistoryBodyObject$`fields`
      }
      if (!is.null(ArchiveHistoryBodyObject$`official`)) {
        self$`official` <- ArchiveHistoryBodyObject$`official`
      }
      if (!is.null(ArchiveHistoryBodyObject$`sort`)) {
        self$`sort` <- ArchiveHistoryBodyObject$`sort`
      }
      if (!is.null(ArchiveHistoryBodyObject$`tradeSite`)) {
        self$`tradeSite` <- ArchiveHistoryBodyObject$`tradeSite`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "issId": %d,
           "isin": %s,
           "dateFrom": %s,
           "dateTo": %s,
           "step": %s,
           "rowNum": %d,
           "fields": [%s],
           "official": %s,
           "sort": %s,
           "tradeSite": %s
        }',
        self$`issId`,
        self$`isin`,
        self$`dateFrom`,
        self$`dateTo`,
        self$`step`,
        self$`rowNum`,
        lapply(self$`fields`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`official`,
        self$`sort`,
        self$`tradeSite`
      )
    },
    fromJSONString = function(ArchiveHistoryBodyJson) {
      ArchiveHistoryBodyObject <- jsonlite::fromJSON(ArchiveHistoryBodyJson)
      self$`issId` <- ArchiveHistoryBodyObject$`issId`
      self$`isin` <- ArchiveHistoryBodyObject$`isin`
      self$`dateFrom` <- ArchiveHistoryBodyObject$`dateFrom`
      self$`dateTo` <- ArchiveHistoryBodyObject$`dateTo`
      self$`step` <- ArchiveHistoryBodyObject$`step`
      self$`rowNum` <- ArchiveHistoryBodyObject$`rowNum`
      self$`fields` <- ArchiveHistoryBodyObject$`fields`
      self$`official` <- ArchiveHistoryBodyObject$`official`
      self$`sort` <- ArchiveHistoryBodyObject$`sort`
      self$`tradeSite` <- ArchiveHistoryBodyObject$`tradeSite`
    }
  )
)
