# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ArchiveSnapshotOnExchangesBody Class
#'
#' @field fintoolIds 
#' @field issIds 
#' @field codes 
#' @field tradeSites 
#' @field timeSlice 
#' @field dateFrom 
#' @field dateTo 
#' @field fields 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArchiveSnapshotOnExchangesBody <- R6::R6Class(
  'ArchiveSnapshotOnExchangesBody',
  public = list(
    `fintoolIds` = NULL,
    `issIds` = NULL,
    `codes` = NULL,
    `tradeSites` = NULL,
    `timeSlice` = NULL,
    `dateFrom` = NULL,
    `dateTo` = NULL,
    `fields` = NULL,
    initialize = function(`fintoolIds`, `issIds`, `codes`, `tradeSites`, `timeSlice`, `dateFrom`, `dateTo`, `fields`){
      if (!missing(`fintoolIds`)) {
        stopifnot(is.list(`fintoolIds`), length(`fintoolIds`) != 0)
        lapply(`fintoolIds`, function(x) stopifnot(is.character(x)))
        self$`fintoolIds` <- `fintoolIds`
      }
      if (!missing(`issIds`)) {
        stopifnot(is.list(`issIds`), length(`issIds`) != 0)
        lapply(`issIds`, function(x) stopifnot(is.character(x)))
        self$`issIds` <- `issIds`
      }
      if (!missing(`codes`)) {
        stopifnot(is.list(`codes`), length(`codes`) != 0)
        lapply(`codes`, function(x) stopifnot(is.character(x)))
        self$`codes` <- `codes`
      }
      if (!missing(`tradeSites`)) {
        stopifnot(is.list(`tradeSites`), length(`tradeSites`) != 0)
        lapply(`tradeSites`, function(x) stopifnot(is.character(x)))
        self$`tradeSites` <- `tradeSites`
      }
      if (!missing(`timeSlice`)) {
        stopifnot(is.character(`timeSlice`), length(`timeSlice`) == 1)
        self$`timeSlice` <- `timeSlice`
      }
      if (!missing(`dateFrom`)) {
        stopifnot(is.character(`dateFrom`), length(`dateFrom`) == 1)
        self$`dateFrom` <- `dateFrom`
      }
      if (!missing(`dateTo`)) {
        stopifnot(is.character(`dateTo`), length(`dateTo`) == 1)
        self$`dateTo` <- `dateTo`
      }
      if (!missing(`fields`)) {
        stopifnot(is.list(`fields`), length(`fields`) != 0)
        lapply(`fields`, function(x) stopifnot(is.character(x)))
        self$`fields` <- `fields`
      }
    },
    toJSON = function() {
      ArchiveSnapshotOnExchangesBodyObject <- list()
      if (!is.null(self$`fintoolIds`)) {
        ArchiveSnapshotOnExchangesBodyObject[['fintoolIds']] <- self$`fintoolIds`
      }
      if (!is.null(self$`issIds`)) {
        ArchiveSnapshotOnExchangesBodyObject[['issIds']] <- self$`issIds`
      }
      if (!is.null(self$`codes`)) {
        ArchiveSnapshotOnExchangesBodyObject[['codes']] <- self$`codes`
      }
      if (!is.null(self$`tradeSites`)) {
        ArchiveSnapshotOnExchangesBodyObject[['tradeSites']] <- self$`tradeSites`
      }
      if (!is.null(self$`timeSlice`)) {
        ArchiveSnapshotOnExchangesBodyObject[['timeSlice']] <- self$`timeSlice`
      }
      if (!is.null(self$`dateFrom`)) {
        ArchiveSnapshotOnExchangesBodyObject[['dateFrom']] <- self$`dateFrom`
      }
      if (!is.null(self$`dateTo`)) {
        ArchiveSnapshotOnExchangesBodyObject[['dateTo']] <- self$`dateTo`
      }
      if (!is.null(self$`fields`)) {
        ArchiveSnapshotOnExchangesBodyObject[['fields']] <- self$`fields`
      }

      ArchiveSnapshotOnExchangesBodyObject
    },
    fromJSON = function(ArchiveSnapshotOnExchangesBodyJson) {
      ArchiveSnapshotOnExchangesBodyObject <- jsonlite::fromJSON(ArchiveSnapshotOnExchangesBodyJson)
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`fintoolIds`)) {
        self$`fintoolIds` <- ArchiveSnapshotOnExchangesBodyObject$`fintoolIds`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`issIds`)) {
        self$`issIds` <- ArchiveSnapshotOnExchangesBodyObject$`issIds`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`codes`)) {
        self$`codes` <- ArchiveSnapshotOnExchangesBodyObject$`codes`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`tradeSites`)) {
        self$`tradeSites` <- ArchiveSnapshotOnExchangesBodyObject$`tradeSites`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`timeSlice`)) {
        self$`timeSlice` <- ArchiveSnapshotOnExchangesBodyObject$`timeSlice`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`dateFrom`)) {
        self$`dateFrom` <- ArchiveSnapshotOnExchangesBodyObject$`dateFrom`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`dateTo`)) {
        self$`dateTo` <- ArchiveSnapshotOnExchangesBodyObject$`dateTo`
      }
      if (!is.null(ArchiveSnapshotOnExchangesBodyObject$`fields`)) {
        self$`fields` <- ArchiveSnapshotOnExchangesBodyObject$`fields`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fintoolIds": [%s],
           "issIds": [%s],
           "codes": [%s],
           "tradeSites": [%s],
           "timeSlice": %s,
           "dateFrom": %s,
           "dateTo": %s,
           "fields": [%s]
        }',
        lapply(self$`fintoolIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`issIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`codes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`tradeSites`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`timeSlice`,
        self$`dateFrom`,
        self$`dateTo`,
        lapply(self$`fields`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(ArchiveSnapshotOnExchangesBodyJson) {
      ArchiveSnapshotOnExchangesBodyObject <- jsonlite::fromJSON(ArchiveSnapshotOnExchangesBodyJson)
      self$`fintoolIds` <- ArchiveSnapshotOnExchangesBodyObject$`fintoolIds`
      self$`issIds` <- ArchiveSnapshotOnExchangesBodyObject$`issIds`
      self$`codes` <- ArchiveSnapshotOnExchangesBodyObject$`codes`
      self$`tradeSites` <- ArchiveSnapshotOnExchangesBodyObject$`tradeSites`
      self$`timeSlice` <- ArchiveSnapshotOnExchangesBodyObject$`timeSlice`
      self$`dateFrom` <- ArchiveSnapshotOnExchangesBodyObject$`dateFrom`
      self$`dateTo` <- ArchiveSnapshotOnExchangesBodyObject$`dateTo`
      self$`fields` <- ArchiveSnapshotOnExchangesBodyObject$`fields`
    }
  )
)
