# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' BondDateOptionsFieldsBody Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BondDateOptionsFieldsBody <- R6::R6Class(
  'BondDateOptionsFieldsBody',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      BondDateOptionsFieldsBodyObject <- list()

      BondDateOptionsFieldsBodyObject
    },
    fromJSON = function(BondDateOptionsFieldsBodyJson) {
      BondDateOptionsFieldsBodyObject <- jsonlite::fromJSON(BondDateOptionsFieldsBodyJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(BondDateOptionsFieldsBodyJson) {
      BondDateOptionsFieldsBodyObject <- jsonlite::fromJSON(BondDateOptionsFieldsBodyJson)
    }
  )
)
