# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' BondListOrgRolesBody Class
#'
#' @field filter 
#' @field count 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BondListOrgRolesBody <- R6::R6Class(
  'BondListOrgRolesBody',
  public = list(
    `filter` = NULL,
    `count` = NULL,
    initialize = function(`filter`, `count`){
      if (!missing(`filter`)) {
        stopifnot(is.character(`filter`), length(`filter`) == 1)
        self$`filter` <- `filter`
      }
      if (!missing(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
        self$`count` <- `count`
      }
    },
    toJSON = function() {
      BondListOrgRolesBodyObject <- list()
      if (!is.null(self$`filter`)) {
        BondListOrgRolesBodyObject[['filter']] <- self$`filter`
      }
      if (!is.null(self$`count`)) {
        BondListOrgRolesBodyObject[['count']] <- self$`count`
      }

      BondListOrgRolesBodyObject
    },
    fromJSON = function(BondListOrgRolesBodyJson) {
      BondListOrgRolesBodyObject <- jsonlite::fromJSON(BondListOrgRolesBodyJson)
      if (!is.null(BondListOrgRolesBodyObject$`filter`)) {
        self$`filter` <- BondListOrgRolesBodyObject$`filter`
      }
      if (!is.null(BondListOrgRolesBodyObject$`count`)) {
        self$`count` <- BondListOrgRolesBodyObject$`count`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "filter": %s,
           "count": %d
        }',
        self$`filter`,
        self$`count`
      )
    },
    fromJSONString = function(BondListOrgRolesBodyJson) {
      BondListOrgRolesBodyObject <- jsonlite::fromJSON(BondListOrgRolesBodyJson)
      self$`filter` <- BondListOrgRolesBodyObject$`filter`
      self$`count` <- BondListOrgRolesBodyObject$`count`
    }
  )
)
