# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRiskAmortisationsResponse Class
#'
#' @field dates 
#' @field parts 
#' @field error 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRiskAmortisationsResponse <- R6::R6Class(
  'EfirDataHubModelsModelsRiskAmortisationsResponse',
  public = list(
    `dates` = NULL,
    `parts` = NULL,
    `error` = NULL,
    initialize = function(`dates`, `parts`, `error`){
      if (!missing(`dates`)) {
        stopifnot(is.list(`dates`), length(`dates`) != 0)
        lapply(`dates`, function(x) stopifnot(is.character(x)))
        self$`dates` <- `dates`
      }
      if (!missing(`parts`)) {
        stopifnot(is.list(`parts`), length(`parts`) != 0)
        lapply(`parts`, function(x) stopifnot(is.character(x)))
        self$`parts` <- `parts`
      }
      if (!missing(`error`)) {
        stopifnot(is.character(`error`), length(`error`) == 1)
        self$`error` <- `error`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRiskAmortisationsResponseObject <- list()
      if (!is.null(self$`dates`)) {
        EfirDataHubModelsModelsRiskAmortisationsResponseObject[['dates']] <- self$`dates`
      }
      if (!is.null(self$`parts`)) {
        EfirDataHubModelsModelsRiskAmortisationsResponseObject[['parts']] <- self$`parts`
      }
      if (!is.null(self$`error`)) {
        EfirDataHubModelsModelsRiskAmortisationsResponseObject[['error']] <- self$`error`
      }

      EfirDataHubModelsModelsRiskAmortisationsResponseObject
    },
    fromJSON = function(EfirDataHubModelsModelsRiskAmortisationsResponseJson) {
      EfirDataHubModelsModelsRiskAmortisationsResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskAmortisationsResponseJson)
      if (!is.null(EfirDataHubModelsModelsRiskAmortisationsResponseObject$`dates`)) {
        self$`dates` <- EfirDataHubModelsModelsRiskAmortisationsResponseObject$`dates`
      }
      if (!is.null(EfirDataHubModelsModelsRiskAmortisationsResponseObject$`parts`)) {
        self$`parts` <- EfirDataHubModelsModelsRiskAmortisationsResponseObject$`parts`
      }
      if (!is.null(EfirDataHubModelsModelsRiskAmortisationsResponseObject$`error`)) {
        self$`error` <- EfirDataHubModelsModelsRiskAmortisationsResponseObject$`error`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "dates": [%s],
           "parts": [%s],
           "error": %s
        }',
        lapply(self$`dates`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`parts`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`error`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRiskAmortisationsResponseJson) {
      EfirDataHubModelsModelsRiskAmortisationsResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskAmortisationsResponseJson)
      self$`dates` <- EfirDataHubModelsModelsRiskAmortisationsResponseObject$`dates`
      self$`parts` <- EfirDataHubModelsModelsRiskAmortisationsResponseObject$`parts`
      self$`error` <- EfirDataHubModelsModelsRiskAmortisationsResponseObject$`error`
    }
  )
)
