# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequest Class
#'
#' @field engine 
#' @field market 
#' @field boardIds 
#' @field instruments 
#' @field dateFrom 
#' @field dateTo 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequest',
  public = list(
    `engine` = NULL,
    `market` = NULL,
    `boardIds` = NULL,
    `instruments` = NULL,
    `dateFrom` = NULL,
    `dateTo` = NULL,
    initialize = function(`engine`, `market`, `boardIds`, `instruments`, `dateFrom`, `dateTo`){
      if (!missing(`engine`)) {
        stopifnot(is.character(`engine`), length(`engine`) == 1)
        self$`engine` <- `engine`
      }
      if (!missing(`market`)) {
        stopifnot(is.character(`market`), length(`market`) == 1)
        self$`market` <- `market`
      }
      if (!missing(`boardIds`)) {
        stopifnot(is.list(`boardIds`), length(`boardIds`) != 0)
        lapply(`boardIds`, function(x) stopifnot(is.character(x)))
        self$`boardIds` <- `boardIds`
      }
      if (!missing(`instruments`)) {
        stopifnot(is.list(`instruments`), length(`instruments`) != 0)
        lapply(`instruments`, function(x) stopifnot(is.character(x)))
        self$`instruments` <- `instruments`
      }
      if (!missing(`dateFrom`)) {
        stopifnot(is.character(`dateFrom`), length(`dateFrom`) == 1)
        self$`dateFrom` <- `dateFrom`
      }
      if (!missing(`dateTo`)) {
        stopifnot(is.character(`dateTo`), length(`dateTo`) == 1)
        self$`dateTo` <- `dateTo`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject <- list()
      if (!is.null(self$`engine`)) {
        EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject[['engine']] <- self$`engine`
      }
      if (!is.null(self$`market`)) {
        EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject[['market']] <- self$`market`
      }
      if (!is.null(self$`boardIds`)) {
        EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject[['boardIds']] <- self$`boardIds`
      }
      if (!is.null(self$`instruments`)) {
        EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject[['instruments']] <- self$`instruments`
      }
      if (!is.null(self$`dateFrom`)) {
        EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject[['dateFrom']] <- self$`dateFrom`
      }
      if (!is.null(self$`dateTo`)) {
        EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject[['dateTo']] <- self$`dateTo`
      }

      EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestJson) {
      EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`engine`)) {
        self$`engine` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`engine`
      }
      if (!is.null(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`market`)) {
        self$`market` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`market`
      }
      if (!is.null(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`boardIds`)) {
        self$`boardIds` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`boardIds`
      }
      if (!is.null(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`instruments`)) {
        self$`instruments` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`instruments`
      }
      if (!is.null(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`dateFrom`)) {
        self$`dateFrom` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`dateFrom`
      }
      if (!is.null(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`dateTo`)) {
        self$`dateTo` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`dateTo`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "engine": %s,
           "market": %s,
           "boardIds": [%s],
           "instruments": [%s],
           "dateFrom": %s,
           "dateTo": %s
        }',
        self$`engine`,
        self$`market`,
        lapply(self$`boardIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`instruments`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`dateFrom`,
        self$`dateTo`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestJson) {
      EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestJson)
      self$`engine` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`engine`
      self$`market` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`market`
      self$`boardIds` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`boardIds`
      self$`instruments` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`instruments`
      self$`dateFrom` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`dateFrom`
      self$`dateTo` <- EfirDataHubModelsRequestsV2ArchiveMoexTradeHistoryRequestObject$`dateTo`
    }
  )
)
