# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsMoexOptionColumnsFields Class
#'
#' @field id 
#' @field code 
#' @field short_name_rus 
#' @field short_name_eng 
#' @field full_name_rus 
#' @field full_name_eng 
#' @field sort_order 
#' @field is_default 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsMoexOptionColumnsFields <- R6::R6Class(
  'EfirDataHubModelsModelsMoexOptionColumnsFields',
  public = list(
    `id` = NULL,
    `code` = NULL,
    `short_name_rus` = NULL,
    `short_name_eng` = NULL,
    `full_name_rus` = NULL,
    `full_name_eng` = NULL,
    `sort_order` = NULL,
    `is_default` = NULL,
    initialize = function(`id`, `code`, `short_name_rus`, `short_name_eng`, `full_name_rus`, `full_name_eng`, `sort_order`, `is_default`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`short_name_rus`)) {
        stopifnot(is.character(`short_name_rus`), length(`short_name_rus`) == 1)
        self$`short_name_rus` <- `short_name_rus`
      }
      if (!missing(`short_name_eng`)) {
        stopifnot(is.character(`short_name_eng`), length(`short_name_eng`) == 1)
        self$`short_name_eng` <- `short_name_eng`
      }
      if (!missing(`full_name_rus`)) {
        stopifnot(is.character(`full_name_rus`), length(`full_name_rus`) == 1)
        self$`full_name_rus` <- `full_name_rus`
      }
      if (!missing(`full_name_eng`)) {
        stopifnot(is.character(`full_name_eng`), length(`full_name_eng`) == 1)
        self$`full_name_eng` <- `full_name_eng`
      }
      if (!missing(`sort_order`)) {
        stopifnot(is.numeric(`sort_order`), length(`sort_order`) == 1)
        self$`sort_order` <- `sort_order`
      }
      if (!missing(`is_default`)) {
        stopifnot(is.numeric(`is_default`), length(`is_default`) == 1)
        self$`is_default` <- `is_default`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsMoexOptionColumnsFieldsObject <- list()
      if (!is.null(self$`id`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['id']] <- self$`id`
      }
      if (!is.null(self$`code`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['code']] <- self$`code`
      }
      if (!is.null(self$`short_name_rus`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['short_name_rus']] <- self$`short_name_rus`
      }
      if (!is.null(self$`short_name_eng`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['short_name_eng']] <- self$`short_name_eng`
      }
      if (!is.null(self$`full_name_rus`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['full_name_rus']] <- self$`full_name_rus`
      }
      if (!is.null(self$`full_name_eng`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['full_name_eng']] <- self$`full_name_eng`
      }
      if (!is.null(self$`sort_order`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['sort_order']] <- self$`sort_order`
      }
      if (!is.null(self$`is_default`)) {
        EfirDataHubModelsModelsMoexOptionColumnsFieldsObject[['is_default']] <- self$`is_default`
      }

      EfirDataHubModelsModelsMoexOptionColumnsFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsMoexOptionColumnsFieldsJson) {
      EfirDataHubModelsModelsMoexOptionColumnsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsMoexOptionColumnsFieldsJson)
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`id`)) {
        self$`id` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`id`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`code`)) {
        self$`code` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`code`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`short_name_rus`)) {
        self$`short_name_rus` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`short_name_rus`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`short_name_eng`)) {
        self$`short_name_eng` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`short_name_eng`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`full_name_rus`)) {
        self$`full_name_rus` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`full_name_rus`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`full_name_eng`)) {
        self$`full_name_eng` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`full_name_eng`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`sort_order`)) {
        self$`sort_order` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`sort_order`
      }
      if (!is.null(EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`is_default`)) {
        self$`is_default` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`is_default`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "code": %s,
           "short_name_rus": %s,
           "short_name_eng": %s,
           "full_name_rus": %s,
           "full_name_eng": %s,
           "sort_order": %d,
           "is_default": %d
        }',
        self$`id`,
        self$`code`,
        self$`short_name_rus`,
        self$`short_name_eng`,
        self$`full_name_rus`,
        self$`full_name_eng`,
        self$`sort_order`,
        self$`is_default`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsMoexOptionColumnsFieldsJson) {
      EfirDataHubModelsModelsMoexOptionColumnsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsMoexOptionColumnsFieldsJson)
      self$`id` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`id`
      self$`code` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`code`
      self$`short_name_rus` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`short_name_rus`
      self$`short_name_eng` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`short_name_eng`
      self$`full_name_rus` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`full_name_rus`
      self$`full_name_eng` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`full_name_eng`
      self$`sort_order` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`sort_order`
      self$`is_default` <- EfirDataHubModelsModelsMoexOptionColumnsFieldsObject$`is_default`
    }
  )
)
