# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2RatingCompanyRatingsRequest Class
#'
#' @field idType 
#' @field date 
#' @field filter 
#' @field count 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2RatingCompanyRatingsRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2RatingCompanyRatingsRequest',
  public = list(
    `idType` = NULL,
    `date` = NULL,
    `filter` = NULL,
    `count` = NULL,
    initialize = function(`idType`, `date`, `filter`, `count`){
      if (!missing(`idType`)) {
        stopifnot(is.character(`idType`), length(`idType`) == 1)
        self$`idType` <- `idType`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`filter`)) {
        stopifnot(is.character(`filter`), length(`filter`) == 1)
        self$`filter` <- `filter`
      }
      if (!missing(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
        self$`count` <- `count`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject <- list()
      if (!is.null(self$`idType`)) {
        EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject[['idType']] <- self$`idType`
      }
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject[['date']] <- self$`date`
      }
      if (!is.null(self$`filter`)) {
        EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject[['filter']] <- self$`filter`
      }
      if (!is.null(self$`count`)) {
        EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject[['count']] <- self$`count`
      }

      EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestJson) {
      EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`idType`)) {
        self$`idType` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`idType`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`date`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`filter`)) {
        self$`filter` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`filter`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`count`)) {
        self$`count` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`count`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "idType": %s,
           "date": %s,
           "filter": %s,
           "count": %d
        }',
        self$`idType`,
        self$`date`,
        self$`filter`,
        self$`count`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestJson) {
      EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestJson)
      self$`idType` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`idType`
      self$`date` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`date`
      self$`filter` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`filter`
      self$`count` <- EfirDataHubModelsRequestsV2RatingCompanyRatingsRequestObject$`count`
    }
  )
)
