# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsReportListFields Class
#'
#' @field name 
#' @field size 
#' @field createDateUtc 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsReportListFields <- R6::R6Class(
  'EfirDataHubModelsModelsReportListFields',
  public = list(
    `name` = NULL,
    `size` = NULL,
    `createDateUtc` = NULL,
    initialize = function(`name`, `size`, `createDateUtc`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`size`)) {
        stopifnot(is.numeric(`size`), length(`size`) == 1)
        self$`size` <- `size`
      }
      if (!missing(`createDateUtc`)) {
        stopifnot(is.character(`createDateUtc`), length(`createDateUtc`) == 1)
        self$`createDateUtc` <- `createDateUtc`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsReportListFieldsObject <- list()
      if (!is.null(self$`name`)) {
        EfirDataHubModelsModelsReportListFieldsObject[['name']] <- self$`name`
      }
      if (!is.null(self$`size`)) {
        EfirDataHubModelsModelsReportListFieldsObject[['size']] <- self$`size`
      }
      if (!is.null(self$`createDateUtc`)) {
        EfirDataHubModelsModelsReportListFieldsObject[['createDateUtc']] <- self$`createDateUtc`
      }

      EfirDataHubModelsModelsReportListFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsReportListFieldsJson) {
      EfirDataHubModelsModelsReportListFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsReportListFieldsJson)
      if (!is.null(EfirDataHubModelsModelsReportListFieldsObject$`name`)) {
        self$`name` <- EfirDataHubModelsModelsReportListFieldsObject$`name`
      }
      if (!is.null(EfirDataHubModelsModelsReportListFieldsObject$`size`)) {
        self$`size` <- EfirDataHubModelsModelsReportListFieldsObject$`size`
      }
      if (!is.null(EfirDataHubModelsModelsReportListFieldsObject$`createDateUtc`)) {
        self$`createDateUtc` <- EfirDataHubModelsModelsReportListFieldsObject$`createDateUtc`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "size": %d,
           "createDateUtc": %s
        }',
        self$`name`,
        self$`size`,
        self$`createDateUtc`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsReportListFieldsJson) {
      EfirDataHubModelsModelsReportListFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsReportListFieldsJson)
      self$`name` <- EfirDataHubModelsModelsReportListFieldsObject$`name`
      self$`size` <- EfirDataHubModelsModelsReportListFieldsObject$`size`
      self$`createDateUtc` <- EfirDataHubModelsModelsReportListFieldsObject$`createDateUtc`
    }
  )
)
