# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRatingAggReason Class
#'
#' @field id_rating 
#' @field last_dt 
#' @field last 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRatingAggReason <- R6::R6Class(
  'EfirDataHubModelsModelsRatingAggReason',
  public = list(
    `id_rating` = NULL,
    `last_dt` = NULL,
    `last` = NULL,
    initialize = function(`id_rating`, `last_dt`, `last`){
      if (!missing(`id_rating`)) {
        stopifnot(is.numeric(`id_rating`), length(`id_rating`) == 1)
        self$`id_rating` <- `id_rating`
      }
      if (!missing(`last_dt`)) {
        stopifnot(is.character(`last_dt`), length(`last_dt`) == 1)
        self$`last_dt` <- `last_dt`
      }
      if (!missing(`last`)) {
        stopifnot(is.character(`last`), length(`last`) == 1)
        self$`last` <- `last`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRatingAggReasonObject <- list()
      if (!is.null(self$`id_rating`)) {
        EfirDataHubModelsModelsRatingAggReasonObject[['id_rating']] <- self$`id_rating`
      }
      if (!is.null(self$`last_dt`)) {
        EfirDataHubModelsModelsRatingAggReasonObject[['last_dt']] <- self$`last_dt`
      }
      if (!is.null(self$`last`)) {
        EfirDataHubModelsModelsRatingAggReasonObject[['last']] <- self$`last`
      }

      EfirDataHubModelsModelsRatingAggReasonObject
    },
    fromJSON = function(EfirDataHubModelsModelsRatingAggReasonJson) {
      EfirDataHubModelsModelsRatingAggReasonObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingAggReasonJson)
      if (!is.null(EfirDataHubModelsModelsRatingAggReasonObject$`id_rating`)) {
        self$`id_rating` <- EfirDataHubModelsModelsRatingAggReasonObject$`id_rating`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggReasonObject$`last_dt`)) {
        self$`last_dt` <- EfirDataHubModelsModelsRatingAggReasonObject$`last_dt`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggReasonObject$`last`)) {
        self$`last` <- EfirDataHubModelsModelsRatingAggReasonObject$`last`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id_rating": %d,
           "last_dt": %s,
           "last": %s
        }',
        self$`id_rating`,
        self$`last_dt`,
        self$`last`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRatingAggReasonJson) {
      EfirDataHubModelsModelsRatingAggReasonObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingAggReasonJson)
      self$`id_rating` <- EfirDataHubModelsModelsRatingAggReasonObject$`id_rating`
      self$`last_dt` <- EfirDataHubModelsModelsRatingAggReasonObject$`last_dt`
      self$`last` <- EfirDataHubModelsModelsRatingAggReasonObject$`last`
    }
  )
)
