# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2RiskPfiParamsRequest Class
#'
#' @field isin 
#' @field date 
#' @field moexPriceType 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2RiskPfiParamsRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2RiskPfiParamsRequest',
  public = list(
    `isin` = NULL,
    `date` = NULL,
    `moexPriceType` = NULL,
    initialize = function(`isin`, `date`, `moexPriceType`){
      if (!missing(`isin`)) {
        stopifnot(is.character(`isin`), length(`isin`) == 1)
        self$`isin` <- `isin`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`moexPriceType`)) {
        stopifnot(is.character(`moexPriceType`), length(`moexPriceType`) == 1)
        self$`moexPriceType` <- `moexPriceType`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject <- list()
      if (!is.null(self$`isin`)) {
        EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject[['isin']] <- self$`isin`
      }
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject[['date']] <- self$`date`
      }
      if (!is.null(self$`moexPriceType`)) {
        EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject[['moexPriceType']] <- self$`moexPriceType`
      }

      EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2RiskPfiParamsRequestJson) {
      EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RiskPfiParamsRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`isin`)) {
        self$`isin` <- EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`isin`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`date`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`moexPriceType`)) {
        self$`moexPriceType` <- EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`moexPriceType`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "isin": %s,
           "date": %s,
           "moexPriceType": %s
        }',
        self$`isin`,
        self$`date`,
        self$`moexPriceType`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2RiskPfiParamsRequestJson) {
      EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RiskPfiParamsRequestJson)
      self$`isin` <- EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`isin`
      self$`date` <- EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`date`
      self$`moexPriceType` <- EfirDataHubModelsRequestsV2RiskPfiParamsRequestObject$`moexPriceType`
    }
  )
)
