# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2BondTimeTableRequest Class
#'
#' @field ids 
#' @field eventTypes 
#' @field fields 
#' @field startDate 
#' @field endDate 
#' @field isShowDefault 
#' @field pageNum 
#' @field pageSize 
#' @field sortDesc 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2BondTimeTableRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2BondTimeTableRequest',
  public = list(
    `ids` = NULL,
    `eventTypes` = NULL,
    `fields` = NULL,
    `startDate` = NULL,
    `endDate` = NULL,
    `isShowDefault` = NULL,
    `pageNum` = NULL,
    `pageSize` = NULL,
    `sortDesc` = NULL,
    initialize = function(`ids`, `eventTypes`, `fields`, `startDate`, `endDate`, `isShowDefault`, `pageNum`, `pageSize`, `sortDesc`){
      if (!missing(`ids`)) {
        stopifnot(is.list(`ids`), length(`ids`) != 0)
        lapply(`ids`, function(x) stopifnot(is.character(x)))
        self$`ids` <- `ids`
      }
      if (!missing(`eventTypes`)) {
        stopifnot(is.list(`eventTypes`), length(`eventTypes`) != 0)
        lapply(`eventTypes`, function(x) stopifnot(is.character(x)))
        self$`eventTypes` <- `eventTypes`
      }
      if (!missing(`fields`)) {
        stopifnot(is.list(`fields`), length(`fields`) != 0)
        lapply(`fields`, function(x) stopifnot(is.character(x)))
        self$`fields` <- `fields`
      }
      if (!missing(`startDate`)) {
        stopifnot(is.character(`startDate`), length(`startDate`) == 1)
        self$`startDate` <- `startDate`
      }
      if (!missing(`endDate`)) {
        stopifnot(is.character(`endDate`), length(`endDate`) == 1)
        self$`endDate` <- `endDate`
      }
      if (!missing(`isShowDefault`)) {
        self$`isShowDefault` <- `isShowDefault`
      }
      if (!missing(`pageNum`)) {
        stopifnot(is.numeric(`pageNum`), length(`pageNum`) == 1)
        self$`pageNum` <- `pageNum`
      }
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
      if (!missing(`sortDesc`)) {
        self$`sortDesc` <- `sortDesc`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2BondTimeTableRequestObject <- list()
      if (!is.null(self$`ids`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['ids']] <- self$`ids`
      }
      if (!is.null(self$`eventTypes`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['eventTypes']] <- self$`eventTypes`
      }
      if (!is.null(self$`fields`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['fields']] <- self$`fields`
      }
      if (!is.null(self$`startDate`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['startDate']] <- self$`startDate`
      }
      if (!is.null(self$`endDate`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['endDate']] <- self$`endDate`
      }
      if (!is.null(self$`isShowDefault`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['isShowDefault']] <- self$`isShowDefault`
      }
      if (!is.null(self$`pageNum`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['pageNum']] <- self$`pageNum`
      }
      if (!is.null(self$`pageSize`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['pageSize']] <- self$`pageSize`
      }
      if (!is.null(self$`sortDesc`)) {
        EfirDataHubModelsRequestsV2BondTimeTableRequestObject[['sortDesc']] <- self$`sortDesc`
      }

      EfirDataHubModelsRequestsV2BondTimeTableRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2BondTimeTableRequestJson) {
      EfirDataHubModelsRequestsV2BondTimeTableRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondTimeTableRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`ids`)) {
        self$`ids` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`ids`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`eventTypes`)) {
        self$`eventTypes` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`eventTypes`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`fields`)) {
        self$`fields` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`fields`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`startDate`)) {
        self$`startDate` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`startDate`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`endDate`)) {
        self$`endDate` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`endDate`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`isShowDefault`)) {
        self$`isShowDefault` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`isShowDefault`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`pageNum`)) {
        self$`pageNum` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`pageNum`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`pageSize`)) {
        self$`pageSize` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`pageSize`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`sortDesc`)) {
        self$`sortDesc` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`sortDesc`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "ids": [%s],
           "eventTypes": [%s],
           "fields": [%s],
           "startDate": %s,
           "endDate": %s,
           "isShowDefault": %s,
           "pageNum": %d,
           "pageSize": %d,
           "sortDesc": %s
        }',
        lapply(self$`ids`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`eventTypes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`fields`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`startDate`,
        self$`endDate`,
        self$`isShowDefault`,
        self$`pageNum`,
        self$`pageSize`,
        self$`sortDesc`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2BondTimeTableRequestJson) {
      EfirDataHubModelsRequestsV2BondTimeTableRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondTimeTableRequestJson)
      self$`ids` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`ids`
      self$`eventTypes` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`eventTypes`
      self$`fields` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`fields`
      self$`startDate` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`startDate`
      self$`endDate` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`endDate`
      self$`isShowDefault` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`isShowDefault`
      self$`pageNum` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`pageNum`
      self$`pageSize` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`pageSize`
      self$`sortDesc` <- EfirDataHubModelsRequestsV2BondTimeTableRequestObject$`sortDesc`
    }
  )
)
