# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsArchiveCurrencyRateResponse Class
#'
#' @field rate 
#' @field endOfDayRate 
#' @field error 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsArchiveCurrencyRateResponse <- R6::R6Class(
  'EfirDataHubModelsModelsArchiveCurrencyRateResponse',
  public = list(
    `rate` = NULL,
    `endOfDayRate` = NULL,
    `error` = NULL,
    initialize = function(`rate`, `endOfDayRate`, `error`){
      if (!missing(`rate`)) {
        stopifnot(is.numeric(`rate`), length(`rate`) == 1)
        stopifnot(R6::is.R6(`rate`))
        self$`rate` <- `rate`
      }
      if (!missing(`endOfDayRate`)) {
        stopifnot(is.numeric(`endOfDayRate`), length(`endOfDayRate`) == 1)
        self$`endOfDayRate` <- `endOfDayRate`
      }
      if (!missing(`error`)) {
        stopifnot(is.character(`error`), length(`error`) == 1)
        self$`error` <- `error`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsArchiveCurrencyRateResponseObject <- list()
      if (!is.null(self$`rate`)) {
        EfirDataHubModelsModelsArchiveCurrencyRateResponseObject[['rate']] <- self$`rate`$toJSON()
      }
      if (!is.null(self$`endOfDayRate`)) {
        EfirDataHubModelsModelsArchiveCurrencyRateResponseObject[['endOfDayRate']] <- self$`endOfDayRate`
      }
      if (!is.null(self$`error`)) {
        EfirDataHubModelsModelsArchiveCurrencyRateResponseObject[['error']] <- self$`error`
      }

      EfirDataHubModelsModelsArchiveCurrencyRateResponseObject
    },
    fromJSON = function(EfirDataHubModelsModelsArchiveCurrencyRateResponseJson) {
      EfirDataHubModelsModelsArchiveCurrencyRateResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsArchiveCurrencyRateResponseJson)
      if (!is.null(EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`rate`)) {
        rateObject <- BigDecimal$new()
        rateObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$rate, auto_unbox = TRUE))
        self$`rate` <- rateObject
      }
      if (!is.null(EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`endOfDayRate`)) {
        self$`endOfDayRate` <- EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`endOfDayRate`
      }
      if (!is.null(EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`error`)) {
        self$`error` <- EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`error`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rate": %s,
           "endOfDayRate": %d,
           "error": %s
        }',
        self$`rate`$toJSON(),
        self$`endOfDayRate`,
        self$`error`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsArchiveCurrencyRateResponseJson) {
      EfirDataHubModelsModelsArchiveCurrencyRateResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsArchiveCurrencyRateResponseJson)
      BigDecimalObject <- BigDecimal$new()
      self$`rate` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$rate, auto_unbox = TRUE))
      self$`endOfDayRate` <- EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`endOfDayRate`
      self$`error` <- EfirDataHubModelsModelsArchiveCurrencyRateResponseObject$`error`
    }
  )
)
