# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsMoexMarket Class
#'
#' @field id 
#' @field name 
#' @field title 
#' @field marketplace 
#' @field boardGroups 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsMoexMarket <- R6::R6Class(
  'EfirDataHubModelsModelsMoexMarket',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `title` = NULL,
    `marketplace` = NULL,
    `boardGroups` = NULL,
    initialize = function(`id`, `name`, `title`, `marketplace`, `boardGroups`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`marketplace`)) {
        stopifnot(is.character(`marketplace`), length(`marketplace`) == 1)
        self$`marketplace` <- `marketplace`
      }
      if (!missing(`boardGroups`)) {
        stopifnot(is.list(`boardGroups`), length(`boardGroups`) != 0)
        lapply(`boardGroups`, function(x) stopifnot(R6::is.R6(x)))
        self$`boardGroups` <- `boardGroups`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsMoexMarketObject <- list()
      if (!is.null(self$`id`)) {
        EfirDataHubModelsModelsMoexMarketObject[['id']] <- self$`id`
      }
      if (!is.null(self$`name`)) {
        EfirDataHubModelsModelsMoexMarketObject[['name']] <- self$`name`
      }
      if (!is.null(self$`title`)) {
        EfirDataHubModelsModelsMoexMarketObject[['title']] <- self$`title`
      }
      if (!is.null(self$`marketplace`)) {
        EfirDataHubModelsModelsMoexMarketObject[['marketplace']] <- self$`marketplace`
      }
      if (!is.null(self$`boardGroups`)) {
        EfirDataHubModelsModelsMoexMarketObject[['boardGroups']] <- lapply(self$`boardGroups`, function(x) x$toJSON())
      }

      EfirDataHubModelsModelsMoexMarketObject
    },
    fromJSON = function(EfirDataHubModelsModelsMoexMarketJson) {
      EfirDataHubModelsModelsMoexMarketObject <- jsonlite::fromJSON(EfirDataHubModelsModelsMoexMarketJson)
      if (!is.null(EfirDataHubModelsModelsMoexMarketObject$`id`)) {
        self$`id` <- EfirDataHubModelsModelsMoexMarketObject$`id`
      }
      if (!is.null(EfirDataHubModelsModelsMoexMarketObject$`name`)) {
        self$`name` <- EfirDataHubModelsModelsMoexMarketObject$`name`
      }
      if (!is.null(EfirDataHubModelsModelsMoexMarketObject$`title`)) {
        self$`title` <- EfirDataHubModelsModelsMoexMarketObject$`title`
      }
      if (!is.null(EfirDataHubModelsModelsMoexMarketObject$`marketplace`)) {
        self$`marketplace` <- EfirDataHubModelsModelsMoexMarketObject$`marketplace`
      }
      if (!is.null(EfirDataHubModelsModelsMoexMarketObject$`boardGroups`)) {
        self$`boardGroups` <- lapply(EfirDataHubModelsModelsMoexMarketObject$`boardGroups`, function(x) {
          boardGroupsObject <- EfirDataHubModelsModelsMoexBoardGroup$new()
          boardGroupsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          boardGroupsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "name": %s,
           "title": %s,
           "marketplace": %s,
           "boardGroups": [%s]
        }',
        self$`id`,
        self$`name`,
        self$`title`,
        self$`marketplace`,
        lapply(self$`boardGroups`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsMoexMarketJson) {
      EfirDataHubModelsModelsMoexMarketObject <- jsonlite::fromJSON(EfirDataHubModelsModelsMoexMarketJson)
      self$`id` <- EfirDataHubModelsModelsMoexMarketObject$`id`
      self$`name` <- EfirDataHubModelsModelsMoexMarketObject$`name`
      self$`title` <- EfirDataHubModelsModelsMoexMarketObject$`title`
      self$`marketplace` <- EfirDataHubModelsModelsMoexMarketObject$`marketplace`
      self$`boardGroups` <- lapply(EfirDataHubModelsModelsMoexMarketObject$`boardGroups`, function(x) EfirDataHubModelsModelsMoexBoardGroup$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
