# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2BondDefaultEventsRequest Class
#'
#' @field filter 
#' @field sortDesc 
#' @field pageNum 
#' @field pageSize 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2BondDefaultEventsRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2BondDefaultEventsRequest',
  public = list(
    `filter` = NULL,
    `sortDesc` = NULL,
    `pageNum` = NULL,
    `pageSize` = NULL,
    initialize = function(`filter`, `sortDesc`, `pageNum`, `pageSize`){
      if (!missing(`filter`)) {
        stopifnot(is.character(`filter`), length(`filter`) == 1)
        self$`filter` <- `filter`
      }
      if (!missing(`sortDesc`)) {
        self$`sortDesc` <- `sortDesc`
      }
      if (!missing(`pageNum`)) {
        stopifnot(is.numeric(`pageNum`), length(`pageNum`) == 1)
        self$`pageNum` <- `pageNum`
      }
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject <- list()
      if (!is.null(self$`filter`)) {
        EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject[['filter']] <- self$`filter`
      }
      if (!is.null(self$`sortDesc`)) {
        EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject[['sortDesc']] <- self$`sortDesc`
      }
      if (!is.null(self$`pageNum`)) {
        EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject[['pageNum']] <- self$`pageNum`
      }
      if (!is.null(self$`pageSize`)) {
        EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject[['pageSize']] <- self$`pageSize`
      }

      EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2BondDefaultEventsRequestJson) {
      EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondDefaultEventsRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`filter`)) {
        self$`filter` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`filter`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`sortDesc`)) {
        self$`sortDesc` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`sortDesc`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`pageNum`)) {
        self$`pageNum` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`pageNum`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`pageSize`)) {
        self$`pageSize` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`pageSize`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "filter": %s,
           "sortDesc": %s,
           "pageNum": %d,
           "pageSize": %d
        }',
        self$`filter`,
        self$`sortDesc`,
        self$`pageNum`,
        self$`pageSize`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2BondDefaultEventsRequestJson) {
      EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondDefaultEventsRequestJson)
      self$`filter` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`filter`
      self$`sortDesc` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`sortDesc`
      self$`pageNum` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`pageNum`
      self$`pageSize` <- EfirDataHubModelsRequestsV2BondDefaultEventsRequestObject$`pageSize`
    }
  )
)
