# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsBondOfferorsGuarantsFields Class
#'
#' @field fintoolId 
#' @field fininstid_guarant 
#' @field fininstid_offeror 
#' @field counter 
#' @field rn 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsBondOfferorsGuarantsFields <- R6::R6Class(
  'EfirDataHubModelsModelsBondOfferorsGuarantsFields',
  public = list(
    `fintoolId` = NULL,
    `fininstid_guarant` = NULL,
    `fininstid_offeror` = NULL,
    `counter` = NULL,
    `rn` = NULL,
    initialize = function(`fintoolId`, `fininstid_guarant`, `fininstid_offeror`, `counter`, `rn`){
      if (!missing(`fintoolId`)) {
        stopifnot(is.numeric(`fintoolId`), length(`fintoolId`) == 1)
        self$`fintoolId` <- `fintoolId`
      }
      if (!missing(`fininstid_guarant`)) {
        stopifnot(is.numeric(`fininstid_guarant`), length(`fininstid_guarant`) == 1)
        self$`fininstid_guarant` <- `fininstid_guarant`
      }
      if (!missing(`fininstid_offeror`)) {
        stopifnot(is.numeric(`fininstid_offeror`), length(`fininstid_offeror`) == 1)
        self$`fininstid_offeror` <- `fininstid_offeror`
      }
      if (!missing(`counter`)) {
        stopifnot(is.numeric(`counter`), length(`counter`) == 1)
        self$`counter` <- `counter`
      }
      if (!missing(`rn`)) {
        stopifnot(is.numeric(`rn`), length(`rn`) == 1)
        self$`rn` <- `rn`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject <- list()
      if (!is.null(self$`fintoolId`)) {
        EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject[['fintoolId']] <- self$`fintoolId`
      }
      if (!is.null(self$`fininstid_guarant`)) {
        EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject[['fininstid_guarant']] <- self$`fininstid_guarant`
      }
      if (!is.null(self$`fininstid_offeror`)) {
        EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject[['fininstid_offeror']] <- self$`fininstid_offeror`
      }
      if (!is.null(self$`counter`)) {
        EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject[['counter']] <- self$`counter`
      }
      if (!is.null(self$`rn`)) {
        EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject[['rn']] <- self$`rn`
      }

      EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsJson) {
      EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsJson)
      if (!is.null(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fintoolId`)) {
        self$`fintoolId` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fintoolId`
      }
      if (!is.null(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fininstid_guarant`)) {
        self$`fininstid_guarant` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fininstid_guarant`
      }
      if (!is.null(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fininstid_offeror`)) {
        self$`fininstid_offeror` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fininstid_offeror`
      }
      if (!is.null(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`counter`)) {
        self$`counter` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`counter`
      }
      if (!is.null(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`rn`)) {
        self$`rn` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`rn`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fintoolId": %d,
           "fininstid_guarant": %d,
           "fininstid_offeror": %d,
           "counter": %d,
           "rn": %d
        }',
        self$`fintoolId`,
        self$`fininstid_guarant`,
        self$`fininstid_offeror`,
        self$`counter`,
        self$`rn`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsJson) {
      EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsBondOfferorsGuarantsFieldsJson)
      self$`fintoolId` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fintoolId`
      self$`fininstid_guarant` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fininstid_guarant`
      self$`fininstid_offeror` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`fininstid_offeror`
      self$`counter` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`counter`
      self$`rn` <- EfirDataHubModelsModelsBondOfferorsGuarantsFieldsObject$`rn`
    }
  )
)
