# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequest Class
#'
#' @field aggType 
#' @field priorityAgency 
#' @field usingType 
#' @field depthInMonths 
#' @field scaleRatioId 
#' @field fintoolIds 
#' @field date 
#' @field ratingCodes 
#' @field ratingListName 
#' @field useFreezing 
#' @field freezingType 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequest',
  public = list(
    `aggType` = NULL,
    `priorityAgency` = NULL,
    `usingType` = NULL,
    `depthInMonths` = NULL,
    `scaleRatioId` = NULL,
    `fintoolIds` = NULL,
    `date` = NULL,
    `ratingCodes` = NULL,
    `ratingListName` = NULL,
    `useFreezing` = NULL,
    `freezingType` = NULL,
    initialize = function(`aggType`, `priorityAgency`, `usingType`, `depthInMonths`, `scaleRatioId`, `fintoolIds`, `date`, `ratingCodes`, `ratingListName`, `useFreezing`, `freezingType`){
      if (!missing(`aggType`)) {
        stopifnot(is.character(`aggType`), length(`aggType`) == 1)
        self$`aggType` <- `aggType`
      }
      if (!missing(`priorityAgency`)) {
        stopifnot(is.character(`priorityAgency`), length(`priorityAgency`) == 1)
        self$`priorityAgency` <- `priorityAgency`
      }
      if (!missing(`usingType`)) {
        stopifnot(is.character(`usingType`), length(`usingType`) == 1)
        self$`usingType` <- `usingType`
      }
      if (!missing(`depthInMonths`)) {
        stopifnot(is.numeric(`depthInMonths`), length(`depthInMonths`) == 1)
        self$`depthInMonths` <- `depthInMonths`
      }
      if (!missing(`scaleRatioId`)) {
        stopifnot(is.numeric(`scaleRatioId`), length(`scaleRatioId`) == 1)
        self$`scaleRatioId` <- `scaleRatioId`
      }
      if (!missing(`fintoolIds`)) {
        stopifnot(is.list(`fintoolIds`), length(`fintoolIds`) != 0)
        lapply(`fintoolIds`, function(x) stopifnot(is.character(x)))
        self$`fintoolIds` <- `fintoolIds`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`ratingCodes`)) {
        stopifnot(is.list(`ratingCodes`), length(`ratingCodes`) != 0)
        lapply(`ratingCodes`, function(x) stopifnot(is.character(x)))
        self$`ratingCodes` <- `ratingCodes`
      }
      if (!missing(`ratingListName`)) {
        stopifnot(is.character(`ratingListName`), length(`ratingListName`) == 1)
        self$`ratingListName` <- `ratingListName`
      }
      if (!missing(`useFreezing`)) {
        self$`useFreezing` <- `useFreezing`
      }
      if (!missing(`freezingType`)) {
        stopifnot(R6::is.R6(`freezingType`))
        self$`freezingType` <- `freezingType`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject <- list()
      if (!is.null(self$`aggType`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['aggType']] <- self$`aggType`
      }
      if (!is.null(self$`priorityAgency`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['priorityAgency']] <- self$`priorityAgency`
      }
      if (!is.null(self$`usingType`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['usingType']] <- self$`usingType`
      }
      if (!is.null(self$`depthInMonths`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['depthInMonths']] <- self$`depthInMonths`
      }
      if (!is.null(self$`scaleRatioId`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['scaleRatioId']] <- self$`scaleRatioId`
      }
      if (!is.null(self$`fintoolIds`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['fintoolIds']] <- self$`fintoolIds`
      }
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['date']] <- self$`date`
      }
      if (!is.null(self$`ratingCodes`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['ratingCodes']] <- self$`ratingCodes`
      }
      if (!is.null(self$`ratingListName`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['ratingListName']] <- self$`ratingListName`
      }
      if (!is.null(self$`useFreezing`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['useFreezing']] <- self$`useFreezing`
      }
      if (!is.null(self$`freezingType`)) {
        EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject[['freezingType']] <- self$`freezingType`$toJSON()
      }

      EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestJson) {
      EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`aggType`)) {
        self$`aggType` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`aggType`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`priorityAgency`)) {
        self$`priorityAgency` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`priorityAgency`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`usingType`)) {
        self$`usingType` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`usingType`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`depthInMonths`)) {
        self$`depthInMonths` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`depthInMonths`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`scaleRatioId`)) {
        self$`scaleRatioId` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`scaleRatioId`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`fintoolIds`)) {
        self$`fintoolIds` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`fintoolIds`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`date`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`ratingCodes`)) {
        self$`ratingCodes` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`ratingCodes`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`ratingListName`)) {
        self$`ratingListName` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`ratingListName`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`useFreezing`)) {
        self$`useFreezing` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`useFreezing`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`freezingType`)) {
        freezingTypeObject <- AllOfEfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestFreezingType$new()
        freezingTypeObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$freezingType, auto_unbox = TRUE))
        self$`freezingType` <- freezingTypeObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "aggType": %s,
           "priorityAgency": %s,
           "usingType": %s,
           "depthInMonths": %d,
           "scaleRatioId": %d,
           "fintoolIds": [%s],
           "date": %s,
           "ratingCodes": [%s],
           "ratingListName": %s,
           "useFreezing": %s,
           "freezingType": %s
        }',
        self$`aggType`,
        self$`priorityAgency`,
        self$`usingType`,
        self$`depthInMonths`,
        self$`scaleRatioId`,
        lapply(self$`fintoolIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`date`,
        lapply(self$`ratingCodes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`ratingListName`,
        self$`useFreezing`,
        self$`freezingType`$toJSON()
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestJson) {
      EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestJson)
      self$`aggType` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`aggType`
      self$`priorityAgency` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`priorityAgency`
      self$`usingType` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`usingType`
      self$`depthInMonths` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`depthInMonths`
      self$`scaleRatioId` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`scaleRatioId`
      self$`fintoolIds` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`fintoolIds`
      self$`date` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`date`
      self$`ratingCodes` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`ratingCodes`
      self$`ratingListName` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`ratingListName`
      self$`useFreezing` <- EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$`useFreezing`
      AllOfEfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestFreezingTypeObject <- AllOfEfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestFreezingType$new()
      self$`freezingType` <- AllOfEfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestFreezingTypeObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsRequestsV2RatingRatingAggSecurityRequestObject$freezingType, auto_unbox = TRUE))
    }
  )
)
