# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsSolvencyRatingAggCompanyFields Class
#'
#' @field fininstId 
#' @field aggregatedRatingLevel 
#' @field ratingCode 
#' @field ratingId 
#' @field ratingAgencyId 
#' @field ratingScaleId 
#' @field ratingValue 
#' @field ratingDate 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsSolvencyRatingAggCompanyFields <- R6::R6Class(
  'EfirDataHubModelsModelsSolvencyRatingAggCompanyFields',
  public = list(
    `fininstId` = NULL,
    `aggregatedRatingLevel` = NULL,
    `ratingCode` = NULL,
    `ratingId` = NULL,
    `ratingAgencyId` = NULL,
    `ratingScaleId` = NULL,
    `ratingValue` = NULL,
    `ratingDate` = NULL,
    initialize = function(`fininstId`, `aggregatedRatingLevel`, `ratingCode`, `ratingId`, `ratingAgencyId`, `ratingScaleId`, `ratingValue`, `ratingDate`){
      if (!missing(`fininstId`)) {
        stopifnot(is.numeric(`fininstId`), length(`fininstId`) == 1)
        self$`fininstId` <- `fininstId`
      }
      if (!missing(`aggregatedRatingLevel`)) {
        stopifnot(is.numeric(`aggregatedRatingLevel`), length(`aggregatedRatingLevel`) == 1)
        self$`aggregatedRatingLevel` <- `aggregatedRatingLevel`
      }
      if (!missing(`ratingCode`)) {
        stopifnot(is.character(`ratingCode`), length(`ratingCode`) == 1)
        self$`ratingCode` <- `ratingCode`
      }
      if (!missing(`ratingId`)) {
        stopifnot(is.numeric(`ratingId`), length(`ratingId`) == 1)
        self$`ratingId` <- `ratingId`
      }
      if (!missing(`ratingAgencyId`)) {
        stopifnot(is.numeric(`ratingAgencyId`), length(`ratingAgencyId`) == 1)
        self$`ratingAgencyId` <- `ratingAgencyId`
      }
      if (!missing(`ratingScaleId`)) {
        stopifnot(is.numeric(`ratingScaleId`), length(`ratingScaleId`) == 1)
        self$`ratingScaleId` <- `ratingScaleId`
      }
      if (!missing(`ratingValue`)) {
        stopifnot(is.character(`ratingValue`), length(`ratingValue`) == 1)
        self$`ratingValue` <- `ratingValue`
      }
      if (!missing(`ratingDate`)) {
        stopifnot(is.character(`ratingDate`), length(`ratingDate`) == 1)
        self$`ratingDate` <- `ratingDate`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject <- list()
      if (!is.null(self$`fininstId`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['fininstId']] <- self$`fininstId`
      }
      if (!is.null(self$`aggregatedRatingLevel`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['aggregatedRatingLevel']] <- self$`aggregatedRatingLevel`
      }
      if (!is.null(self$`ratingCode`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['ratingCode']] <- self$`ratingCode`
      }
      if (!is.null(self$`ratingId`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['ratingId']] <- self$`ratingId`
      }
      if (!is.null(self$`ratingAgencyId`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['ratingAgencyId']] <- self$`ratingAgencyId`
      }
      if (!is.null(self$`ratingScaleId`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['ratingScaleId']] <- self$`ratingScaleId`
      }
      if (!is.null(self$`ratingValue`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['ratingValue']] <- self$`ratingValue`
      }
      if (!is.null(self$`ratingDate`)) {
        EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject[['ratingDate']] <- self$`ratingDate`
      }

      EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsJson) {
      EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsJson)
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`fininstId`)) {
        self$`fininstId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`fininstId`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`aggregatedRatingLevel`)) {
        self$`aggregatedRatingLevel` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`aggregatedRatingLevel`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingCode`)) {
        self$`ratingCode` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingCode`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingId`)) {
        self$`ratingId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingId`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingAgencyId`)) {
        self$`ratingAgencyId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingAgencyId`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingScaleId`)) {
        self$`ratingScaleId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingScaleId`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingValue`)) {
        self$`ratingValue` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingValue`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingDate`)) {
        self$`ratingDate` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingDate`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fininstId": %d,
           "aggregatedRatingLevel": %d,
           "ratingCode": %s,
           "ratingId": %d,
           "ratingAgencyId": %d,
           "ratingScaleId": %d,
           "ratingValue": %s,
           "ratingDate": %s
        }',
        self$`fininstId`,
        self$`aggregatedRatingLevel`,
        self$`ratingCode`,
        self$`ratingId`,
        self$`ratingAgencyId`,
        self$`ratingScaleId`,
        self$`ratingValue`,
        self$`ratingDate`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsJson) {
      EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsJson)
      self$`fininstId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`fininstId`
      self$`aggregatedRatingLevel` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`aggregatedRatingLevel`
      self$`ratingCode` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingCode`
      self$`ratingId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingId`
      self$`ratingAgencyId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingAgencyId`
      self$`ratingScaleId` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingScaleId`
      self$`ratingValue` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingValue`
      self$`ratingDate` <- EfirDataHubModelsModelsSolvencyRatingAggCompanyFieldsObject$`ratingDate`
    }
  )
)
