# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRatingAggregationScaleRatioListFields Class
#'
#' @field line_number 
#' @field ru_level 
#' @field big3_level 
#' @field final_level 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRatingAggregationScaleRatioListFields <- R6::R6Class(
  'EfirDataHubModelsModelsRatingAggregationScaleRatioListFields',
  public = list(
    `line_number` = NULL,
    `ru_level` = NULL,
    `big3_level` = NULL,
    `final_level` = NULL,
    initialize = function(`line_number`, `ru_level`, `big3_level`, `final_level`){
      if (!missing(`line_number`)) {
        stopifnot(is.numeric(`line_number`), length(`line_number`) == 1)
        self$`line_number` <- `line_number`
      }
      if (!missing(`ru_level`)) {
        stopifnot(is.numeric(`ru_level`), length(`ru_level`) == 1)
        self$`ru_level` <- `ru_level`
      }
      if (!missing(`big3_level`)) {
        stopifnot(is.numeric(`big3_level`), length(`big3_level`) == 1)
        self$`big3_level` <- `big3_level`
      }
      if (!missing(`final_level`)) {
        stopifnot(is.numeric(`final_level`), length(`final_level`) == 1)
        self$`final_level` <- `final_level`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject <- list()
      if (!is.null(self$`line_number`)) {
        EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject[['line_number']] <- self$`line_number`
      }
      if (!is.null(self$`ru_level`)) {
        EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject[['ru_level']] <- self$`ru_level`
      }
      if (!is.null(self$`big3_level`)) {
        EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject[['big3_level']] <- self$`big3_level`
      }
      if (!is.null(self$`final_level`)) {
        EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject[['final_level']] <- self$`final_level`
      }

      EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsJson) {
      EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsJson)
      if (!is.null(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`line_number`)) {
        self$`line_number` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`line_number`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`ru_level`)) {
        self$`ru_level` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`ru_level`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`big3_level`)) {
        self$`big3_level` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`big3_level`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`final_level`)) {
        self$`final_level` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`final_level`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "line_number": %d,
           "ru_level": %d,
           "big3_level": %d,
           "final_level": %d
        }',
        self$`line_number`,
        self$`ru_level`,
        self$`big3_level`,
        self$`final_level`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsJson) {
      EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsJson)
      self$`line_number` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`line_number`
      self$`ru_level` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`ru_level`
      self$`big3_level` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`big3_level`
      self$`final_level` <- EfirDataHubModelsModelsRatingAggregationScaleRatioListFieldsObject$`final_level`
    }
  )
)
