# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsAccountSubscriptionPrivilege Class
#'
#' @field privilegeId 
#' @field userId 
#' @field roleId 
#' @field productId 
#' @field code 
#' @field name 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsAccountSubscriptionPrivilege <- R6::R6Class(
  'EfirDataHubModelsModelsAccountSubscriptionPrivilege',
  public = list(
    `privilegeId` = NULL,
    `userId` = NULL,
    `roleId` = NULL,
    `productId` = NULL,
    `code` = NULL,
    `name` = NULL,
    initialize = function(`privilegeId`, `userId`, `roleId`, `productId`, `code`, `name`){
      if (!missing(`privilegeId`)) {
        stopifnot(is.numeric(`privilegeId`), length(`privilegeId`) == 1)
        self$`privilegeId` <- `privilegeId`
      }
      if (!missing(`userId`)) {
        stopifnot(is.numeric(`userId`), length(`userId`) == 1)
        self$`userId` <- `userId`
      }
      if (!missing(`roleId`)) {
        stopifnot(is.numeric(`roleId`), length(`roleId`) == 1)
        self$`roleId` <- `roleId`
      }
      if (!missing(`productId`)) {
        stopifnot(is.numeric(`productId`), length(`productId`) == 1)
        self$`productId` <- `productId`
      }
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject <- list()
      if (!is.null(self$`privilegeId`)) {
        EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject[['privilegeId']] <- self$`privilegeId`
      }
      if (!is.null(self$`userId`)) {
        EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject[['userId']] <- self$`userId`
      }
      if (!is.null(self$`roleId`)) {
        EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject[['roleId']] <- self$`roleId`
      }
      if (!is.null(self$`productId`)) {
        EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject[['productId']] <- self$`productId`
      }
      if (!is.null(self$`code`)) {
        EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject[['code']] <- self$`code`
      }
      if (!is.null(self$`name`)) {
        EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject[['name']] <- self$`name`
      }

      EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject
    },
    fromJSON = function(EfirDataHubModelsModelsAccountSubscriptionPrivilegeJson) {
      EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject <- jsonlite::fromJSON(EfirDataHubModelsModelsAccountSubscriptionPrivilegeJson)
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`privilegeId`)) {
        self$`privilegeId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`privilegeId`
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`userId`)) {
        self$`userId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`userId`
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`roleId`)) {
        self$`roleId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`roleId`
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`productId`)) {
        self$`productId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`productId`
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`code`)) {
        self$`code` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`code`
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`name`)) {
        self$`name` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`name`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "privilegeId": %d,
           "userId": %d,
           "roleId": %d,
           "productId": %d,
           "code": %s,
           "name": %s
        }',
        self$`privilegeId`,
        self$`userId`,
        self$`roleId`,
        self$`productId`,
        self$`code`,
        self$`name`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsAccountSubscriptionPrivilegeJson) {
      EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject <- jsonlite::fromJSON(EfirDataHubModelsModelsAccountSubscriptionPrivilegeJson)
      self$`privilegeId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`privilegeId`
      self$`userId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`userId`
      self$`roleId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`roleId`
      self$`productId` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`productId`
      self$`code` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`code`
      self$`name` <- EfirDataHubModelsModelsAccountSubscriptionPrivilegeObject$`name`
    }
  )
)
