# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2SolvencyRatingListRequest Class
#'
#' @field date 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2SolvencyRatingListRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2SolvencyRatingListRequest',
  public = list(
    `date` = NULL,
    initialize = function(`date`){
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject <- list()
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject[['date']] <- self$`date`
      }

      EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2SolvencyRatingListRequestJson) {
      EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2SolvencyRatingListRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject$`date`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "date": %s
        }',
        self$`date`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2SolvencyRatingListRequestJson) {
      EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2SolvencyRatingListRequestJson)
      self$`date` <- EfirDataHubModelsRequestsV2SolvencyRatingListRequestObject$`date`
    }
  )
)
