# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsInfoEnumValuesFields Class
#'
#' @field id 
#' @field val 
#' @field fullname_rus 
#' @field val_id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsInfoEnumValuesFields <- R6::R6Class(
  'EfirDataHubModelsModelsInfoEnumValuesFields',
  public = list(
    `id` = NULL,
    `val` = NULL,
    `fullname_rus` = NULL,
    `val_id` = NULL,
    initialize = function(`id`, `val`, `fullname_rus`, `val_id`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`val`)) {
        stopifnot(is.character(`val`), length(`val`) == 1)
        self$`val` <- `val`
      }
      if (!missing(`fullname_rus`)) {
        stopifnot(is.character(`fullname_rus`), length(`fullname_rus`) == 1)
        self$`fullname_rus` <- `fullname_rus`
      }
      if (!missing(`val_id`)) {
        stopifnot(is.numeric(`val_id`), length(`val_id`) == 1)
        self$`val_id` <- `val_id`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsInfoEnumValuesFieldsObject <- list()
      if (!is.null(self$`id`)) {
        EfirDataHubModelsModelsInfoEnumValuesFieldsObject[['id']] <- self$`id`
      }
      if (!is.null(self$`val`)) {
        EfirDataHubModelsModelsInfoEnumValuesFieldsObject[['val']] <- self$`val`
      }
      if (!is.null(self$`fullname_rus`)) {
        EfirDataHubModelsModelsInfoEnumValuesFieldsObject[['fullname_rus']] <- self$`fullname_rus`
      }
      if (!is.null(self$`val_id`)) {
        EfirDataHubModelsModelsInfoEnumValuesFieldsObject[['val_id']] <- self$`val_id`
      }

      EfirDataHubModelsModelsInfoEnumValuesFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsInfoEnumValuesFieldsJson) {
      EfirDataHubModelsModelsInfoEnumValuesFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsInfoEnumValuesFieldsJson)
      if (!is.null(EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`id`)) {
        self$`id` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`id`
      }
      if (!is.null(EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`val`)) {
        self$`val` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`val`
      }
      if (!is.null(EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`fullname_rus`)) {
        self$`fullname_rus` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`fullname_rus`
      }
      if (!is.null(EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`val_id`)) {
        self$`val_id` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`val_id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "val": %s,
           "fullname_rus": %s,
           "val_id": %d
        }',
        self$`id`,
        self$`val`,
        self$`fullname_rus`,
        self$`val_id`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsInfoEnumValuesFieldsJson) {
      EfirDataHubModelsModelsInfoEnumValuesFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsInfoEnumValuesFieldsJson)
      self$`id` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`id`
      self$`val` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`val`
      self$`fullname_rus` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`fullname_rus`
      self$`val_id` <- EfirDataHubModelsModelsInfoEnumValuesFieldsObject$`val_id`
    }
  )
)
