# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequest Class
#'
#' @field fintoolIds 
#' @field date 
#' @field aggType 
#' @field ratingCodes 
#' @field ratingListName 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequest',
  public = list(
    `fintoolIds` = NULL,
    `date` = NULL,
    `aggType` = NULL,
    `ratingCodes` = NULL,
    `ratingListName` = NULL,
    initialize = function(`fintoolIds`, `date`, `aggType`, `ratingCodes`, `ratingListName`){
      if (!missing(`fintoolIds`)) {
        stopifnot(is.list(`fintoolIds`), length(`fintoolIds`) != 0)
        lapply(`fintoolIds`, function(x) stopifnot(is.character(x)))
        self$`fintoolIds` <- `fintoolIds`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`aggType`)) {
        stopifnot(is.character(`aggType`), length(`aggType`) == 1)
        self$`aggType` <- `aggType`
      }
      if (!missing(`ratingCodes`)) {
        stopifnot(is.list(`ratingCodes`), length(`ratingCodes`) != 0)
        lapply(`ratingCodes`, function(x) stopifnot(is.character(x)))
        self$`ratingCodes` <- `ratingCodes`
      }
      if (!missing(`ratingListName`)) {
        stopifnot(is.character(`ratingListName`), length(`ratingListName`) == 1)
        self$`ratingListName` <- `ratingListName`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject <- list()
      if (!is.null(self$`fintoolIds`)) {
        EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject[['fintoolIds']] <- self$`fintoolIds`
      }
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject[['date']] <- self$`date`
      }
      if (!is.null(self$`aggType`)) {
        EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject[['aggType']] <- self$`aggType`
      }
      if (!is.null(self$`ratingCodes`)) {
        EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject[['ratingCodes']] <- self$`ratingCodes`
      }
      if (!is.null(self$`ratingListName`)) {
        EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject[['ratingListName']] <- self$`ratingListName`
      }

      EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestJson) {
      EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`fintoolIds`)) {
        self$`fintoolIds` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`fintoolIds`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`date`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`aggType`)) {
        self$`aggType` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`aggType`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`ratingCodes`)) {
        self$`ratingCodes` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`ratingCodes`
      }
      if (!is.null(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`ratingListName`)) {
        self$`ratingListName` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`ratingListName`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fintoolIds": [%s],
           "date": %s,
           "aggType": %s,
           "ratingCodes": [%s],
           "ratingListName": %s
        }',
        lapply(self$`fintoolIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`date`,
        self$`aggType`,
        lapply(self$`ratingCodes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`ratingListName`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestJson) {
      EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestJson)
      self$`fintoolIds` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`fintoolIds`
      self$`date` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`date`
      self$`aggType` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`aggType`
      self$`ratingCodes` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`ratingCodes`
      self$`ratingListName` <- EfirDataHubModelsRequestsV2RatingSecurityRatingByAgenciesRequestObject$`ratingListName`
    }
  )
)
