# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2MarkingCodesRequest Class
#'
#' @field date 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2MarkingCodesRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2MarkingCodesRequest',
  public = list(
    `date` = NULL,
    initialize = function(`date`){
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2MarkingCodesRequestObject <- list()
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2MarkingCodesRequestObject[['date']] <- self$`date`
      }

      EfirDataHubModelsRequestsV2MarkingCodesRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2MarkingCodesRequestJson) {
      EfirDataHubModelsRequestsV2MarkingCodesRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2MarkingCodesRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2MarkingCodesRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2MarkingCodesRequestObject$`date`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "date": %s
        }',
        self$`date`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2MarkingCodesRequestJson) {
      EfirDataHubModelsRequestsV2MarkingCodesRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2MarkingCodesRequestJson)
      self$`date` <- EfirDataHubModelsRequestsV2MarkingCodesRequestObject$`date`
    }
  )
)
