# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRatingAggScale Class
#'
#' @field scale 
#' @field value_l 
#' @field value_n 
#' @field agg_reasons 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRatingAggScale <- R6::R6Class(
  'EfirDataHubModelsModelsRatingAggScale',
  public = list(
    `scale` = NULL,
    `value_l` = NULL,
    `value_n` = NULL,
    `agg_reasons` = NULL,
    initialize = function(`scale`, `value_l`, `value_n`, `agg_reasons`){
      if (!missing(`scale`)) {
        stopifnot(is.character(`scale`), length(`scale`) == 1)
        self$`scale` <- `scale`
      }
      if (!missing(`value_l`)) {
        stopifnot(is.character(`value_l`), length(`value_l`) == 1)
        self$`value_l` <- `value_l`
      }
      if (!missing(`value_n`)) {
        stopifnot(is.numeric(`value_n`), length(`value_n`) == 1)
        self$`value_n` <- `value_n`
      }
      if (!missing(`agg_reasons`)) {
        stopifnot(is.list(`agg_reasons`), length(`agg_reasons`) != 0)
        lapply(`agg_reasons`, function(x) stopifnot(R6::is.R6(x)))
        self$`agg_reasons` <- `agg_reasons`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRatingAggScaleObject <- list()
      if (!is.null(self$`scale`)) {
        EfirDataHubModelsModelsRatingAggScaleObject[['scale']] <- self$`scale`
      }
      if (!is.null(self$`value_l`)) {
        EfirDataHubModelsModelsRatingAggScaleObject[['value_l']] <- self$`value_l`
      }
      if (!is.null(self$`value_n`)) {
        EfirDataHubModelsModelsRatingAggScaleObject[['value_n']] <- self$`value_n`
      }
      if (!is.null(self$`agg_reasons`)) {
        EfirDataHubModelsModelsRatingAggScaleObject[['agg_reasons']] <- lapply(self$`agg_reasons`, function(x) x$toJSON())
      }

      EfirDataHubModelsModelsRatingAggScaleObject
    },
    fromJSON = function(EfirDataHubModelsModelsRatingAggScaleJson) {
      EfirDataHubModelsModelsRatingAggScaleObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingAggScaleJson)
      if (!is.null(EfirDataHubModelsModelsRatingAggScaleObject$`scale`)) {
        self$`scale` <- EfirDataHubModelsModelsRatingAggScaleObject$`scale`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggScaleObject$`value_l`)) {
        self$`value_l` <- EfirDataHubModelsModelsRatingAggScaleObject$`value_l`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggScaleObject$`value_n`)) {
        self$`value_n` <- EfirDataHubModelsModelsRatingAggScaleObject$`value_n`
      }
      if (!is.null(EfirDataHubModelsModelsRatingAggScaleObject$`agg_reasons`)) {
        self$`agg_reasons` <- lapply(EfirDataHubModelsModelsRatingAggScaleObject$`agg_reasons`, function(x) {
          agg_reasonsObject <- EfirDataHubModelsModelsRatingAggReason$new()
          agg_reasonsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          agg_reasonsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "scale": %s,
           "value_l": %s,
           "value_n": %d,
           "agg_reasons": [%s]
        }',
        self$`scale`,
        self$`value_l`,
        self$`value_n`,
        lapply(self$`agg_reasons`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRatingAggScaleJson) {
      EfirDataHubModelsModelsRatingAggScaleObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingAggScaleJson)
      self$`scale` <- EfirDataHubModelsModelsRatingAggScaleObject$`scale`
      self$`value_l` <- EfirDataHubModelsModelsRatingAggScaleObject$`value_l`
      self$`value_n` <- EfirDataHubModelsModelsRatingAggScaleObject$`value_n`
      self$`agg_reasons` <- lapply(EfirDataHubModelsModelsRatingAggScaleObject$`agg_reasons`, function(x) EfirDataHubModelsModelsRatingAggReason$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
