# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2InfoFieldsRequest Class
#'
#' @field filter 
#' @field count 
#' @field parameters 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2InfoFieldsRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2InfoFieldsRequest',
  public = list(
    `filter` = NULL,
    `count` = NULL,
    `parameters` = NULL,
    initialize = function(`filter`, `count`, `parameters`){
      if (!missing(`filter`)) {
        stopifnot(is.character(`filter`), length(`filter`) == 1)
        self$`filter` <- `filter`
      }
      if (!missing(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
        self$`count` <- `count`
      }
      if (!missing(`parameters`)) {
        stopifnot(is.character(`parameters`), length(`parameters`) == 1)
        self$`parameters` <- `parameters`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2InfoFieldsRequestObject <- list()
      if (!is.null(self$`filter`)) {
        EfirDataHubModelsRequestsV2InfoFieldsRequestObject[['filter']] <- self$`filter`
      }
      if (!is.null(self$`count`)) {
        EfirDataHubModelsRequestsV2InfoFieldsRequestObject[['count']] <- self$`count`
      }
      if (!is.null(self$`parameters`)) {
        EfirDataHubModelsRequestsV2InfoFieldsRequestObject[['parameters']] <- self$`parameters`
      }

      EfirDataHubModelsRequestsV2InfoFieldsRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2InfoFieldsRequestJson) {
      EfirDataHubModelsRequestsV2InfoFieldsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2InfoFieldsRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`filter`)) {
        self$`filter` <- EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`filter`
      }
      if (!is.null(EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`count`)) {
        self$`count` <- EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`count`
      }
      if (!is.null(EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`parameters`)) {
        self$`parameters` <- EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`parameters`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "filter": %s,
           "count": %d,
           "parameters": %s
        }',
        self$`filter`,
        self$`count`,
        self$`parameters`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2InfoFieldsRequestJson) {
      EfirDataHubModelsRequestsV2InfoFieldsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2InfoFieldsRequestJson)
      self$`filter` <- EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`filter`
      self$`count` <- EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`count`
      self$`parameters` <- EfirDataHubModelsRequestsV2InfoFieldsRequestObject$`parameters`
    }
  )
)
