# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRiskLiquidityAdjustmentFields Class
#'
#' @field id 
#' @field adj_liq_n 
#' @field adj_liq 
#' @field dt 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRiskLiquidityAdjustmentFields <- R6::R6Class(
  'EfirDataHubModelsModelsRiskLiquidityAdjustmentFields',
  public = list(
    `id` = NULL,
    `adj_liq_n` = NULL,
    `adj_liq` = NULL,
    `dt` = NULL,
    initialize = function(`id`, `adj_liq_n`, `adj_liq`, `dt`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`adj_liq_n`)) {
        stopifnot(is.numeric(`adj_liq_n`), length(`adj_liq_n`) == 1)
        stopifnot(R6::is.R6(`adj_liq_n`))
        self$`adj_liq_n` <- `adj_liq_n`
      }
      if (!missing(`adj_liq`)) {
        stopifnot(is.numeric(`adj_liq`), length(`adj_liq`) == 1)
        stopifnot(R6::is.R6(`adj_liq`))
        self$`adj_liq` <- `adj_liq`
      }
      if (!missing(`dt`)) {
        stopifnot(is.character(`dt`), length(`dt`) == 1)
        self$`dt` <- `dt`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject <- list()
      if (!is.null(self$`id`)) {
        EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject[['id']] <- self$`id`
      }
      if (!is.null(self$`adj_liq_n`)) {
        EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject[['adj_liq_n']] <- self$`adj_liq_n`$toJSON()
      }
      if (!is.null(self$`adj_liq`)) {
        EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject[['adj_liq']] <- self$`adj_liq`$toJSON()
      }
      if (!is.null(self$`dt`)) {
        EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject[['dt']] <- self$`dt`
      }

      EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsJson) {
      EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsJson)
      if (!is.null(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`id`)) {
        self$`id` <- EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`id`
      }
      if (!is.null(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`adj_liq_n`)) {
        adj_liq_nObject <- BigDecimal$new()
        adj_liq_nObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$adj_liq_n, auto_unbox = TRUE))
        self$`adj_liq_n` <- adj_liq_nObject
      }
      if (!is.null(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`adj_liq`)) {
        adj_liqObject <- BigDecimal$new()
        adj_liqObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$adj_liq, auto_unbox = TRUE))
        self$`adj_liq` <- adj_liqObject
      }
      if (!is.null(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`dt`)) {
        self$`dt` <- EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`dt`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "adj_liq_n": %s,
           "adj_liq": %s,
           "dt": %s
        }',
        self$`id`,
        self$`adj_liq_n`$toJSON(),
        self$`adj_liq`$toJSON(),
        self$`dt`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsJson) {
      EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsJson)
      self$`id` <- EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`id`
      BigDecimalObject <- BigDecimal$new()
      self$`adj_liq_n` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$adj_liq_n, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`adj_liq` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$adj_liq, auto_unbox = TRUE))
      self$`dt` <- EfirDataHubModelsModelsRiskLiquidityAdjustmentFieldsObject$`dt`
    }
  )
)
