# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRatingRatingsHistoryFields Class
#'
#' @field name_ra 
#' @field dt 
#' @field last 
#' @field last_dt 
#' @field change 
#' @field forecast 
#' @field advanced 
#' @field prev 
#' @field prev_dt 
#' @field rating_agency 
#' @field rating_code 
#' @field rating_full_name_rus 
#' @field rating_official_name 
#' @field rating_object_type 
#' @field is_credit_rating 
#' @field rating_term 
#' @field scale_type 
#' @field scale_cur 
#' @field short_name_org 
#' @field inn 
#' @field lei 
#' @field sector 
#' @field country 
#' @field role 
#' @field short_name_issue 
#' @field isin 
#' @field reg_code 
#' @field sector_by_rating 
#' @field region 
#' @field is_archive 
#' @field is_accred_br 
#' @field full_name_org 
#' @field press_release 
#' @field is_sf 
#' @field isregion 
#' @field rating_id 
#' @field fininstid 
#' @field fintoolid 
#' @field update_date 
#' @field counter 
#' @field rn 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRatingRatingsHistoryFields <- R6::R6Class(
  'EfirDataHubModelsModelsRatingRatingsHistoryFields',
  public = list(
    `name_ra` = NULL,
    `dt` = NULL,
    `last` = NULL,
    `last_dt` = NULL,
    `change` = NULL,
    `forecast` = NULL,
    `advanced` = NULL,
    `prev` = NULL,
    `prev_dt` = NULL,
    `rating_agency` = NULL,
    `rating_code` = NULL,
    `rating_full_name_rus` = NULL,
    `rating_official_name` = NULL,
    `rating_object_type` = NULL,
    `is_credit_rating` = NULL,
    `rating_term` = NULL,
    `scale_type` = NULL,
    `scale_cur` = NULL,
    `short_name_org` = NULL,
    `inn` = NULL,
    `lei` = NULL,
    `sector` = NULL,
    `country` = NULL,
    `role` = NULL,
    `short_name_issue` = NULL,
    `isin` = NULL,
    `reg_code` = NULL,
    `sector_by_rating` = NULL,
    `region` = NULL,
    `is_archive` = NULL,
    `is_accred_br` = NULL,
    `full_name_org` = NULL,
    `press_release` = NULL,
    `is_sf` = NULL,
    `isregion` = NULL,
    `rating_id` = NULL,
    `fininstid` = NULL,
    `fintoolid` = NULL,
    `update_date` = NULL,
    `counter` = NULL,
    `rn` = NULL,
    initialize = function(`name_ra`, `dt`, `last`, `last_dt`, `change`, `forecast`, `advanced`, `prev`, `prev_dt`, `rating_agency`, `rating_code`, `rating_full_name_rus`, `rating_official_name`, `rating_object_type`, `is_credit_rating`, `rating_term`, `scale_type`, `scale_cur`, `short_name_org`, `inn`, `lei`, `sector`, `country`, `role`, `short_name_issue`, `isin`, `reg_code`, `sector_by_rating`, `region`, `is_archive`, `is_accred_br`, `full_name_org`, `press_release`, `is_sf`, `isregion`, `rating_id`, `fininstid`, `fintoolid`, `update_date`, `counter`, `rn`){
      if (!missing(`name_ra`)) {
        stopifnot(is.character(`name_ra`), length(`name_ra`) == 1)
        self$`name_ra` <- `name_ra`
      }
      if (!missing(`dt`)) {
        stopifnot(is.character(`dt`), length(`dt`) == 1)
        self$`dt` <- `dt`
      }
      if (!missing(`last`)) {
        stopifnot(is.character(`last`), length(`last`) == 1)
        self$`last` <- `last`
      }
      if (!missing(`last_dt`)) {
        stopifnot(is.character(`last_dt`), length(`last_dt`) == 1)
        self$`last_dt` <- `last_dt`
      }
      if (!missing(`change`)) {
        stopifnot(is.character(`change`), length(`change`) == 1)
        self$`change` <- `change`
      }
      if (!missing(`forecast`)) {
        stopifnot(is.character(`forecast`), length(`forecast`) == 1)
        self$`forecast` <- `forecast`
      }
      if (!missing(`advanced`)) {
        stopifnot(is.character(`advanced`), length(`advanced`) == 1)
        self$`advanced` <- `advanced`
      }
      if (!missing(`prev`)) {
        stopifnot(is.character(`prev`), length(`prev`) == 1)
        self$`prev` <- `prev`
      }
      if (!missing(`prev_dt`)) {
        stopifnot(is.character(`prev_dt`), length(`prev_dt`) == 1)
        self$`prev_dt` <- `prev_dt`
      }
      if (!missing(`rating_agency`)) {
        stopifnot(is.character(`rating_agency`), length(`rating_agency`) == 1)
        self$`rating_agency` <- `rating_agency`
      }
      if (!missing(`rating_code`)) {
        stopifnot(is.character(`rating_code`), length(`rating_code`) == 1)
        self$`rating_code` <- `rating_code`
      }
      if (!missing(`rating_full_name_rus`)) {
        stopifnot(is.character(`rating_full_name_rus`), length(`rating_full_name_rus`) == 1)
        self$`rating_full_name_rus` <- `rating_full_name_rus`
      }
      if (!missing(`rating_official_name`)) {
        stopifnot(is.character(`rating_official_name`), length(`rating_official_name`) == 1)
        self$`rating_official_name` <- `rating_official_name`
      }
      if (!missing(`rating_object_type`)) {
        stopifnot(is.character(`rating_object_type`), length(`rating_object_type`) == 1)
        self$`rating_object_type` <- `rating_object_type`
      }
      if (!missing(`is_credit_rating`)) {
        stopifnot(is.numeric(`is_credit_rating`), length(`is_credit_rating`) == 1)
        self$`is_credit_rating` <- `is_credit_rating`
      }
      if (!missing(`rating_term`)) {
        stopifnot(is.character(`rating_term`), length(`rating_term`) == 1)
        self$`rating_term` <- `rating_term`
      }
      if (!missing(`scale_type`)) {
        stopifnot(is.character(`scale_type`), length(`scale_type`) == 1)
        self$`scale_type` <- `scale_type`
      }
      if (!missing(`scale_cur`)) {
        stopifnot(is.character(`scale_cur`), length(`scale_cur`) == 1)
        self$`scale_cur` <- `scale_cur`
      }
      if (!missing(`short_name_org`)) {
        stopifnot(is.character(`short_name_org`), length(`short_name_org`) == 1)
        self$`short_name_org` <- `short_name_org`
      }
      if (!missing(`inn`)) {
        stopifnot(is.character(`inn`), length(`inn`) == 1)
        self$`inn` <- `inn`
      }
      if (!missing(`lei`)) {
        stopifnot(is.character(`lei`), length(`lei`) == 1)
        self$`lei` <- `lei`
      }
      if (!missing(`sector`)) {
        stopifnot(is.character(`sector`), length(`sector`) == 1)
        self$`sector` <- `sector`
      }
      if (!missing(`country`)) {
        stopifnot(is.character(`country`), length(`country`) == 1)
        self$`country` <- `country`
      }
      if (!missing(`role`)) {
        stopifnot(is.character(`role`), length(`role`) == 1)
        self$`role` <- `role`
      }
      if (!missing(`short_name_issue`)) {
        stopifnot(is.character(`short_name_issue`), length(`short_name_issue`) == 1)
        self$`short_name_issue` <- `short_name_issue`
      }
      if (!missing(`isin`)) {
        stopifnot(is.character(`isin`), length(`isin`) == 1)
        self$`isin` <- `isin`
      }
      if (!missing(`reg_code`)) {
        stopifnot(is.character(`reg_code`), length(`reg_code`) == 1)
        self$`reg_code` <- `reg_code`
      }
      if (!missing(`sector_by_rating`)) {
        stopifnot(is.character(`sector_by_rating`), length(`sector_by_rating`) == 1)
        self$`sector_by_rating` <- `sector_by_rating`
      }
      if (!missing(`region`)) {
        stopifnot(is.character(`region`), length(`region`) == 1)
        self$`region` <- `region`
      }
      if (!missing(`is_archive`)) {
        stopifnot(is.numeric(`is_archive`), length(`is_archive`) == 1)
        self$`is_archive` <- `is_archive`
      }
      if (!missing(`is_accred_br`)) {
        stopifnot(is.numeric(`is_accred_br`), length(`is_accred_br`) == 1)
        self$`is_accred_br` <- `is_accred_br`
      }
      if (!missing(`full_name_org`)) {
        stopifnot(is.character(`full_name_org`), length(`full_name_org`) == 1)
        self$`full_name_org` <- `full_name_org`
      }
      if (!missing(`press_release`)) {
        stopifnot(is.character(`press_release`), length(`press_release`) == 1)
        self$`press_release` <- `press_release`
      }
      if (!missing(`is_sf`)) {
        stopifnot(is.numeric(`is_sf`), length(`is_sf`) == 1)
        stopifnot(R6::is.R6(`is_sf`))
        self$`is_sf` <- `is_sf`
      }
      if (!missing(`isregion`)) {
        stopifnot(is.numeric(`isregion`), length(`isregion`) == 1)
        stopifnot(R6::is.R6(`isregion`))
        self$`isregion` <- `isregion`
      }
      if (!missing(`rating_id`)) {
        stopifnot(is.numeric(`rating_id`), length(`rating_id`) == 1)
        self$`rating_id` <- `rating_id`
      }
      if (!missing(`fininstid`)) {
        stopifnot(is.numeric(`fininstid`), length(`fininstid`) == 1)
        self$`fininstid` <- `fininstid`
      }
      if (!missing(`fintoolid`)) {
        stopifnot(is.numeric(`fintoolid`), length(`fintoolid`) == 1)
        self$`fintoolid` <- `fintoolid`
      }
      if (!missing(`update_date`)) {
        stopifnot(is.character(`update_date`), length(`update_date`) == 1)
        self$`update_date` <- `update_date`
      }
      if (!missing(`counter`)) {
        stopifnot(is.numeric(`counter`), length(`counter`) == 1)
        self$`counter` <- `counter`
      }
      if (!missing(`rn`)) {
        stopifnot(is.numeric(`rn`), length(`rn`) == 1)
        self$`rn` <- `rn`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject <- list()
      if (!is.null(self$`name_ra`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['name_ra']] <- self$`name_ra`
      }
      if (!is.null(self$`dt`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['dt']] <- self$`dt`
      }
      if (!is.null(self$`last`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['last']] <- self$`last`
      }
      if (!is.null(self$`last_dt`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['last_dt']] <- self$`last_dt`
      }
      if (!is.null(self$`change`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['change']] <- self$`change`
      }
      if (!is.null(self$`forecast`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['forecast']] <- self$`forecast`
      }
      if (!is.null(self$`advanced`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['advanced']] <- self$`advanced`
      }
      if (!is.null(self$`prev`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['prev']] <- self$`prev`
      }
      if (!is.null(self$`prev_dt`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['prev_dt']] <- self$`prev_dt`
      }
      if (!is.null(self$`rating_agency`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_agency']] <- self$`rating_agency`
      }
      if (!is.null(self$`rating_code`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_code']] <- self$`rating_code`
      }
      if (!is.null(self$`rating_full_name_rus`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_full_name_rus']] <- self$`rating_full_name_rus`
      }
      if (!is.null(self$`rating_official_name`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_official_name']] <- self$`rating_official_name`
      }
      if (!is.null(self$`rating_object_type`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_object_type']] <- self$`rating_object_type`
      }
      if (!is.null(self$`is_credit_rating`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['is_credit_rating']] <- self$`is_credit_rating`
      }
      if (!is.null(self$`rating_term`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_term']] <- self$`rating_term`
      }
      if (!is.null(self$`scale_type`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['scale_type']] <- self$`scale_type`
      }
      if (!is.null(self$`scale_cur`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['scale_cur']] <- self$`scale_cur`
      }
      if (!is.null(self$`short_name_org`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['short_name_org']] <- self$`short_name_org`
      }
      if (!is.null(self$`inn`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['inn']] <- self$`inn`
      }
      if (!is.null(self$`lei`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['lei']] <- self$`lei`
      }
      if (!is.null(self$`sector`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['sector']] <- self$`sector`
      }
      if (!is.null(self$`country`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['country']] <- self$`country`
      }
      if (!is.null(self$`role`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['role']] <- self$`role`
      }
      if (!is.null(self$`short_name_issue`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['short_name_issue']] <- self$`short_name_issue`
      }
      if (!is.null(self$`isin`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['isin']] <- self$`isin`
      }
      if (!is.null(self$`reg_code`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['reg_code']] <- self$`reg_code`
      }
      if (!is.null(self$`sector_by_rating`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['sector_by_rating']] <- self$`sector_by_rating`
      }
      if (!is.null(self$`region`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['region']] <- self$`region`
      }
      if (!is.null(self$`is_archive`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['is_archive']] <- self$`is_archive`
      }
      if (!is.null(self$`is_accred_br`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['is_accred_br']] <- self$`is_accred_br`
      }
      if (!is.null(self$`full_name_org`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['full_name_org']] <- self$`full_name_org`
      }
      if (!is.null(self$`press_release`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['press_release']] <- self$`press_release`
      }
      if (!is.null(self$`is_sf`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['is_sf']] <- self$`is_sf`$toJSON()
      }
      if (!is.null(self$`isregion`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['isregion']] <- self$`isregion`$toJSON()
      }
      if (!is.null(self$`rating_id`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rating_id']] <- self$`rating_id`
      }
      if (!is.null(self$`fininstid`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['fininstid']] <- self$`fininstid`
      }
      if (!is.null(self$`fintoolid`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['fintoolid']] <- self$`fintoolid`
      }
      if (!is.null(self$`update_date`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['update_date']] <- self$`update_date`
      }
      if (!is.null(self$`counter`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['counter']] <- self$`counter`
      }
      if (!is.null(self$`rn`)) {
        EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject[['rn']] <- self$`rn`
      }

      EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsRatingRatingsHistoryFieldsJson) {
      EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingRatingsHistoryFieldsJson)
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`name_ra`)) {
        self$`name_ra` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`name_ra`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`dt`)) {
        self$`dt` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`dt`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`last`)) {
        self$`last` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`last`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`last_dt`)) {
        self$`last_dt` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`last_dt`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`change`)) {
        self$`change` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`change`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`forecast`)) {
        self$`forecast` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`forecast`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`advanced`)) {
        self$`advanced` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`advanced`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`prev`)) {
        self$`prev` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`prev`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`prev_dt`)) {
        self$`prev_dt` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`prev_dt`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_agency`)) {
        self$`rating_agency` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_agency`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_code`)) {
        self$`rating_code` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_code`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_full_name_rus`)) {
        self$`rating_full_name_rus` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_full_name_rus`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_official_name`)) {
        self$`rating_official_name` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_official_name`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_object_type`)) {
        self$`rating_object_type` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_object_type`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_credit_rating`)) {
        self$`is_credit_rating` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_credit_rating`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_term`)) {
        self$`rating_term` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_term`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`scale_type`)) {
        self$`scale_type` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`scale_type`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`scale_cur`)) {
        self$`scale_cur` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`scale_cur`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`short_name_org`)) {
        self$`short_name_org` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`short_name_org`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`inn`)) {
        self$`inn` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`inn`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`lei`)) {
        self$`lei` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`lei`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`sector`)) {
        self$`sector` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`sector`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`country`)) {
        self$`country` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`country`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`role`)) {
        self$`role` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`role`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`short_name_issue`)) {
        self$`short_name_issue` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`short_name_issue`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`isin`)) {
        self$`isin` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`isin`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`reg_code`)) {
        self$`reg_code` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`reg_code`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`sector_by_rating`)) {
        self$`sector_by_rating` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`sector_by_rating`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`region`)) {
        self$`region` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`region`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_archive`)) {
        self$`is_archive` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_archive`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_accred_br`)) {
        self$`is_accred_br` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_accred_br`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`full_name_org`)) {
        self$`full_name_org` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`full_name_org`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`press_release`)) {
        self$`press_release` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`press_release`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_sf`)) {
        is_sfObject <- BigDecimal$new()
        is_sfObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$is_sf, auto_unbox = TRUE))
        self$`is_sf` <- is_sfObject
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`isregion`)) {
        isregionObject <- BigDecimal$new()
        isregionObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$isregion, auto_unbox = TRUE))
        self$`isregion` <- isregionObject
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_id`)) {
        self$`rating_id` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_id`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`fininstid`)) {
        self$`fininstid` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`fininstid`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`fintoolid`)) {
        self$`fintoolid` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`fintoolid`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`update_date`)) {
        self$`update_date` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`update_date`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`counter`)) {
        self$`counter` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`counter`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rn`)) {
        self$`rn` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rn`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name_ra": %s,
           "dt": %s,
           "last": %s,
           "last_dt": %s,
           "change": %s,
           "forecast": %s,
           "advanced": %s,
           "prev": %s,
           "prev_dt": %s,
           "rating_agency": %s,
           "rating_code": %s,
           "rating_full_name_rus": %s,
           "rating_official_name": %s,
           "rating_object_type": %s,
           "is_credit_rating": %d,
           "rating_term": %s,
           "scale_type": %s,
           "scale_cur": %s,
           "short_name_org": %s,
           "inn": %s,
           "lei": %s,
           "sector": %s,
           "country": %s,
           "role": %s,
           "short_name_issue": %s,
           "isin": %s,
           "reg_code": %s,
           "sector_by_rating": %s,
           "region": %s,
           "is_archive": %d,
           "is_accred_br": %d,
           "full_name_org": %s,
           "press_release": %s,
           "is_sf": %s,
           "isregion": %s,
           "rating_id": %d,
           "fininstid": %d,
           "fintoolid": %d,
           "update_date": %s,
           "counter": %d,
           "rn": %d
        }',
        self$`name_ra`,
        self$`dt`,
        self$`last`,
        self$`last_dt`,
        self$`change`,
        self$`forecast`,
        self$`advanced`,
        self$`prev`,
        self$`prev_dt`,
        self$`rating_agency`,
        self$`rating_code`,
        self$`rating_full_name_rus`,
        self$`rating_official_name`,
        self$`rating_object_type`,
        self$`is_credit_rating`,
        self$`rating_term`,
        self$`scale_type`,
        self$`scale_cur`,
        self$`short_name_org`,
        self$`inn`,
        self$`lei`,
        self$`sector`,
        self$`country`,
        self$`role`,
        self$`short_name_issue`,
        self$`isin`,
        self$`reg_code`,
        self$`sector_by_rating`,
        self$`region`,
        self$`is_archive`,
        self$`is_accred_br`,
        self$`full_name_org`,
        self$`press_release`,
        self$`is_sf`$toJSON(),
        self$`isregion`$toJSON(),
        self$`rating_id`,
        self$`fininstid`,
        self$`fintoolid`,
        self$`update_date`,
        self$`counter`,
        self$`rn`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRatingRatingsHistoryFieldsJson) {
      EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingRatingsHistoryFieldsJson)
      self$`name_ra` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`name_ra`
      self$`dt` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`dt`
      self$`last` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`last`
      self$`last_dt` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`last_dt`
      self$`change` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`change`
      self$`forecast` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`forecast`
      self$`advanced` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`advanced`
      self$`prev` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`prev`
      self$`prev_dt` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`prev_dt`
      self$`rating_agency` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_agency`
      self$`rating_code` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_code`
      self$`rating_full_name_rus` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_full_name_rus`
      self$`rating_official_name` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_official_name`
      self$`rating_object_type` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_object_type`
      self$`is_credit_rating` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_credit_rating`
      self$`rating_term` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_term`
      self$`scale_type` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`scale_type`
      self$`scale_cur` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`scale_cur`
      self$`short_name_org` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`short_name_org`
      self$`inn` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`inn`
      self$`lei` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`lei`
      self$`sector` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`sector`
      self$`country` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`country`
      self$`role` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`role`
      self$`short_name_issue` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`short_name_issue`
      self$`isin` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`isin`
      self$`reg_code` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`reg_code`
      self$`sector_by_rating` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`sector_by_rating`
      self$`region` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`region`
      self$`is_archive` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_archive`
      self$`is_accred_br` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`is_accred_br`
      self$`full_name_org` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`full_name_org`
      self$`press_release` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`press_release`
      BigDecimalObject <- BigDecimal$new()
      self$`is_sf` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$is_sf, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`isregion` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$isregion, auto_unbox = TRUE))
      self$`rating_id` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rating_id`
      self$`fininstid` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`fininstid`
      self$`fintoolid` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`fintoolid`
      self$`update_date` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`update_date`
      self$`counter` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`counter`
      self$`rn` <- EfirDataHubModelsModelsRatingRatingsHistoryFieldsObject$`rn`
    }
  )
)
