# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsIndicatorRiskFreeFields Class
#'
#' @field term 
#' @field rate 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsIndicatorRiskFreeFields <- R6::R6Class(
  'EfirDataHubModelsModelsIndicatorRiskFreeFields',
  public = list(
    `term` = NULL,
    `rate` = NULL,
    initialize = function(`term`, `rate`){
      if (!missing(`term`)) {
        stopifnot(is.numeric(`term`), length(`term`) == 1)
        self$`term` <- `term`
      }
      if (!missing(`rate`)) {
        stopifnot(is.numeric(`rate`), length(`rate`) == 1)
        self$`rate` <- `rate`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject <- list()
      if (!is.null(self$`term`)) {
        EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject[['term']] <- self$`term`
      }
      if (!is.null(self$`rate`)) {
        EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject[['rate']] <- self$`rate`
      }

      EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsIndicatorRiskFreeFieldsJson) {
      EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsIndicatorRiskFreeFieldsJson)
      if (!is.null(EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject$`term`)) {
        self$`term` <- EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject$`term`
      }
      if (!is.null(EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject$`rate`)) {
        self$`rate` <- EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject$`rate`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "term": %d,
           "rate": %d
        }',
        self$`term`,
        self$`rate`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsIndicatorRiskFreeFieldsJson) {
      EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsIndicatorRiskFreeFieldsJson)
      self$`term` <- EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject$`term`
      self$`rate` <- EfirDataHubModelsModelsIndicatorRiskFreeFieldsObject$`rate`
    }
  )
)
