# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2BondCalculateBondPeriods Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2BondCalculateBondPeriods <- R6::R6Class(
  'EfirDataHubModelsRequestsV2BondCalculateBondPeriods',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2BondCalculateBondPeriodsObject <- list()

      EfirDataHubModelsRequestsV2BondCalculateBondPeriodsObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2BondCalculateBondPeriodsJson) {
      EfirDataHubModelsRequestsV2BondCalculateBondPeriodsObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondCalculateBondPeriodsJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2BondCalculateBondPeriodsJson) {
      EfirDataHubModelsRequestsV2BondCalculateBondPeriodsObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondCalculateBondPeriodsJson)
    }
  )
)
