# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsSppiCovenantFields Class
#'
#' @field id 
#' @field name 
#' @field optionNum 
#' @field classificationResult 
#' @field note 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsSppiCovenantFields <- R6::R6Class(
  'EfirDataHubModelsModelsSppiCovenantFields',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `optionNum` = NULL,
    `classificationResult` = NULL,
    `note` = NULL,
    initialize = function(`id`, `name`, `optionNum`, `classificationResult`, `note`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`optionNum`)) {
        stopifnot(is.numeric(`optionNum`), length(`optionNum`) == 1)
        self$`optionNum` <- `optionNum`
      }
      if (!missing(`classificationResult`)) {
        stopifnot(is.character(`classificationResult`), length(`classificationResult`) == 1)
        self$`classificationResult` <- `classificationResult`
      }
      if (!missing(`note`)) {
        stopifnot(is.character(`note`), length(`note`) == 1)
        self$`note` <- `note`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsSppiCovenantFieldsObject <- list()
      if (!is.null(self$`id`)) {
        EfirDataHubModelsModelsSppiCovenantFieldsObject[['id']] <- self$`id`
      }
      if (!is.null(self$`name`)) {
        EfirDataHubModelsModelsSppiCovenantFieldsObject[['name']] <- self$`name`
      }
      if (!is.null(self$`optionNum`)) {
        EfirDataHubModelsModelsSppiCovenantFieldsObject[['optionNum']] <- self$`optionNum`
      }
      if (!is.null(self$`classificationResult`)) {
        EfirDataHubModelsModelsSppiCovenantFieldsObject[['classificationResult']] <- self$`classificationResult`
      }
      if (!is.null(self$`note`)) {
        EfirDataHubModelsModelsSppiCovenantFieldsObject[['note']] <- self$`note`
      }

      EfirDataHubModelsModelsSppiCovenantFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsSppiCovenantFieldsJson) {
      EfirDataHubModelsModelsSppiCovenantFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsSppiCovenantFieldsJson)
      if (!is.null(EfirDataHubModelsModelsSppiCovenantFieldsObject$`id`)) {
        self$`id` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`id`
      }
      if (!is.null(EfirDataHubModelsModelsSppiCovenantFieldsObject$`name`)) {
        self$`name` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`name`
      }
      if (!is.null(EfirDataHubModelsModelsSppiCovenantFieldsObject$`optionNum`)) {
        self$`optionNum` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`optionNum`
      }
      if (!is.null(EfirDataHubModelsModelsSppiCovenantFieldsObject$`classificationResult`)) {
        self$`classificationResult` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`classificationResult`
      }
      if (!is.null(EfirDataHubModelsModelsSppiCovenantFieldsObject$`note`)) {
        self$`note` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`note`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "name": %s,
           "optionNum": %d,
           "classificationResult": %s,
           "note": %s
        }',
        self$`id`,
        self$`name`,
        self$`optionNum`,
        self$`classificationResult`,
        self$`note`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsSppiCovenantFieldsJson) {
      EfirDataHubModelsModelsSppiCovenantFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsSppiCovenantFieldsJson)
      self$`id` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`id`
      self$`name` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`name`
      self$`optionNum` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`optionNum`
      self$`classificationResult` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`classificationResult`
      self$`note` <- EfirDataHubModelsModelsSppiCovenantFieldsObject$`note`
    }
  )
)
