# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsScoringCompanyPDFields Class
#'
#' @field pd 
#' @field company_shortname 
#' @field company_sparkid 
#' @field company_inn 
#' @field company_ogrn 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsScoringCompanyPDFields <- R6::R6Class(
  'EfirDataHubModelsModelsScoringCompanyPDFields',
  public = list(
    `pd` = NULL,
    `company_shortname` = NULL,
    `company_sparkid` = NULL,
    `company_inn` = NULL,
    `company_ogrn` = NULL,
    initialize = function(`pd`, `company_shortname`, `company_sparkid`, `company_inn`, `company_ogrn`){
      if (!missing(`pd`)) {
        stopifnot(is.numeric(`pd`), length(`pd`) == 1)
        self$`pd` <- `pd`
      }
      if (!missing(`company_shortname`)) {
        stopifnot(is.character(`company_shortname`), length(`company_shortname`) == 1)
        self$`company_shortname` <- `company_shortname`
      }
      if (!missing(`company_sparkid`)) {
        stopifnot(is.numeric(`company_sparkid`), length(`company_sparkid`) == 1)
        self$`company_sparkid` <- `company_sparkid`
      }
      if (!missing(`company_inn`)) {
        stopifnot(is.character(`company_inn`), length(`company_inn`) == 1)
        self$`company_inn` <- `company_inn`
      }
      if (!missing(`company_ogrn`)) {
        stopifnot(is.character(`company_ogrn`), length(`company_ogrn`) == 1)
        self$`company_ogrn` <- `company_ogrn`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsScoringCompanyPDFieldsObject <- list()
      if (!is.null(self$`pd`)) {
        EfirDataHubModelsModelsScoringCompanyPDFieldsObject[['pd']] <- self$`pd`
      }
      if (!is.null(self$`company_shortname`)) {
        EfirDataHubModelsModelsScoringCompanyPDFieldsObject[['company_shortname']] <- self$`company_shortname`
      }
      if (!is.null(self$`company_sparkid`)) {
        EfirDataHubModelsModelsScoringCompanyPDFieldsObject[['company_sparkid']] <- self$`company_sparkid`
      }
      if (!is.null(self$`company_inn`)) {
        EfirDataHubModelsModelsScoringCompanyPDFieldsObject[['company_inn']] <- self$`company_inn`
      }
      if (!is.null(self$`company_ogrn`)) {
        EfirDataHubModelsModelsScoringCompanyPDFieldsObject[['company_ogrn']] <- self$`company_ogrn`
      }

      EfirDataHubModelsModelsScoringCompanyPDFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsScoringCompanyPDFieldsJson) {
      EfirDataHubModelsModelsScoringCompanyPDFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsScoringCompanyPDFieldsJson)
      if (!is.null(EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`pd`)) {
        self$`pd` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`pd`
      }
      if (!is.null(EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_shortname`)) {
        self$`company_shortname` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_shortname`
      }
      if (!is.null(EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_sparkid`)) {
        self$`company_sparkid` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_sparkid`
      }
      if (!is.null(EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_inn`)) {
        self$`company_inn` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_inn`
      }
      if (!is.null(EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_ogrn`)) {
        self$`company_ogrn` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_ogrn`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "pd": %d,
           "company_shortname": %s,
           "company_sparkid": %d,
           "company_inn": %s,
           "company_ogrn": %s
        }',
        self$`pd`,
        self$`company_shortname`,
        self$`company_sparkid`,
        self$`company_inn`,
        self$`company_ogrn`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsScoringCompanyPDFieldsJson) {
      EfirDataHubModelsModelsScoringCompanyPDFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsScoringCompanyPDFieldsJson)
      self$`pd` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`pd`
      self$`company_shortname` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_shortname`
      self$`company_sparkid` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_sparkid`
      self$`company_inn` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_inn`
      self$`company_ogrn` <- EfirDataHubModelsModelsScoringCompanyPDFieldsObject$`company_ogrn`
    }
  )
)
