# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsSolvencyCounterpartyFields Class
#'
#' @field source_id 
#' @field source_type 
#' @field counterpartyid 
#' @field inn 
#' @field ogrn 
#' @field tin 
#' @field lei_code 
#' @field fininstid 
#' @field okpo 
#' @field sparkid 
#' @field br_txnmid 
#' @field br_regno 
#' @field reg_code 
#' @field shortname_rus 
#' @field fullname_rus 
#' @field shortname_eng 
#' @field legal_address 
#' @field country 
#' @field country_reg 
#' @field oecd_lvl 
#' @field is_riskfree 
#' @field okved 
#' @field kpp 
#' @field is_finorg 
#' @field is_govorg 
#' @field licinfo_type 
#' @field licinfo_no 
#' @field activ_id 
#' @field is_lloyd 
#' @field is_systinfr 
#' @field is_default 
#' @field capital 
#' @field capital_unit 
#' @field post_address 
#' @field e_mail 
#' @field is_gov_or_cb 
#' @field on_behalf_of_state 
#' @field is_subject_rf 
#' @field is_branch 
#' @field is_liquidated 
#' @field is_govorg_ext 
#' @field counter 
#' @field rn 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsSolvencyCounterpartyFields <- R6::R6Class(
  'EfirDataHubModelsModelsSolvencyCounterpartyFields',
  public = list(
    `source_id` = NULL,
    `source_type` = NULL,
    `counterpartyid` = NULL,
    `inn` = NULL,
    `ogrn` = NULL,
    `tin` = NULL,
    `lei_code` = NULL,
    `fininstid` = NULL,
    `okpo` = NULL,
    `sparkid` = NULL,
    `br_txnmid` = NULL,
    `br_regno` = NULL,
    `reg_code` = NULL,
    `shortname_rus` = NULL,
    `fullname_rus` = NULL,
    `shortname_eng` = NULL,
    `legal_address` = NULL,
    `country` = NULL,
    `country_reg` = NULL,
    `oecd_lvl` = NULL,
    `is_riskfree` = NULL,
    `okved` = NULL,
    `kpp` = NULL,
    `is_finorg` = NULL,
    `is_govorg` = NULL,
    `licinfo_type` = NULL,
    `licinfo_no` = NULL,
    `activ_id` = NULL,
    `is_lloyd` = NULL,
    `is_systinfr` = NULL,
    `is_default` = NULL,
    `capital` = NULL,
    `capital_unit` = NULL,
    `post_address` = NULL,
    `e_mail` = NULL,
    `is_gov_or_cb` = NULL,
    `on_behalf_of_state` = NULL,
    `is_subject_rf` = NULL,
    `is_branch` = NULL,
    `is_liquidated` = NULL,
    `is_govorg_ext` = NULL,
    `counter` = NULL,
    `rn` = NULL,
    initialize = function(`source_id`, `source_type`, `counterpartyid`, `inn`, `ogrn`, `tin`, `lei_code`, `fininstid`, `okpo`, `sparkid`, `br_txnmid`, `br_regno`, `reg_code`, `shortname_rus`, `fullname_rus`, `shortname_eng`, `legal_address`, `country`, `country_reg`, `oecd_lvl`, `is_riskfree`, `okved`, `kpp`, `is_finorg`, `is_govorg`, `licinfo_type`, `licinfo_no`, `activ_id`, `is_lloyd`, `is_systinfr`, `is_default`, `capital`, `capital_unit`, `post_address`, `e_mail`, `is_gov_or_cb`, `on_behalf_of_state`, `is_subject_rf`, `is_branch`, `is_liquidated`, `is_govorg_ext`, `counter`, `rn`){
      if (!missing(`source_id`)) {
        stopifnot(is.character(`source_id`), length(`source_id`) == 1)
        self$`source_id` <- `source_id`
      }
      if (!missing(`source_type`)) {
        stopifnot(is.character(`source_type`), length(`source_type`) == 1)
        self$`source_type` <- `source_type`
      }
      if (!missing(`counterpartyid`)) {
        stopifnot(is.numeric(`counterpartyid`), length(`counterpartyid`) == 1)
        self$`counterpartyid` <- `counterpartyid`
      }
      if (!missing(`inn`)) {
        stopifnot(is.character(`inn`), length(`inn`) == 1)
        self$`inn` <- `inn`
      }
      if (!missing(`ogrn`)) {
        stopifnot(is.character(`ogrn`), length(`ogrn`) == 1)
        self$`ogrn` <- `ogrn`
      }
      if (!missing(`tin`)) {
        stopifnot(is.character(`tin`), length(`tin`) == 1)
        self$`tin` <- `tin`
      }
      if (!missing(`lei_code`)) {
        stopifnot(is.character(`lei_code`), length(`lei_code`) == 1)
        self$`lei_code` <- `lei_code`
      }
      if (!missing(`fininstid`)) {
        stopifnot(is.numeric(`fininstid`), length(`fininstid`) == 1)
        self$`fininstid` <- `fininstid`
      }
      if (!missing(`okpo`)) {
        stopifnot(is.character(`okpo`), length(`okpo`) == 1)
        self$`okpo` <- `okpo`
      }
      if (!missing(`sparkid`)) {
        stopifnot(is.numeric(`sparkid`), length(`sparkid`) == 1)
        self$`sparkid` <- `sparkid`
      }
      if (!missing(`br_txnmid`)) {
        stopifnot(is.character(`br_txnmid`), length(`br_txnmid`) == 1)
        self$`br_txnmid` <- `br_txnmid`
      }
      if (!missing(`br_regno`)) {
        stopifnot(is.character(`br_regno`), length(`br_regno`) == 1)
        self$`br_regno` <- `br_regno`
      }
      if (!missing(`reg_code`)) {
        stopifnot(is.character(`reg_code`), length(`reg_code`) == 1)
        self$`reg_code` <- `reg_code`
      }
      if (!missing(`shortname_rus`)) {
        stopifnot(is.character(`shortname_rus`), length(`shortname_rus`) == 1)
        self$`shortname_rus` <- `shortname_rus`
      }
      if (!missing(`fullname_rus`)) {
        stopifnot(is.character(`fullname_rus`), length(`fullname_rus`) == 1)
        self$`fullname_rus` <- `fullname_rus`
      }
      if (!missing(`shortname_eng`)) {
        stopifnot(is.character(`shortname_eng`), length(`shortname_eng`) == 1)
        self$`shortname_eng` <- `shortname_eng`
      }
      if (!missing(`legal_address`)) {
        stopifnot(is.character(`legal_address`), length(`legal_address`) == 1)
        self$`legal_address` <- `legal_address`
      }
      if (!missing(`country`)) {
        stopifnot(is.character(`country`), length(`country`) == 1)
        self$`country` <- `country`
      }
      if (!missing(`country_reg`)) {
        stopifnot(is.character(`country_reg`), length(`country_reg`) == 1)
        self$`country_reg` <- `country_reg`
      }
      if (!missing(`oecd_lvl`)) {
        stopifnot(is.character(`oecd_lvl`), length(`oecd_lvl`) == 1)
        self$`oecd_lvl` <- `oecd_lvl`
      }
      if (!missing(`is_riskfree`)) {
        self$`is_riskfree` <- `is_riskfree`
      }
      if (!missing(`okved`)) {
        stopifnot(is.character(`okved`), length(`okved`) == 1)
        self$`okved` <- `okved`
      }
      if (!missing(`kpp`)) {
        stopifnot(is.character(`kpp`), length(`kpp`) == 1)
        self$`kpp` <- `kpp`
      }
      if (!missing(`is_finorg`)) {
        self$`is_finorg` <- `is_finorg`
      }
      if (!missing(`is_govorg`)) {
        self$`is_govorg` <- `is_govorg`
      }
      if (!missing(`licinfo_type`)) {
        stopifnot(is.character(`licinfo_type`), length(`licinfo_type`) == 1)
        self$`licinfo_type` <- `licinfo_type`
      }
      if (!missing(`licinfo_no`)) {
        stopifnot(is.character(`licinfo_no`), length(`licinfo_no`) == 1)
        self$`licinfo_no` <- `licinfo_no`
      }
      if (!missing(`activ_id`)) {
        stopifnot(is.character(`activ_id`), length(`activ_id`) == 1)
        self$`activ_id` <- `activ_id`
      }
      if (!missing(`is_lloyd`)) {
        self$`is_lloyd` <- `is_lloyd`
      }
      if (!missing(`is_systinfr`)) {
        self$`is_systinfr` <- `is_systinfr`
      }
      if (!missing(`is_default`)) {
        self$`is_default` <- `is_default`
      }
      if (!missing(`capital`)) {
        stopifnot(is.numeric(`capital`), length(`capital`) == 1)
        self$`capital` <- `capital`
      }
      if (!missing(`capital_unit`)) {
        stopifnot(is.character(`capital_unit`), length(`capital_unit`) == 1)
        self$`capital_unit` <- `capital_unit`
      }
      if (!missing(`post_address`)) {
        stopifnot(is.character(`post_address`), length(`post_address`) == 1)
        self$`post_address` <- `post_address`
      }
      if (!missing(`e_mail`)) {
        stopifnot(is.character(`e_mail`), length(`e_mail`) == 1)
        self$`e_mail` <- `e_mail`
      }
      if (!missing(`is_gov_or_cb`)) {
        self$`is_gov_or_cb` <- `is_gov_or_cb`
      }
      if (!missing(`on_behalf_of_state`)) {
        self$`on_behalf_of_state` <- `on_behalf_of_state`
      }
      if (!missing(`is_subject_rf`)) {
        self$`is_subject_rf` <- `is_subject_rf`
      }
      if (!missing(`is_branch`)) {
        self$`is_branch` <- `is_branch`
      }
      if (!missing(`is_liquidated`)) {
        self$`is_liquidated` <- `is_liquidated`
      }
      if (!missing(`is_govorg_ext`)) {
        self$`is_govorg_ext` <- `is_govorg_ext`
      }
      if (!missing(`counter`)) {
        stopifnot(is.numeric(`counter`), length(`counter`) == 1)
        self$`counter` <- `counter`
      }
      if (!missing(`rn`)) {
        stopifnot(is.numeric(`rn`), length(`rn`) == 1)
        self$`rn` <- `rn`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject <- list()
      if (!is.null(self$`source_id`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['source_id']] <- self$`source_id`
      }
      if (!is.null(self$`source_type`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['source_type']] <- self$`source_type`
      }
      if (!is.null(self$`counterpartyid`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['counterpartyid']] <- self$`counterpartyid`
      }
      if (!is.null(self$`inn`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['inn']] <- self$`inn`
      }
      if (!is.null(self$`ogrn`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['ogrn']] <- self$`ogrn`
      }
      if (!is.null(self$`tin`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['tin']] <- self$`tin`
      }
      if (!is.null(self$`lei_code`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['lei_code']] <- self$`lei_code`
      }
      if (!is.null(self$`fininstid`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['fininstid']] <- self$`fininstid`
      }
      if (!is.null(self$`okpo`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['okpo']] <- self$`okpo`
      }
      if (!is.null(self$`sparkid`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['sparkid']] <- self$`sparkid`
      }
      if (!is.null(self$`br_txnmid`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['br_txnmid']] <- self$`br_txnmid`
      }
      if (!is.null(self$`br_regno`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['br_regno']] <- self$`br_regno`
      }
      if (!is.null(self$`reg_code`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['reg_code']] <- self$`reg_code`
      }
      if (!is.null(self$`shortname_rus`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['shortname_rus']] <- self$`shortname_rus`
      }
      if (!is.null(self$`fullname_rus`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['fullname_rus']] <- self$`fullname_rus`
      }
      if (!is.null(self$`shortname_eng`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['shortname_eng']] <- self$`shortname_eng`
      }
      if (!is.null(self$`legal_address`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['legal_address']] <- self$`legal_address`
      }
      if (!is.null(self$`country`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['country']] <- self$`country`
      }
      if (!is.null(self$`country_reg`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['country_reg']] <- self$`country_reg`
      }
      if (!is.null(self$`oecd_lvl`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['oecd_lvl']] <- self$`oecd_lvl`
      }
      if (!is.null(self$`is_riskfree`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_riskfree']] <- self$`is_riskfree`
      }
      if (!is.null(self$`okved`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['okved']] <- self$`okved`
      }
      if (!is.null(self$`kpp`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['kpp']] <- self$`kpp`
      }
      if (!is.null(self$`is_finorg`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_finorg']] <- self$`is_finorg`
      }
      if (!is.null(self$`is_govorg`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_govorg']] <- self$`is_govorg`
      }
      if (!is.null(self$`licinfo_type`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['licinfo_type']] <- self$`licinfo_type`
      }
      if (!is.null(self$`licinfo_no`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['licinfo_no']] <- self$`licinfo_no`
      }
      if (!is.null(self$`activ_id`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['activ_id']] <- self$`activ_id`
      }
      if (!is.null(self$`is_lloyd`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_lloyd']] <- self$`is_lloyd`
      }
      if (!is.null(self$`is_systinfr`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_systinfr']] <- self$`is_systinfr`
      }
      if (!is.null(self$`is_default`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_default']] <- self$`is_default`
      }
      if (!is.null(self$`capital`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['capital']] <- self$`capital`
      }
      if (!is.null(self$`capital_unit`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['capital_unit']] <- self$`capital_unit`
      }
      if (!is.null(self$`post_address`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['post_address']] <- self$`post_address`
      }
      if (!is.null(self$`e_mail`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['e_mail']] <- self$`e_mail`
      }
      if (!is.null(self$`is_gov_or_cb`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_gov_or_cb']] <- self$`is_gov_or_cb`
      }
      if (!is.null(self$`on_behalf_of_state`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['on_behalf_of_state']] <- self$`on_behalf_of_state`
      }
      if (!is.null(self$`is_subject_rf`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_subject_rf']] <- self$`is_subject_rf`
      }
      if (!is.null(self$`is_branch`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_branch']] <- self$`is_branch`
      }
      if (!is.null(self$`is_liquidated`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_liquidated']] <- self$`is_liquidated`
      }
      if (!is.null(self$`is_govorg_ext`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['is_govorg_ext']] <- self$`is_govorg_ext`
      }
      if (!is.null(self$`counter`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['counter']] <- self$`counter`
      }
      if (!is.null(self$`rn`)) {
        EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject[['rn']] <- self$`rn`
      }

      EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsSolvencyCounterpartyFieldsJson) {
      EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsSolvencyCounterpartyFieldsJson)
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`source_id`)) {
        self$`source_id` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`source_id`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`source_type`)) {
        self$`source_type` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`source_type`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`counterpartyid`)) {
        self$`counterpartyid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`counterpartyid`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`inn`)) {
        self$`inn` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`inn`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`ogrn`)) {
        self$`ogrn` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`ogrn`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`tin`)) {
        self$`tin` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`tin`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`lei_code`)) {
        self$`lei_code` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`lei_code`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`fininstid`)) {
        self$`fininstid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`fininstid`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`okpo`)) {
        self$`okpo` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`okpo`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`sparkid`)) {
        self$`sparkid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`sparkid`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`br_txnmid`)) {
        self$`br_txnmid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`br_txnmid`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`br_regno`)) {
        self$`br_regno` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`br_regno`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`reg_code`)) {
        self$`reg_code` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`reg_code`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`shortname_rus`)) {
        self$`shortname_rus` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`shortname_rus`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`fullname_rus`)) {
        self$`fullname_rus` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`fullname_rus`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`shortname_eng`)) {
        self$`shortname_eng` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`shortname_eng`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`legal_address`)) {
        self$`legal_address` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`legal_address`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`country`)) {
        self$`country` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`country`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`country_reg`)) {
        self$`country_reg` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`country_reg`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`oecd_lvl`)) {
        self$`oecd_lvl` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`oecd_lvl`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_riskfree`)) {
        self$`is_riskfree` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_riskfree`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`okved`)) {
        self$`okved` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`okved`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`kpp`)) {
        self$`kpp` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`kpp`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_finorg`)) {
        self$`is_finorg` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_finorg`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_govorg`)) {
        self$`is_govorg` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_govorg`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`licinfo_type`)) {
        self$`licinfo_type` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`licinfo_type`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`licinfo_no`)) {
        self$`licinfo_no` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`licinfo_no`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`activ_id`)) {
        self$`activ_id` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`activ_id`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_lloyd`)) {
        self$`is_lloyd` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_lloyd`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_systinfr`)) {
        self$`is_systinfr` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_systinfr`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_default`)) {
        self$`is_default` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_default`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`capital`)) {
        self$`capital` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`capital`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`capital_unit`)) {
        self$`capital_unit` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`capital_unit`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`post_address`)) {
        self$`post_address` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`post_address`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`e_mail`)) {
        self$`e_mail` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`e_mail`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_gov_or_cb`)) {
        self$`is_gov_or_cb` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_gov_or_cb`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`on_behalf_of_state`)) {
        self$`on_behalf_of_state` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`on_behalf_of_state`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_subject_rf`)) {
        self$`is_subject_rf` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_subject_rf`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_branch`)) {
        self$`is_branch` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_branch`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_liquidated`)) {
        self$`is_liquidated` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_liquidated`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_govorg_ext`)) {
        self$`is_govorg_ext` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_govorg_ext`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`counter`)) {
        self$`counter` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`counter`
      }
      if (!is.null(EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`rn`)) {
        self$`rn` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`rn`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "source_id": %s,
           "source_type": %s,
           "counterpartyid": %d,
           "inn": %s,
           "ogrn": %s,
           "tin": %s,
           "lei_code": %s,
           "fininstid": %d,
           "okpo": %s,
           "sparkid": %d,
           "br_txnmid": %s,
           "br_regno": %s,
           "reg_code": %s,
           "shortname_rus": %s,
           "fullname_rus": %s,
           "shortname_eng": %s,
           "legal_address": %s,
           "country": %s,
           "country_reg": %s,
           "oecd_lvl": %s,
           "is_riskfree": %s,
           "okved": %s,
           "kpp": %s,
           "is_finorg": %s,
           "is_govorg": %s,
           "licinfo_type": %s,
           "licinfo_no": %s,
           "activ_id": %s,
           "is_lloyd": %s,
           "is_systinfr": %s,
           "is_default": %s,
           "capital": %d,
           "capital_unit": %s,
           "post_address": %s,
           "e_mail": %s,
           "is_gov_or_cb": %s,
           "on_behalf_of_state": %s,
           "is_subject_rf": %s,
           "is_branch": %s,
           "is_liquidated": %s,
           "is_govorg_ext": %s,
           "counter": %d,
           "rn": %d
        }',
        self$`source_id`,
        self$`source_type`,
        self$`counterpartyid`,
        self$`inn`,
        self$`ogrn`,
        self$`tin`,
        self$`lei_code`,
        self$`fininstid`,
        self$`okpo`,
        self$`sparkid`,
        self$`br_txnmid`,
        self$`br_regno`,
        self$`reg_code`,
        self$`shortname_rus`,
        self$`fullname_rus`,
        self$`shortname_eng`,
        self$`legal_address`,
        self$`country`,
        self$`country_reg`,
        self$`oecd_lvl`,
        self$`is_riskfree`,
        self$`okved`,
        self$`kpp`,
        self$`is_finorg`,
        self$`is_govorg`,
        self$`licinfo_type`,
        self$`licinfo_no`,
        self$`activ_id`,
        self$`is_lloyd`,
        self$`is_systinfr`,
        self$`is_default`,
        self$`capital`,
        self$`capital_unit`,
        self$`post_address`,
        self$`e_mail`,
        self$`is_gov_or_cb`,
        self$`on_behalf_of_state`,
        self$`is_subject_rf`,
        self$`is_branch`,
        self$`is_liquidated`,
        self$`is_govorg_ext`,
        self$`counter`,
        self$`rn`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsSolvencyCounterpartyFieldsJson) {
      EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsSolvencyCounterpartyFieldsJson)
      self$`source_id` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`source_id`
      self$`source_type` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`source_type`
      self$`counterpartyid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`counterpartyid`
      self$`inn` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`inn`
      self$`ogrn` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`ogrn`
      self$`tin` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`tin`
      self$`lei_code` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`lei_code`
      self$`fininstid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`fininstid`
      self$`okpo` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`okpo`
      self$`sparkid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`sparkid`
      self$`br_txnmid` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`br_txnmid`
      self$`br_regno` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`br_regno`
      self$`reg_code` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`reg_code`
      self$`shortname_rus` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`shortname_rus`
      self$`fullname_rus` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`fullname_rus`
      self$`shortname_eng` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`shortname_eng`
      self$`legal_address` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`legal_address`
      self$`country` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`country`
      self$`country_reg` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`country_reg`
      self$`oecd_lvl` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`oecd_lvl`
      self$`is_riskfree` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_riskfree`
      self$`okved` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`okved`
      self$`kpp` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`kpp`
      self$`is_finorg` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_finorg`
      self$`is_govorg` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_govorg`
      self$`licinfo_type` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`licinfo_type`
      self$`licinfo_no` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`licinfo_no`
      self$`activ_id` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`activ_id`
      self$`is_lloyd` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_lloyd`
      self$`is_systinfr` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_systinfr`
      self$`is_default` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_default`
      self$`capital` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`capital`
      self$`capital_unit` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`capital_unit`
      self$`post_address` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`post_address`
      self$`e_mail` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`e_mail`
      self$`is_gov_or_cb` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_gov_or_cb`
      self$`on_behalf_of_state` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`on_behalf_of_state`
      self$`is_subject_rf` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_subject_rf`
      self$`is_branch` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_branch`
      self$`is_liquidated` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_liquidated`
      self$`is_govorg_ext` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`is_govorg_ext`
      self$`counter` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`counter`
      self$`rn` <- EfirDataHubModelsModelsSolvencyCounterpartyFieldsObject$`rn`
    }
  )
)
