# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRiskRule139Response Class
#'
#' @field rule 
#' @field nonGarantRule 
#' @field error 
#' @field ruleCoef 
#' @field nonGarantRuleCoef 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRiskRule139Response <- R6::R6Class(
  'EfirDataHubModelsModelsRiskRule139Response',
  public = list(
    `rule` = NULL,
    `nonGarantRule` = NULL,
    `error` = NULL,
    `ruleCoef` = NULL,
    `nonGarantRuleCoef` = NULL,
    initialize = function(`rule`, `nonGarantRule`, `error`, `ruleCoef`, `nonGarantRuleCoef`){
      if (!missing(`rule`)) {
        stopifnot(is.character(`rule`), length(`rule`) == 1)
        self$`rule` <- `rule`
      }
      if (!missing(`nonGarantRule`)) {
        stopifnot(is.character(`nonGarantRule`), length(`nonGarantRule`) == 1)
        self$`nonGarantRule` <- `nonGarantRule`
      }
      if (!missing(`error`)) {
        stopifnot(is.character(`error`), length(`error`) == 1)
        self$`error` <- `error`
      }
      if (!missing(`ruleCoef`)) {
        stopifnot(is.numeric(`ruleCoef`), length(`ruleCoef`) == 1)
        stopifnot(R6::is.R6(`ruleCoef`))
        self$`ruleCoef` <- `ruleCoef`
      }
      if (!missing(`nonGarantRuleCoef`)) {
        stopifnot(is.numeric(`nonGarantRuleCoef`), length(`nonGarantRuleCoef`) == 1)
        stopifnot(R6::is.R6(`nonGarantRuleCoef`))
        self$`nonGarantRuleCoef` <- `nonGarantRuleCoef`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRiskRule139ResponseObject <- list()
      if (!is.null(self$`rule`)) {
        EfirDataHubModelsModelsRiskRule139ResponseObject[['rule']] <- self$`rule`
      }
      if (!is.null(self$`nonGarantRule`)) {
        EfirDataHubModelsModelsRiskRule139ResponseObject[['nonGarantRule']] <- self$`nonGarantRule`
      }
      if (!is.null(self$`error`)) {
        EfirDataHubModelsModelsRiskRule139ResponseObject[['error']] <- self$`error`
      }
      if (!is.null(self$`ruleCoef`)) {
        EfirDataHubModelsModelsRiskRule139ResponseObject[['ruleCoef']] <- self$`ruleCoef`$toJSON()
      }
      if (!is.null(self$`nonGarantRuleCoef`)) {
        EfirDataHubModelsModelsRiskRule139ResponseObject[['nonGarantRuleCoef']] <- self$`nonGarantRuleCoef`$toJSON()
      }

      EfirDataHubModelsModelsRiskRule139ResponseObject
    },
    fromJSON = function(EfirDataHubModelsModelsRiskRule139ResponseJson) {
      EfirDataHubModelsModelsRiskRule139ResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskRule139ResponseJson)
      if (!is.null(EfirDataHubModelsModelsRiskRule139ResponseObject$`rule`)) {
        self$`rule` <- EfirDataHubModelsModelsRiskRule139ResponseObject$`rule`
      }
      if (!is.null(EfirDataHubModelsModelsRiskRule139ResponseObject$`nonGarantRule`)) {
        self$`nonGarantRule` <- EfirDataHubModelsModelsRiskRule139ResponseObject$`nonGarantRule`
      }
      if (!is.null(EfirDataHubModelsModelsRiskRule139ResponseObject$`error`)) {
        self$`error` <- EfirDataHubModelsModelsRiskRule139ResponseObject$`error`
      }
      if (!is.null(EfirDataHubModelsModelsRiskRule139ResponseObject$`ruleCoef`)) {
        ruleCoefObject <- BigDecimal$new()
        ruleCoefObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskRule139ResponseObject$ruleCoef, auto_unbox = TRUE))
        self$`ruleCoef` <- ruleCoefObject
      }
      if (!is.null(EfirDataHubModelsModelsRiskRule139ResponseObject$`nonGarantRuleCoef`)) {
        nonGarantRuleCoefObject <- BigDecimal$new()
        nonGarantRuleCoefObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskRule139ResponseObject$nonGarantRuleCoef, auto_unbox = TRUE))
        self$`nonGarantRuleCoef` <- nonGarantRuleCoefObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rule": %s,
           "nonGarantRule": %s,
           "error": %s,
           "ruleCoef": %s,
           "nonGarantRuleCoef": %s
        }',
        self$`rule`,
        self$`nonGarantRule`,
        self$`error`,
        self$`ruleCoef`$toJSON(),
        self$`nonGarantRuleCoef`$toJSON()
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRiskRule139ResponseJson) {
      EfirDataHubModelsModelsRiskRule139ResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskRule139ResponseJson)
      self$`rule` <- EfirDataHubModelsModelsRiskRule139ResponseObject$`rule`
      self$`nonGarantRule` <- EfirDataHubModelsModelsRiskRule139ResponseObject$`nonGarantRule`
      self$`error` <- EfirDataHubModelsModelsRiskRule139ResponseObject$`error`
      BigDecimalObject <- BigDecimal$new()
      self$`ruleCoef` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskRule139ResponseObject$ruleCoef, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`nonGarantRuleCoef` <- BigDecimalObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskRule139ResponseObject$nonGarantRuleCoef, auto_unbox = TRUE))
    }
  )
)
