# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsDictionaryFintoolCategoryValueFields Class
#'
#' @field fintoolid 
#' @field isincode 
#' @field regcode 
#' @field nrdcode 
#' @field categories 
#' @field counter 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsDictionaryFintoolCategoryValueFields <- R6::R6Class(
  'EfirDataHubModelsModelsDictionaryFintoolCategoryValueFields',
  public = list(
    `fintoolid` = NULL,
    `isincode` = NULL,
    `regcode` = NULL,
    `nrdcode` = NULL,
    `categories` = NULL,
    `counter` = NULL,
    initialize = function(`fintoolid`, `isincode`, `regcode`, `nrdcode`, `categories`, `counter`){
      if (!missing(`fintoolid`)) {
        stopifnot(is.numeric(`fintoolid`), length(`fintoolid`) == 1)
        self$`fintoolid` <- `fintoolid`
      }
      if (!missing(`isincode`)) {
        stopifnot(is.character(`isincode`), length(`isincode`) == 1)
        self$`isincode` <- `isincode`
      }
      if (!missing(`regcode`)) {
        stopifnot(is.character(`regcode`), length(`regcode`) == 1)
        self$`regcode` <- `regcode`
      }
      if (!missing(`nrdcode`)) {
        stopifnot(is.character(`nrdcode`), length(`nrdcode`) == 1)
        self$`nrdcode` <- `nrdcode`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(R6::is.R6(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`counter`)) {
        stopifnot(is.numeric(`counter`), length(`counter`) == 1)
        self$`counter` <- `counter`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject <- list()
      if (!is.null(self$`fintoolid`)) {
        EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject[['fintoolid']] <- self$`fintoolid`
      }
      if (!is.null(self$`isincode`)) {
        EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject[['isincode']] <- self$`isincode`
      }
      if (!is.null(self$`regcode`)) {
        EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject[['regcode']] <- self$`regcode`
      }
      if (!is.null(self$`nrdcode`)) {
        EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject[['nrdcode']] <- self$`nrdcode`
      }
      if (!is.null(self$`categories`)) {
        EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject[['categories']] <- lapply(self$`categories`, function(x) x$toJSON())
      }
      if (!is.null(self$`counter`)) {
        EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject[['counter']] <- self$`counter`
      }

      EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsJson) {
      EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsJson)
      if (!is.null(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`fintoolid`)) {
        self$`fintoolid` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`fintoolid`
      }
      if (!is.null(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`isincode`)) {
        self$`isincode` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`isincode`
      }
      if (!is.null(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`regcode`)) {
        self$`regcode` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`regcode`
      }
      if (!is.null(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`nrdcode`)) {
        self$`nrdcode` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`nrdcode`
      }
      if (!is.null(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`categories`)) {
        self$`categories` <- lapply(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`categories`, function(x) {
          categoriesObject <- EfirDataHubModelsModelsDictionaryCategoryToolFields$new()
          categoriesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          categoriesObject
        })
      }
      if (!is.null(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`counter`)) {
        self$`counter` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`counter`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fintoolid": %d,
           "isincode": %s,
           "regcode": %s,
           "nrdcode": %s,
           "categories": [%s],
           "counter": %d
        }',
        self$`fintoolid`,
        self$`isincode`,
        self$`regcode`,
        self$`nrdcode`,
        lapply(self$`categories`, function(x) paste(x$toJSON(), sep=",")),
        self$`counter`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsJson) {
      EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsJson)
      self$`fintoolid` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`fintoolid`
      self$`isincode` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`isincode`
      self$`regcode` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`regcode`
      self$`nrdcode` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`nrdcode`
      self$`categories` <- lapply(EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`categories`, function(x) EfirDataHubModelsModelsDictionaryCategoryToolFields$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`counter` <- EfirDataHubModelsModelsDictionaryFintoolCategoryValueFieldsObject$`counter`
    }
  )
)
