# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2BondDateOptionsRequest Class
#'
#' @field symbol 
#' @field date 
#' @field isCloseRegister 
#' @field couponForecast 
#' @field couponBinding 
#' @field useFixDate 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2BondDateOptionsRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2BondDateOptionsRequest',
  public = list(
    `symbol` = NULL,
    `date` = NULL,
    `isCloseRegister` = NULL,
    `couponForecast` = NULL,
    `couponBinding` = NULL,
    `useFixDate` = NULL,
    initialize = function(`symbol`, `date`, `isCloseRegister`, `couponForecast`, `couponBinding`, `useFixDate`){
      if (!missing(`symbol`)) {
        stopifnot(is.character(`symbol`), length(`symbol`) == 1)
        self$`symbol` <- `symbol`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`isCloseRegister`)) {
        self$`isCloseRegister` <- `isCloseRegister`
      }
      if (!missing(`couponForecast`)) {
        stopifnot(is.character(`couponForecast`), length(`couponForecast`) == 1)
        self$`couponForecast` <- `couponForecast`
      }
      if (!missing(`couponBinding`)) {
        stopifnot(is.character(`couponBinding`), length(`couponBinding`) == 1)
        self$`couponBinding` <- `couponBinding`
      }
      if (!missing(`useFixDate`)) {
        self$`useFixDate` <- `useFixDate`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2BondDateOptionsRequestObject <- list()
      if (!is.null(self$`symbol`)) {
        EfirDataHubModelsRequestsV2BondDateOptionsRequestObject[['symbol']] <- self$`symbol`
      }
      if (!is.null(self$`date`)) {
        EfirDataHubModelsRequestsV2BondDateOptionsRequestObject[['date']] <- self$`date`
      }
      if (!is.null(self$`isCloseRegister`)) {
        EfirDataHubModelsRequestsV2BondDateOptionsRequestObject[['isCloseRegister']] <- self$`isCloseRegister`
      }
      if (!is.null(self$`couponForecast`)) {
        EfirDataHubModelsRequestsV2BondDateOptionsRequestObject[['couponForecast']] <- self$`couponForecast`
      }
      if (!is.null(self$`couponBinding`)) {
        EfirDataHubModelsRequestsV2BondDateOptionsRequestObject[['couponBinding']] <- self$`couponBinding`
      }
      if (!is.null(self$`useFixDate`)) {
        EfirDataHubModelsRequestsV2BondDateOptionsRequestObject[['useFixDate']] <- self$`useFixDate`
      }

      EfirDataHubModelsRequestsV2BondDateOptionsRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2BondDateOptionsRequestJson) {
      EfirDataHubModelsRequestsV2BondDateOptionsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondDateOptionsRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`symbol`)) {
        self$`symbol` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`symbol`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`date`)) {
        self$`date` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`date`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`isCloseRegister`)) {
        self$`isCloseRegister` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`isCloseRegister`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`couponForecast`)) {
        self$`couponForecast` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`couponForecast`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`couponBinding`)) {
        self$`couponBinding` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`couponBinding`
      }
      if (!is.null(EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`useFixDate`)) {
        self$`useFixDate` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`useFixDate`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "symbol": %s,
           "date": %s,
           "isCloseRegister": %s,
           "couponForecast": %s,
           "couponBinding": %s,
           "useFixDate": %s
        }',
        self$`symbol`,
        self$`date`,
        self$`isCloseRegister`,
        self$`couponForecast`,
        self$`couponBinding`,
        self$`useFixDate`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2BondDateOptionsRequestJson) {
      EfirDataHubModelsRequestsV2BondDateOptionsRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2BondDateOptionsRequestJson)
      self$`symbol` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`symbol`
      self$`date` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`date`
      self$`isCloseRegister` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`isCloseRegister`
      self$`couponForecast` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`couponForecast`
      self$`couponBinding` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`couponBinding`
      self$`useFixDate` <- EfirDataHubModelsRequestsV2BondDateOptionsRequestObject$`useFixDate`
    }
  )
)
