# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRUPriceHistoryColumnsFields Class
#'
#' @field id 
#' @field id_group 
#' @field codename 
#' @field shortname_rus 
#' @field fullname_rus 
#' @field shortname_nrd 
#' @field field_remark 
#' @field sort_order 
#' @field shortname_eng 
#' @field fullname_eng 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRUPriceHistoryColumnsFields <- R6::R6Class(
  'EfirDataHubModelsModelsRUPriceHistoryColumnsFields',
  public = list(
    `id` = NULL,
    `id_group` = NULL,
    `codename` = NULL,
    `shortname_rus` = NULL,
    `fullname_rus` = NULL,
    `shortname_nrd` = NULL,
    `field_remark` = NULL,
    `sort_order` = NULL,
    `shortname_eng` = NULL,
    `fullname_eng` = NULL,
    initialize = function(`id`, `id_group`, `codename`, `shortname_rus`, `fullname_rus`, `shortname_nrd`, `field_remark`, `sort_order`, `shortname_eng`, `fullname_eng`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`id_group`)) {
        stopifnot(is.numeric(`id_group`), length(`id_group`) == 1)
        self$`id_group` <- `id_group`
      }
      if (!missing(`codename`)) {
        stopifnot(is.character(`codename`), length(`codename`) == 1)
        self$`codename` <- `codename`
      }
      if (!missing(`shortname_rus`)) {
        stopifnot(is.character(`shortname_rus`), length(`shortname_rus`) == 1)
        self$`shortname_rus` <- `shortname_rus`
      }
      if (!missing(`fullname_rus`)) {
        stopifnot(is.character(`fullname_rus`), length(`fullname_rus`) == 1)
        self$`fullname_rus` <- `fullname_rus`
      }
      if (!missing(`shortname_nrd`)) {
        stopifnot(is.character(`shortname_nrd`), length(`shortname_nrd`) == 1)
        self$`shortname_nrd` <- `shortname_nrd`
      }
      if (!missing(`field_remark`)) {
        stopifnot(is.character(`field_remark`), length(`field_remark`) == 1)
        self$`field_remark` <- `field_remark`
      }
      if (!missing(`sort_order`)) {
        stopifnot(is.numeric(`sort_order`), length(`sort_order`) == 1)
        self$`sort_order` <- `sort_order`
      }
      if (!missing(`shortname_eng`)) {
        stopifnot(is.character(`shortname_eng`), length(`shortname_eng`) == 1)
        self$`shortname_eng` <- `shortname_eng`
      }
      if (!missing(`fullname_eng`)) {
        stopifnot(is.character(`fullname_eng`), length(`fullname_eng`) == 1)
        self$`fullname_eng` <- `fullname_eng`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject <- list()
      if (!is.null(self$`id`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['id']] <- self$`id`
      }
      if (!is.null(self$`id_group`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['id_group']] <- self$`id_group`
      }
      if (!is.null(self$`codename`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['codename']] <- self$`codename`
      }
      if (!is.null(self$`shortname_rus`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['shortname_rus']] <- self$`shortname_rus`
      }
      if (!is.null(self$`fullname_rus`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['fullname_rus']] <- self$`fullname_rus`
      }
      if (!is.null(self$`shortname_nrd`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['shortname_nrd']] <- self$`shortname_nrd`
      }
      if (!is.null(self$`field_remark`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['field_remark']] <- self$`field_remark`
      }
      if (!is.null(self$`sort_order`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['sort_order']] <- self$`sort_order`
      }
      if (!is.null(self$`shortname_eng`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['shortname_eng']] <- self$`shortname_eng`
      }
      if (!is.null(self$`fullname_eng`)) {
        EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject[['fullname_eng']] <- self$`fullname_eng`
      }

      EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsJson) {
      EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsJson)
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`id`)) {
        self$`id` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`id`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`id_group`)) {
        self$`id_group` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`id_group`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`codename`)) {
        self$`codename` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`codename`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_rus`)) {
        self$`shortname_rus` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_rus`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`fullname_rus`)) {
        self$`fullname_rus` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`fullname_rus`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_nrd`)) {
        self$`shortname_nrd` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_nrd`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`field_remark`)) {
        self$`field_remark` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`field_remark`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`sort_order`)) {
        self$`sort_order` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`sort_order`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_eng`)) {
        self$`shortname_eng` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_eng`
      }
      if (!is.null(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`fullname_eng`)) {
        self$`fullname_eng` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`fullname_eng`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "id_group": %d,
           "codename": %s,
           "shortname_rus": %s,
           "fullname_rus": %s,
           "shortname_nrd": %s,
           "field_remark": %s,
           "sort_order": %d,
           "shortname_eng": %s,
           "fullname_eng": %s
        }',
        self$`id`,
        self$`id_group`,
        self$`codename`,
        self$`shortname_rus`,
        self$`fullname_rus`,
        self$`shortname_nrd`,
        self$`field_remark`,
        self$`sort_order`,
        self$`shortname_eng`,
        self$`fullname_eng`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsJson) {
      EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsJson)
      self$`id` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`id`
      self$`id_group` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`id_group`
      self$`codename` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`codename`
      self$`shortname_rus` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_rus`
      self$`fullname_rus` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`fullname_rus`
      self$`shortname_nrd` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_nrd`
      self$`field_remark` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`field_remark`
      self$`sort_order` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`sort_order`
      self$`shortname_eng` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`shortname_eng`
      self$`fullname_eng` <- EfirDataHubModelsModelsRUPriceHistoryColumnsFieldsObject$`fullname_eng`
    }
  )
)
