# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2InfoCalendarTypes Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2InfoCalendarTypes <- R6::R6Class(
  'EfirDataHubModelsRequestsV2InfoCalendarTypes',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2InfoCalendarTypesObject <- list()

      EfirDataHubModelsRequestsV2InfoCalendarTypesObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2InfoCalendarTypesJson) {
      EfirDataHubModelsRequestsV2InfoCalendarTypesObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2InfoCalendarTypesJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2InfoCalendarTypesJson) {
      EfirDataHubModelsRequestsV2InfoCalendarTypesObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2InfoCalendarTypesJson)
    }
  )
)
