# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsAffiliatesStopWhen Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsAffiliatesStopWhen <- R6::R6Class(
  'EfirDataHubModelsModelsAffiliatesStopWhen',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      EfirDataHubModelsModelsAffiliatesStopWhenObject <- list()

      EfirDataHubModelsModelsAffiliatesStopWhenObject
    },
    fromJSON = function(EfirDataHubModelsModelsAffiliatesStopWhenJson) {
      EfirDataHubModelsModelsAffiliatesStopWhenObject <- jsonlite::fromJSON(EfirDataHubModelsModelsAffiliatesStopWhenJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsAffiliatesStopWhenJson) {
      EfirDataHubModelsModelsAffiliatesStopWhenObject <- jsonlite::fromJSON(EfirDataHubModelsModelsAffiliatesStopWhenJson)
    }
  )
)
