# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFields Class
#'
#' @field param_name 
#' @field param 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFields <- R6::R6Class(
  'EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFields',
  public = list(
    `param_name` = NULL,
    `param` = NULL,
    initialize = function(`param_name`, `param`){
      if (!missing(`param_name`)) {
        stopifnot(is.character(`param_name`), length(`param_name`) == 1)
        self$`param_name` <- `param_name`
      }
      if (!missing(`param`)) {
        stopifnot(R6::is.R6(`param`))
        self$`param` <- `param`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject <- list()
      if (!is.null(self$`param_name`)) {
        EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject[['param_name']] <- self$`param_name`
      }
      if (!is.null(self$`param`)) {
        EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject[['param']] <- self$`param`$toJSON()
      }

      EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsJson) {
      EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsJson)
      if (!is.null(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject$`param_name`)) {
        self$`param_name` <- EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject$`param_name`
      }
      if (!is.null(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject$`param`)) {
        paramObject <- Object$new()
        paramObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject$param, auto_unbox = TRUE))
        self$`param` <- paramObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "param_name": %s,
           "param": %s
        }',
        self$`param_name`,
        self$`param`$toJSON()
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsJson) {
      EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsJson)
      self$`param_name` <- EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject$`param_name`
      ObjectObject <- Object$new()
      self$`param` <- ObjectObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsRiskFintoolsRiskGroupParamsFieldsObject$param, auto_unbox = TRUE))
    }
  )
)
