# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFields Class
#'
#' @field fintoolId 
#' @field ratingDate 
#' @field ratingLevel 
#' @field ratingId 
#' @field ratingAgencyId 
#' @field ratingValue 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFields <- R6::R6Class(
  'EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFields',
  public = list(
    `fintoolId` = NULL,
    `ratingDate` = NULL,
    `ratingLevel` = NULL,
    `ratingId` = NULL,
    `ratingAgencyId` = NULL,
    `ratingValue` = NULL,
    initialize = function(`fintoolId`, `ratingDate`, `ratingLevel`, `ratingId`, `ratingAgencyId`, `ratingValue`){
      if (!missing(`fintoolId`)) {
        stopifnot(is.numeric(`fintoolId`), length(`fintoolId`) == 1)
        self$`fintoolId` <- `fintoolId`
      }
      if (!missing(`ratingDate`)) {
        stopifnot(is.character(`ratingDate`), length(`ratingDate`) == 1)
        self$`ratingDate` <- `ratingDate`
      }
      if (!missing(`ratingLevel`)) {
        stopifnot(is.numeric(`ratingLevel`), length(`ratingLevel`) == 1)
        self$`ratingLevel` <- `ratingLevel`
      }
      if (!missing(`ratingId`)) {
        stopifnot(is.numeric(`ratingId`), length(`ratingId`) == 1)
        self$`ratingId` <- `ratingId`
      }
      if (!missing(`ratingAgencyId`)) {
        stopifnot(is.numeric(`ratingAgencyId`), length(`ratingAgencyId`) == 1)
        self$`ratingAgencyId` <- `ratingAgencyId`
      }
      if (!missing(`ratingValue`)) {
        stopifnot(is.character(`ratingValue`), length(`ratingValue`) == 1)
        self$`ratingValue` <- `ratingValue`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject <- list()
      if (!is.null(self$`fintoolId`)) {
        EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject[['fintoolId']] <- self$`fintoolId`
      }
      if (!is.null(self$`ratingDate`)) {
        EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject[['ratingDate']] <- self$`ratingDate`
      }
      if (!is.null(self$`ratingLevel`)) {
        EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject[['ratingLevel']] <- self$`ratingLevel`
      }
      if (!is.null(self$`ratingId`)) {
        EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject[['ratingId']] <- self$`ratingId`
      }
      if (!is.null(self$`ratingAgencyId`)) {
        EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject[['ratingAgencyId']] <- self$`ratingAgencyId`
      }
      if (!is.null(self$`ratingValue`)) {
        EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject[['ratingValue']] <- self$`ratingValue`
      }

      EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsJson) {
      EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsJson)
      if (!is.null(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`fintoolId`)) {
        self$`fintoolId` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`fintoolId`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingDate`)) {
        self$`ratingDate` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingDate`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingLevel`)) {
        self$`ratingLevel` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingLevel`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingId`)) {
        self$`ratingId` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingId`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingAgencyId`)) {
        self$`ratingAgencyId` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingAgencyId`
      }
      if (!is.null(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingValue`)) {
        self$`ratingValue` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingValue`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fintoolId": %d,
           "ratingDate": %s,
           "ratingLevel": %d,
           "ratingId": %d,
           "ratingAgencyId": %d,
           "ratingValue": %s
        }',
        self$`fintoolId`,
        self$`ratingDate`,
        self$`ratingLevel`,
        self$`ratingId`,
        self$`ratingAgencyId`,
        self$`ratingValue`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsJson) {
      EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsJson)
      self$`fintoolId` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`fintoolId`
      self$`ratingDate` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingDate`
      self$`ratingLevel` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingLevel`
      self$`ratingId` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingId`
      self$`ratingAgencyId` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingAgencyId`
      self$`ratingValue` <- EfirDataHubModelsModelsRatingRatingSecurityByAgenciesFieldsObject$`ratingValue`
    }
  )
)
