# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsEmitentReportRow Class
#'
#' @field code 
#' @field value 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsEmitentReportRow <- R6::R6Class(
  'EfirDataHubModelsModelsEmitentReportRow',
  public = list(
    `code` = NULL,
    `value` = NULL,
    initialize = function(`code`, `value`){
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`value`)) {
        stopifnot(is.numeric(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsEmitentReportRowObject <- list()
      if (!is.null(self$`code`)) {
        EfirDataHubModelsModelsEmitentReportRowObject[['code']] <- self$`code`
      }
      if (!is.null(self$`value`)) {
        EfirDataHubModelsModelsEmitentReportRowObject[['value']] <- self$`value`
      }

      EfirDataHubModelsModelsEmitentReportRowObject
    },
    fromJSON = function(EfirDataHubModelsModelsEmitentReportRowJson) {
      EfirDataHubModelsModelsEmitentReportRowObject <- jsonlite::fromJSON(EfirDataHubModelsModelsEmitentReportRowJson)
      if (!is.null(EfirDataHubModelsModelsEmitentReportRowObject$`code`)) {
        self$`code` <- EfirDataHubModelsModelsEmitentReportRowObject$`code`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentReportRowObject$`value`)) {
        self$`value` <- EfirDataHubModelsModelsEmitentReportRowObject$`value`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "code": %s,
           "value": %d
        }',
        self$`code`,
        self$`value`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsEmitentReportRowJson) {
      EfirDataHubModelsModelsEmitentReportRowObject <- jsonlite::fromJSON(EfirDataHubModelsModelsEmitentReportRowJson)
      self$`code` <- EfirDataHubModelsModelsEmitentReportRowObject$`code`
      self$`value` <- EfirDataHubModelsModelsEmitentReportRowObject$`value`
    }
  )
)
