# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsEmitentScoringStatsFields Class
#'
#' @field sector 
#' @field source 
#' @field actualondate 
#' @field key_name 
#' @field mean 
#' @field median 
#' @field q1 
#' @field q3 
#' @field top10 
#' @field top90 
#' @field max 
#' @field min 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsEmitentScoringStatsFields <- R6::R6Class(
  'EfirDataHubModelsModelsEmitentScoringStatsFields',
  public = list(
    `sector` = NULL,
    `source` = NULL,
    `actualondate` = NULL,
    `key_name` = NULL,
    `mean` = NULL,
    `median` = NULL,
    `q1` = NULL,
    `q3` = NULL,
    `top10` = NULL,
    `top90` = NULL,
    `max` = NULL,
    `min` = NULL,
    initialize = function(`sector`, `source`, `actualondate`, `key_name`, `mean`, `median`, `q1`, `q3`, `top10`, `top90`, `max`, `min`){
      if (!missing(`sector`)) {
        stopifnot(is.character(`sector`), length(`sector`) == 1)
        self$`sector` <- `sector`
      }
      if (!missing(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!missing(`actualondate`)) {
        stopifnot(is.character(`actualondate`), length(`actualondate`) == 1)
        self$`actualondate` <- `actualondate`
      }
      if (!missing(`key_name`)) {
        stopifnot(is.character(`key_name`), length(`key_name`) == 1)
        self$`key_name` <- `key_name`
      }
      if (!missing(`mean`)) {
        stopifnot(is.numeric(`mean`), length(`mean`) == 1)
        self$`mean` <- `mean`
      }
      if (!missing(`median`)) {
        stopifnot(is.numeric(`median`), length(`median`) == 1)
        self$`median` <- `median`
      }
      if (!missing(`q1`)) {
        stopifnot(is.numeric(`q1`), length(`q1`) == 1)
        self$`q1` <- `q1`
      }
      if (!missing(`q3`)) {
        stopifnot(is.numeric(`q3`), length(`q3`) == 1)
        self$`q3` <- `q3`
      }
      if (!missing(`top10`)) {
        stopifnot(is.numeric(`top10`), length(`top10`) == 1)
        self$`top10` <- `top10`
      }
      if (!missing(`top90`)) {
        stopifnot(is.numeric(`top90`), length(`top90`) == 1)
        self$`top90` <- `top90`
      }
      if (!missing(`max`)) {
        stopifnot(is.numeric(`max`), length(`max`) == 1)
        self$`max` <- `max`
      }
      if (!missing(`min`)) {
        stopifnot(is.numeric(`min`), length(`min`) == 1)
        self$`min` <- `min`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsEmitentScoringStatsFieldsObject <- list()
      if (!is.null(self$`sector`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['sector']] <- self$`sector`
      }
      if (!is.null(self$`source`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['source']] <- self$`source`
      }
      if (!is.null(self$`actualondate`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['actualondate']] <- self$`actualondate`
      }
      if (!is.null(self$`key_name`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['key_name']] <- self$`key_name`
      }
      if (!is.null(self$`mean`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['mean']] <- self$`mean`
      }
      if (!is.null(self$`median`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['median']] <- self$`median`
      }
      if (!is.null(self$`q1`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['q1']] <- self$`q1`
      }
      if (!is.null(self$`q3`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['q3']] <- self$`q3`
      }
      if (!is.null(self$`top10`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['top10']] <- self$`top10`
      }
      if (!is.null(self$`top90`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['top90']] <- self$`top90`
      }
      if (!is.null(self$`max`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['max']] <- self$`max`
      }
      if (!is.null(self$`min`)) {
        EfirDataHubModelsModelsEmitentScoringStatsFieldsObject[['min']] <- self$`min`
      }

      EfirDataHubModelsModelsEmitentScoringStatsFieldsObject
    },
    fromJSON = function(EfirDataHubModelsModelsEmitentScoringStatsFieldsJson) {
      EfirDataHubModelsModelsEmitentScoringStatsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsEmitentScoringStatsFieldsJson)
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`sector`)) {
        self$`sector` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`sector`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`source`)) {
        self$`source` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`source`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`actualondate`)) {
        self$`actualondate` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`actualondate`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`key_name`)) {
        self$`key_name` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`key_name`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`mean`)) {
        self$`mean` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`mean`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`median`)) {
        self$`median` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`median`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`q1`)) {
        self$`q1` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`q1`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`q3`)) {
        self$`q3` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`q3`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`top10`)) {
        self$`top10` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`top10`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`top90`)) {
        self$`top90` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`top90`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`max`)) {
        self$`max` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`max`
      }
      if (!is.null(EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`min`)) {
        self$`min` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`min`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "sector": %s,
           "source": %s,
           "actualondate": %s,
           "key_name": %s,
           "mean": %d,
           "median": %d,
           "q1": %d,
           "q3": %d,
           "top10": %d,
           "top90": %d,
           "max": %d,
           "min": %d
        }',
        self$`sector`,
        self$`source`,
        self$`actualondate`,
        self$`key_name`,
        self$`mean`,
        self$`median`,
        self$`q1`,
        self$`q3`,
        self$`top10`,
        self$`top90`,
        self$`max`,
        self$`min`
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsEmitentScoringStatsFieldsJson) {
      EfirDataHubModelsModelsEmitentScoringStatsFieldsObject <- jsonlite::fromJSON(EfirDataHubModelsModelsEmitentScoringStatsFieldsJson)
      self$`sector` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`sector`
      self$`source` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`source`
      self$`actualondate` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`actualondate`
      self$`key_name` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`key_name`
      self$`mean` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`mean`
      self$`median` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`median`
      self$`q1` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`q1`
      self$`q3` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`q3`
      self$`top10` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`top10`
      self$`top90` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`top90`
      self$`max` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`max`
      self$`min` <- EfirDataHubModelsModelsEmitentScoringStatsFieldsObject$`min`
    }
  )
)
