# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequest Class
#'
#' @field filterCategory 
#' @field fintoolIds 
#' @field codes 
#' @field onlyFintoolsWithCategory 
#' @field pageNum 
#' @field pageSize 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequest <- R6::R6Class(
  'EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequest',
  public = list(
    `filterCategory` = NULL,
    `fintoolIds` = NULL,
    `codes` = NULL,
    `onlyFintoolsWithCategory` = NULL,
    `pageNum` = NULL,
    `pageSize` = NULL,
    initialize = function(`filterCategory`, `fintoolIds`, `codes`, `onlyFintoolsWithCategory`, `pageNum`, `pageSize`){
      if (!missing(`filterCategory`)) {
        stopifnot(is.character(`filterCategory`), length(`filterCategory`) == 1)
        self$`filterCategory` <- `filterCategory`
      }
      if (!missing(`fintoolIds`)) {
        stopifnot(is.list(`fintoolIds`), length(`fintoolIds`) != 0)
        lapply(`fintoolIds`, function(x) stopifnot(is.character(x)))
        self$`fintoolIds` <- `fintoolIds`
      }
      if (!missing(`codes`)) {
        stopifnot(is.list(`codes`), length(`codes`) != 0)
        lapply(`codes`, function(x) stopifnot(is.character(x)))
        self$`codes` <- `codes`
      }
      if (!missing(`onlyFintoolsWithCategory`)) {
        self$`onlyFintoolsWithCategory` <- `onlyFintoolsWithCategory`
      }
      if (!missing(`pageNum`)) {
        stopifnot(is.numeric(`pageNum`), length(`pageNum`) == 1)
        self$`pageNum` <- `pageNum`
      }
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
    },
    toJSON = function() {
      EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject <- list()
      if (!is.null(self$`filterCategory`)) {
        EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject[['filterCategory']] <- self$`filterCategory`
      }
      if (!is.null(self$`fintoolIds`)) {
        EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject[['fintoolIds']] <- self$`fintoolIds`
      }
      if (!is.null(self$`codes`)) {
        EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject[['codes']] <- self$`codes`
      }
      if (!is.null(self$`onlyFintoolsWithCategory`)) {
        EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject[['onlyFintoolsWithCategory']] <- self$`onlyFintoolsWithCategory`
      }
      if (!is.null(self$`pageNum`)) {
        EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject[['pageNum']] <- self$`pageNum`
      }
      if (!is.null(self$`pageSize`)) {
        EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject[['pageSize']] <- self$`pageSize`
      }

      EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject
    },
    fromJSON = function(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestJson) {
      EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestJson)
      if (!is.null(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`filterCategory`)) {
        self$`filterCategory` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`filterCategory`
      }
      if (!is.null(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`fintoolIds`)) {
        self$`fintoolIds` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`fintoolIds`
      }
      if (!is.null(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`codes`)) {
        self$`codes` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`codes`
      }
      if (!is.null(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`onlyFintoolsWithCategory`)) {
        self$`onlyFintoolsWithCategory` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`onlyFintoolsWithCategory`
      }
      if (!is.null(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`pageNum`)) {
        self$`pageNum` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`pageNum`
      }
      if (!is.null(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`pageSize`)) {
        self$`pageSize` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`pageSize`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "filterCategory": %s,
           "fintoolIds": [%s],
           "codes": [%s],
           "onlyFintoolsWithCategory": %s,
           "pageNum": %d,
           "pageSize": %d
        }',
        self$`filterCategory`,
        lapply(self$`fintoolIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`codes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`onlyFintoolsWithCategory`,
        self$`pageNum`,
        self$`pageSize`
      )
    },
    fromJSONString = function(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestJson) {
      EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject <- jsonlite::fromJSON(EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestJson)
      self$`filterCategory` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`filterCategory`
      self$`fintoolIds` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`fintoolIds`
      self$`codes` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`codes`
      self$`onlyFintoolsWithCategory` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`onlyFintoolsWithCategory`
      self$`pageNum` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`pageNum`
      self$`pageSize` <- EfirDataHubModelsRequestsV2DictionaryFintoolCategoryValueRequestObject$`pageSize`
    }
  )
)
