# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsReportCustomReportStatus Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsReportCustomReportStatus <- R6::R6Class(
  'EfirDataHubModelsModelsReportCustomReportStatus',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      EfirDataHubModelsModelsReportCustomReportStatusObject <- list()

      EfirDataHubModelsModelsReportCustomReportStatusObject
    },
    fromJSON = function(EfirDataHubModelsModelsReportCustomReportStatusJson) {
      EfirDataHubModelsModelsReportCustomReportStatusObject <- jsonlite::fromJSON(EfirDataHubModelsModelsReportCustomReportStatusJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsReportCustomReportStatusJson) {
      EfirDataHubModelsModelsReportCustomReportStatusObject <- jsonlite::fromJSON(EfirDataHubModelsModelsReportCustomReportStatusJson)
    }
  )
)
