# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' EfirDataHubModelsModelsAccountSubscriptionResponse Class
#'
#' @field user 
#' @field roles 
#' @field privilegies 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EfirDataHubModelsModelsAccountSubscriptionResponse <- R6::R6Class(
  'EfirDataHubModelsModelsAccountSubscriptionResponse',
  public = list(
    `user` = NULL,
    `roles` = NULL,
    `privilegies` = NULL,
    initialize = function(`user`, `roles`, `privilegies`){
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!missing(`roles`)) {
        stopifnot(is.list(`roles`), length(`roles`) != 0)
        lapply(`roles`, function(x) stopifnot(R6::is.R6(x)))
        self$`roles` <- `roles`
      }
      if (!missing(`privilegies`)) {
        stopifnot(is.list(`privilegies`), length(`privilegies`) != 0)
        lapply(`privilegies`, function(x) stopifnot(R6::is.R6(x)))
        self$`privilegies` <- `privilegies`
      }
    },
    toJSON = function() {
      EfirDataHubModelsModelsAccountSubscriptionResponseObject <- list()
      if (!is.null(self$`user`)) {
        EfirDataHubModelsModelsAccountSubscriptionResponseObject[['user']] <- self$`user`$toJSON()
      }
      if (!is.null(self$`roles`)) {
        EfirDataHubModelsModelsAccountSubscriptionResponseObject[['roles']] <- lapply(self$`roles`, function(x) x$toJSON())
      }
      if (!is.null(self$`privilegies`)) {
        EfirDataHubModelsModelsAccountSubscriptionResponseObject[['privilegies']] <- lapply(self$`privilegies`, function(x) x$toJSON())
      }

      EfirDataHubModelsModelsAccountSubscriptionResponseObject
    },
    fromJSON = function(EfirDataHubModelsModelsAccountSubscriptionResponseJson) {
      EfirDataHubModelsModelsAccountSubscriptionResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsAccountSubscriptionResponseJson)
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`user`)) {
        userObject <- AllOfEfirDataHubModelsModelsAccountSubscriptionResponseUser$new()
        userObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsAccountSubscriptionResponseObject$user, auto_unbox = TRUE))
        self$`user` <- userObject
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`roles`)) {
        self$`roles` <- lapply(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`roles`, function(x) {
          rolesObject <- EfirDataHubModelsModelsAccountSubscriptionRole$new()
          rolesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          rolesObject
        })
      }
      if (!is.null(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`privilegies`)) {
        self$`privilegies` <- lapply(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`privilegies`, function(x) {
          privilegiesObject <- EfirDataHubModelsModelsAccountSubscriptionPrivilege$new()
          privilegiesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          privilegiesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "user": %s,
           "roles": [%s],
           "privilegies": [%s]
        }',
        self$`user`$toJSON(),
        lapply(self$`roles`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`privilegies`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(EfirDataHubModelsModelsAccountSubscriptionResponseJson) {
      EfirDataHubModelsModelsAccountSubscriptionResponseObject <- jsonlite::fromJSON(EfirDataHubModelsModelsAccountSubscriptionResponseJson)
      AllOfEfirDataHubModelsModelsAccountSubscriptionResponseUserObject <- AllOfEfirDataHubModelsModelsAccountSubscriptionResponseUser$new()
      self$`user` <- AllOfEfirDataHubModelsModelsAccountSubscriptionResponseUserObject$fromJSON(jsonlite::toJSON(EfirDataHubModelsModelsAccountSubscriptionResponseObject$user, auto_unbox = TRUE))
      self$`roles` <- lapply(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`roles`, function(x) EfirDataHubModelsModelsAccountSubscriptionRole$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`privilegies` <- lapply(EfirDataHubModelsModelsAccountSubscriptionResponseObject$`privilegies`, function(x) EfirDataHubModelsModelsAccountSubscriptionPrivilege$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
