# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MoexNccIndicativeRiskCurrencyBody Class
#'
#' @field fintoolId 
#' @field startDate 
#' @field endDate 
#' @field pageNum 
#' @field pageSize 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MoexNccIndicativeRiskCurrencyBody <- R6::R6Class(
  'MoexNccIndicativeRiskCurrencyBody',
  public = list(
    `fintoolId` = NULL,
    `startDate` = NULL,
    `endDate` = NULL,
    `pageNum` = NULL,
    `pageSize` = NULL,
    initialize = function(`fintoolId`, `startDate`, `endDate`, `pageNum`, `pageSize`){
      if (!missing(`fintoolId`)) {
        stopifnot(is.numeric(`fintoolId`), length(`fintoolId`) == 1)
        self$`fintoolId` <- `fintoolId`
      }
      if (!missing(`startDate`)) {
        stopifnot(is.character(`startDate`), length(`startDate`) == 1)
        self$`startDate` <- `startDate`
      }
      if (!missing(`endDate`)) {
        stopifnot(is.character(`endDate`), length(`endDate`) == 1)
        self$`endDate` <- `endDate`
      }
      if (!missing(`pageNum`)) {
        stopifnot(is.numeric(`pageNum`), length(`pageNum`) == 1)
        self$`pageNum` <- `pageNum`
      }
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
    },
    toJSON = function() {
      MoexNccIndicativeRiskCurrencyBodyObject <- list()
      if (!is.null(self$`fintoolId`)) {
        MoexNccIndicativeRiskCurrencyBodyObject[['fintoolId']] <- self$`fintoolId`
      }
      if (!is.null(self$`startDate`)) {
        MoexNccIndicativeRiskCurrencyBodyObject[['startDate']] <- self$`startDate`
      }
      if (!is.null(self$`endDate`)) {
        MoexNccIndicativeRiskCurrencyBodyObject[['endDate']] <- self$`endDate`
      }
      if (!is.null(self$`pageNum`)) {
        MoexNccIndicativeRiskCurrencyBodyObject[['pageNum']] <- self$`pageNum`
      }
      if (!is.null(self$`pageSize`)) {
        MoexNccIndicativeRiskCurrencyBodyObject[['pageSize']] <- self$`pageSize`
      }

      MoexNccIndicativeRiskCurrencyBodyObject
    },
    fromJSON = function(MoexNccIndicativeRiskCurrencyBodyJson) {
      MoexNccIndicativeRiskCurrencyBodyObject <- jsonlite::fromJSON(MoexNccIndicativeRiskCurrencyBodyJson)
      if (!is.null(MoexNccIndicativeRiskCurrencyBodyObject$`fintoolId`)) {
        self$`fintoolId` <- MoexNccIndicativeRiskCurrencyBodyObject$`fintoolId`
      }
      if (!is.null(MoexNccIndicativeRiskCurrencyBodyObject$`startDate`)) {
        self$`startDate` <- MoexNccIndicativeRiskCurrencyBodyObject$`startDate`
      }
      if (!is.null(MoexNccIndicativeRiskCurrencyBodyObject$`endDate`)) {
        self$`endDate` <- MoexNccIndicativeRiskCurrencyBodyObject$`endDate`
      }
      if (!is.null(MoexNccIndicativeRiskCurrencyBodyObject$`pageNum`)) {
        self$`pageNum` <- MoexNccIndicativeRiskCurrencyBodyObject$`pageNum`
      }
      if (!is.null(MoexNccIndicativeRiskCurrencyBodyObject$`pageSize`)) {
        self$`pageSize` <- MoexNccIndicativeRiskCurrencyBodyObject$`pageSize`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fintoolId": %d,
           "startDate": %s,
           "endDate": %s,
           "pageNum": %d,
           "pageSize": %d
        }',
        self$`fintoolId`,
        self$`startDate`,
        self$`endDate`,
        self$`pageNum`,
        self$`pageSize`
      )
    },
    fromJSONString = function(MoexNccIndicativeRiskCurrencyBodyJson) {
      MoexNccIndicativeRiskCurrencyBodyObject <- jsonlite::fromJSON(MoexNccIndicativeRiskCurrencyBodyJson)
      self$`fintoolId` <- MoexNccIndicativeRiskCurrencyBodyObject$`fintoolId`
      self$`startDate` <- MoexNccIndicativeRiskCurrencyBodyObject$`startDate`
      self$`endDate` <- MoexNccIndicativeRiskCurrencyBodyObject$`endDate`
      self$`pageNum` <- MoexNccIndicativeRiskCurrencyBodyObject$`pageNum`
      self$`pageSize` <- MoexNccIndicativeRiskCurrencyBodyObject$`pageSize`
    }
  )
)
