# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' RatingRatingsHistoryBody Class
#'
#' @field dateFrom 
#' @field dateTo 
#' @field sort 
#' @field filter 
#' @field including_gov_org 
#' @field pageNum 
#' @field pageSize 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RatingRatingsHistoryBody <- R6::R6Class(
  'RatingRatingsHistoryBody',
  public = list(
    `dateFrom` = NULL,
    `dateTo` = NULL,
    `sort` = NULL,
    `filter` = NULL,
    `including_gov_org` = NULL,
    `pageNum` = NULL,
    `pageSize` = NULL,
    initialize = function(`dateFrom`, `dateTo`, `sort`, `filter`, `including_gov_org`, `pageNum`, `pageSize`){
      if (!missing(`dateFrom`)) {
        stopifnot(is.character(`dateFrom`), length(`dateFrom`) == 1)
        self$`dateFrom` <- `dateFrom`
      }
      if (!missing(`dateTo`)) {
        stopifnot(is.character(`dateTo`), length(`dateTo`) == 1)
        self$`dateTo` <- `dateTo`
      }
      if (!missing(`sort`)) {
        stopifnot(is.numeric(`sort`), length(`sort`) == 1)
        self$`sort` <- `sort`
      }
      if (!missing(`filter`)) {
        stopifnot(is.character(`filter`), length(`filter`) == 1)
        self$`filter` <- `filter`
      }
      if (!missing(`including_gov_org`)) {
        self$`including_gov_org` <- `including_gov_org`
      }
      if (!missing(`pageNum`)) {
        stopifnot(is.numeric(`pageNum`), length(`pageNum`) == 1)
        self$`pageNum` <- `pageNum`
      }
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
    },
    toJSON = function() {
      RatingRatingsHistoryBodyObject <- list()
      if (!is.null(self$`dateFrom`)) {
        RatingRatingsHistoryBodyObject[['dateFrom']] <- self$`dateFrom`
      }
      if (!is.null(self$`dateTo`)) {
        RatingRatingsHistoryBodyObject[['dateTo']] <- self$`dateTo`
      }
      if (!is.null(self$`sort`)) {
        RatingRatingsHistoryBodyObject[['sort']] <- self$`sort`
      }
      if (!is.null(self$`filter`)) {
        RatingRatingsHistoryBodyObject[['filter']] <- self$`filter`
      }
      if (!is.null(self$`including_gov_org`)) {
        RatingRatingsHistoryBodyObject[['including_gov_org']] <- self$`including_gov_org`
      }
      if (!is.null(self$`pageNum`)) {
        RatingRatingsHistoryBodyObject[['pageNum']] <- self$`pageNum`
      }
      if (!is.null(self$`pageSize`)) {
        RatingRatingsHistoryBodyObject[['pageSize']] <- self$`pageSize`
      }

      RatingRatingsHistoryBodyObject
    },
    fromJSON = function(RatingRatingsHistoryBodyJson) {
      RatingRatingsHistoryBodyObject <- jsonlite::fromJSON(RatingRatingsHistoryBodyJson)
      if (!is.null(RatingRatingsHistoryBodyObject$`dateFrom`)) {
        self$`dateFrom` <- RatingRatingsHistoryBodyObject$`dateFrom`
      }
      if (!is.null(RatingRatingsHistoryBodyObject$`dateTo`)) {
        self$`dateTo` <- RatingRatingsHistoryBodyObject$`dateTo`
      }
      if (!is.null(RatingRatingsHistoryBodyObject$`sort`)) {
        self$`sort` <- RatingRatingsHistoryBodyObject$`sort`
      }
      if (!is.null(RatingRatingsHistoryBodyObject$`filter`)) {
        self$`filter` <- RatingRatingsHistoryBodyObject$`filter`
      }
      if (!is.null(RatingRatingsHistoryBodyObject$`including_gov_org`)) {
        self$`including_gov_org` <- RatingRatingsHistoryBodyObject$`including_gov_org`
      }
      if (!is.null(RatingRatingsHistoryBodyObject$`pageNum`)) {
        self$`pageNum` <- RatingRatingsHistoryBodyObject$`pageNum`
      }
      if (!is.null(RatingRatingsHistoryBodyObject$`pageSize`)) {
        self$`pageSize` <- RatingRatingsHistoryBodyObject$`pageSize`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "dateFrom": %s,
           "dateTo": %s,
           "sort": %d,
           "filter": %s,
           "including_gov_org": %s,
           "pageNum": %d,
           "pageSize": %d
        }',
        self$`dateFrom`,
        self$`dateTo`,
        self$`sort`,
        self$`filter`,
        self$`including_gov_org`,
        self$`pageNum`,
        self$`pageSize`
      )
    },
    fromJSONString = function(RatingRatingsHistoryBodyJson) {
      RatingRatingsHistoryBodyObject <- jsonlite::fromJSON(RatingRatingsHistoryBodyJson)
      self$`dateFrom` <- RatingRatingsHistoryBodyObject$`dateFrom`
      self$`dateTo` <- RatingRatingsHistoryBodyObject$`dateTo`
      self$`sort` <- RatingRatingsHistoryBodyObject$`sort`
      self$`filter` <- RatingRatingsHistoryBodyObject$`filter`
      self$`including_gov_org` <- RatingRatingsHistoryBodyObject$`including_gov_org`
      self$`pageNum` <- RatingRatingsHistoryBodyObject$`pageNum`
      self$`pageSize` <- RatingRatingsHistoryBodyObject$`pageSize`
    }
  )
)
