# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' RiskMarketRiskDataBody Class
#'
#' @field ids 
#' @field calcDate 
#' @field offerEnable 
#' @field useFrozenDates 
#' @field edition 
#' @field bBCountry 
#' @field cbrInstructions 
#' @field positionOpenDate 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RiskMarketRiskDataBody <- R6::R6Class(
  'RiskMarketRiskDataBody',
  public = list(
    `ids` = NULL,
    `calcDate` = NULL,
    `offerEnable` = NULL,
    `useFrozenDates` = NULL,
    `edition` = NULL,
    `bBCountry` = NULL,
    `cbrInstructions` = NULL,
    `positionOpenDate` = NULL,
    initialize = function(`ids`, `calcDate`, `offerEnable`, `useFrozenDates`, `edition`, `bBCountry`, `cbrInstructions`, `positionOpenDate`){
      if (!missing(`ids`)) {
        stopifnot(is.list(`ids`), length(`ids`) != 0)
        lapply(`ids`, function(x) stopifnot(is.character(x)))
        self$`ids` <- `ids`
      }
      if (!missing(`calcDate`)) {
        stopifnot(is.character(`calcDate`), length(`calcDate`) == 1)
        self$`calcDate` <- `calcDate`
      }
      if (!missing(`offerEnable`)) {
        self$`offerEnable` <- `offerEnable`
      }
      if (!missing(`useFrozenDates`)) {
        self$`useFrozenDates` <- `useFrozenDates`
      }
      if (!missing(`edition`)) {
        stopifnot(is.character(`edition`), length(`edition`) == 1)
        self$`edition` <- `edition`
      }
      if (!missing(`bBCountry`)) {
        stopifnot(is.character(`bBCountry`), length(`bBCountry`) == 1)
        self$`bBCountry` <- `bBCountry`
      }
      if (!missing(`cbrInstructions`)) {
        stopifnot(is.list(`cbrInstructions`), length(`cbrInstructions`) != 0)
        lapply(`cbrInstructions`, function(x) stopifnot(R6::is.R6(x)))
        self$`cbrInstructions` <- `cbrInstructions`
      }
      if (!missing(`positionOpenDate`)) {
        stopifnot(is.character(`positionOpenDate`), length(`positionOpenDate`) == 1)
        self$`positionOpenDate` <- `positionOpenDate`
      }
    },
    toJSON = function() {
      RiskMarketRiskDataBodyObject <- list()
      if (!is.null(self$`ids`)) {
        RiskMarketRiskDataBodyObject[['ids']] <- self$`ids`
      }
      if (!is.null(self$`calcDate`)) {
        RiskMarketRiskDataBodyObject[['calcDate']] <- self$`calcDate`
      }
      if (!is.null(self$`offerEnable`)) {
        RiskMarketRiskDataBodyObject[['offerEnable']] <- self$`offerEnable`
      }
      if (!is.null(self$`useFrozenDates`)) {
        RiskMarketRiskDataBodyObject[['useFrozenDates']] <- self$`useFrozenDates`
      }
      if (!is.null(self$`edition`)) {
        RiskMarketRiskDataBodyObject[['edition']] <- self$`edition`
      }
      if (!is.null(self$`bBCountry`)) {
        RiskMarketRiskDataBodyObject[['bBCountry']] <- self$`bBCountry`
      }
      if (!is.null(self$`cbrInstructions`)) {
        RiskMarketRiskDataBodyObject[['cbrInstructions']] <- lapply(self$`cbrInstructions`, function(x) x$toJSON())
      }
      if (!is.null(self$`positionOpenDate`)) {
        RiskMarketRiskDataBodyObject[['positionOpenDate']] <- self$`positionOpenDate`
      }

      RiskMarketRiskDataBodyObject
    },
    fromJSON = function(RiskMarketRiskDataBodyJson) {
      RiskMarketRiskDataBodyObject <- jsonlite::fromJSON(RiskMarketRiskDataBodyJson)
      if (!is.null(RiskMarketRiskDataBodyObject$`ids`)) {
        self$`ids` <- RiskMarketRiskDataBodyObject$`ids`
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`calcDate`)) {
        self$`calcDate` <- RiskMarketRiskDataBodyObject$`calcDate`
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`offerEnable`)) {
        self$`offerEnable` <- RiskMarketRiskDataBodyObject$`offerEnable`
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`useFrozenDates`)) {
        self$`useFrozenDates` <- RiskMarketRiskDataBodyObject$`useFrozenDates`
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`edition`)) {
        self$`edition` <- RiskMarketRiskDataBodyObject$`edition`
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`bBCountry`)) {
        self$`bBCountry` <- RiskMarketRiskDataBodyObject$`bBCountry`
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`cbrInstructions`)) {
        self$`cbrInstructions` <- lapply(RiskMarketRiskDataBodyObject$`cbrInstructions`, function(x) {
          cbrInstructionsObject <- EfirDataHubModelsRequestsV2NameValuePair$new()
          cbrInstructionsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          cbrInstructionsObject
        })
      }
      if (!is.null(RiskMarketRiskDataBodyObject$`positionOpenDate`)) {
        self$`positionOpenDate` <- RiskMarketRiskDataBodyObject$`positionOpenDate`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "ids": [%s],
           "calcDate": %s,
           "offerEnable": %s,
           "useFrozenDates": %s,
           "edition": %s,
           "bBCountry": %s,
           "cbrInstructions": [%s],
           "positionOpenDate": %s
        }',
        lapply(self$`ids`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`calcDate`,
        self$`offerEnable`,
        self$`useFrozenDates`,
        self$`edition`,
        self$`bBCountry`,
        lapply(self$`cbrInstructions`, function(x) paste(x$toJSON(), sep=",")),
        self$`positionOpenDate`
      )
    },
    fromJSONString = function(RiskMarketRiskDataBodyJson) {
      RiskMarketRiskDataBodyObject <- jsonlite::fromJSON(RiskMarketRiskDataBodyJson)
      self$`ids` <- RiskMarketRiskDataBodyObject$`ids`
      self$`calcDate` <- RiskMarketRiskDataBodyObject$`calcDate`
      self$`offerEnable` <- RiskMarketRiskDataBodyObject$`offerEnable`
      self$`useFrozenDates` <- RiskMarketRiskDataBodyObject$`useFrozenDates`
      self$`edition` <- RiskMarketRiskDataBodyObject$`edition`
      self$`bBCountry` <- RiskMarketRiskDataBodyObject$`bBCountry`
      self$`cbrInstructions` <- lapply(RiskMarketRiskDataBodyObject$`cbrInstructions`, function(x) EfirDataHubModelsRequestsV2NameValuePair$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`positionOpenDate` <- RiskMarketRiskDataBodyObject$`positionOpenDate`
    }
  )
)
