# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScoringTransformantsBody Class
#'
#' @field actualDate 
#' @field coefNameEng 
#' @field source 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScoringTransformantsBody <- R6::R6Class(
  'ScoringTransformantsBody',
  public = list(
    `actualDate` = NULL,
    `coefNameEng` = NULL,
    `source` = NULL,
    initialize = function(`actualDate`, `coefNameEng`, `source`){
      if (!missing(`actualDate`)) {
        stopifnot(is.character(`actualDate`), length(`actualDate`) == 1)
        self$`actualDate` <- `actualDate`
      }
      if (!missing(`coefNameEng`)) {
        stopifnot(is.character(`coefNameEng`), length(`coefNameEng`) == 1)
        self$`coefNameEng` <- `coefNameEng`
      }
      if (!missing(`source`)) {
        stopifnot(R6::is.R6(`source`))
        self$`source` <- `source`
      }
    },
    toJSON = function() {
      ScoringTransformantsBodyObject <- list()
      if (!is.null(self$`actualDate`)) {
        ScoringTransformantsBodyObject[['actualDate']] <- self$`actualDate`
      }
      if (!is.null(self$`coefNameEng`)) {
        ScoringTransformantsBodyObject[['coefNameEng']] <- self$`coefNameEng`
      }
      if (!is.null(self$`source`)) {
        ScoringTransformantsBodyObject[['source']] <- self$`source`$toJSON()
      }

      ScoringTransformantsBodyObject
    },
    fromJSON = function(ScoringTransformantsBodyJson) {
      ScoringTransformantsBodyObject <- jsonlite::fromJSON(ScoringTransformantsBodyJson)
      if (!is.null(ScoringTransformantsBodyObject$`actualDate`)) {
        self$`actualDate` <- ScoringTransformantsBodyObject$`actualDate`
      }
      if (!is.null(ScoringTransformantsBodyObject$`coefNameEng`)) {
        self$`coefNameEng` <- ScoringTransformantsBodyObject$`coefNameEng`
      }
      if (!is.null(ScoringTransformantsBodyObject$`source`)) {
        sourceObject <- Object$new()
        sourceObject$fromJSON(jsonlite::toJSON(ScoringTransformantsBodyObject$source, auto_unbox = TRUE))
        self$`source` <- sourceObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "actualDate": %s,
           "coefNameEng": %s,
           "source": %s
        }',
        self$`actualDate`,
        self$`coefNameEng`,
        self$`source`$toJSON()
      )
    },
    fromJSONString = function(ScoringTransformantsBodyJson) {
      ScoringTransformantsBodyObject <- jsonlite::fromJSON(ScoringTransformantsBodyJson)
      self$`actualDate` <- ScoringTransformantsBodyObject$`actualDate`
      self$`coefNameEng` <- ScoringTransformantsBodyObject$`coefNameEng`
      ObjectObject <- Object$new()
      self$`source` <- ObjectObject$fromJSON(jsonlite::toJSON(ScoringTransformantsBodyObject$source, auto_unbox = TRUE))
    }
  )
)
