# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScoringCompanyownersBody Class
#'
#' @field ids 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScoringCompanyownersBody <- R6::R6Class(
  'ScoringCompanyownersBody',
  public = list(
    `ids` = NULL,
    initialize = function(`ids`){
      if (!missing(`ids`)) {
        stopifnot(is.list(`ids`), length(`ids`) != 0)
        lapply(`ids`, function(x) stopifnot(R6::is.R6(x)))
        self$`ids` <- `ids`
      }
    },
    toJSON = function() {
      ScoringCompanyownersBodyObject <- list()
      if (!is.null(self$`ids`)) {
        ScoringCompanyownersBodyObject[['ids']] <- lapply(self$`ids`, function(x) x$toJSON())
      }

      ScoringCompanyownersBodyObject
    },
    fromJSON = function(ScoringCompanyownersBodyJson) {
      ScoringCompanyownersBodyObject <- jsonlite::fromJSON(ScoringCompanyownersBodyJson)
      if (!is.null(ScoringCompanyownersBodyObject$`ids`)) {
        self$`ids` <- lapply(ScoringCompanyownersBodyObject$`ids`, function(x) {
          idsObject <- EfirDataHubModelsRequestsV2ScoringCompanyCode$new()
          idsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          idsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "ids": [%s]
        }',
        lapply(self$`ids`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(ScoringCompanyownersBodyJson) {
      ScoringCompanyownersBodyObject <- jsonlite::fromJSON(ScoringCompanyownersBodyJson)
      self$`ids` <- lapply(ScoringCompanyownersBodyObject$`ids`, function(x) EfirDataHubModelsRequestsV2ScoringCompanyCode$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
