# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' SolvencyRatingAggSecurityBody Class
#'
#' @field useReinsurerRatings 
#' @field scaleCode 
#' @field fintoolIds 
#' @field date 
#' @field useFreezing 
#' @field freezingType 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SolvencyRatingAggSecurityBody <- R6::R6Class(
  'SolvencyRatingAggSecurityBody',
  public = list(
    `useReinsurerRatings` = NULL,
    `scaleCode` = NULL,
    `fintoolIds` = NULL,
    `date` = NULL,
    `useFreezing` = NULL,
    `freezingType` = NULL,
    initialize = function(`useReinsurerRatings`, `scaleCode`, `fintoolIds`, `date`, `useFreezing`, `freezingType`){
      if (!missing(`useReinsurerRatings`)) {
        self$`useReinsurerRatings` <- `useReinsurerRatings`
      }
      if (!missing(`scaleCode`)) {
        stopifnot(is.numeric(`scaleCode`), length(`scaleCode`) == 1)
        self$`scaleCode` <- `scaleCode`
      }
      if (!missing(`fintoolIds`)) {
        stopifnot(is.list(`fintoolIds`), length(`fintoolIds`) != 0)
        lapply(`fintoolIds`, function(x) stopifnot(is.character(x)))
        self$`fintoolIds` <- `fintoolIds`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`useFreezing`)) {
        self$`useFreezing` <- `useFreezing`
      }
      if (!missing(`freezingType`)) {
        stopifnot(R6::is.R6(`freezingType`))
        self$`freezingType` <- `freezingType`
      }
    },
    toJSON = function() {
      SolvencyRatingAggSecurityBodyObject <- list()
      if (!is.null(self$`useReinsurerRatings`)) {
        SolvencyRatingAggSecurityBodyObject[['useReinsurerRatings']] <- self$`useReinsurerRatings`
      }
      if (!is.null(self$`scaleCode`)) {
        SolvencyRatingAggSecurityBodyObject[['scaleCode']] <- self$`scaleCode`
      }
      if (!is.null(self$`fintoolIds`)) {
        SolvencyRatingAggSecurityBodyObject[['fintoolIds']] <- self$`fintoolIds`
      }
      if (!is.null(self$`date`)) {
        SolvencyRatingAggSecurityBodyObject[['date']] <- self$`date`
      }
      if (!is.null(self$`useFreezing`)) {
        SolvencyRatingAggSecurityBodyObject[['useFreezing']] <- self$`useFreezing`
      }
      if (!is.null(self$`freezingType`)) {
        SolvencyRatingAggSecurityBodyObject[['freezingType']] <- self$`freezingType`$toJSON()
      }

      SolvencyRatingAggSecurityBodyObject
    },
    fromJSON = function(SolvencyRatingAggSecurityBodyJson) {
      SolvencyRatingAggSecurityBodyObject <- jsonlite::fromJSON(SolvencyRatingAggSecurityBodyJson)
      if (!is.null(SolvencyRatingAggSecurityBodyObject$`useReinsurerRatings`)) {
        self$`useReinsurerRatings` <- SolvencyRatingAggSecurityBodyObject$`useReinsurerRatings`
      }
      if (!is.null(SolvencyRatingAggSecurityBodyObject$`scaleCode`)) {
        self$`scaleCode` <- SolvencyRatingAggSecurityBodyObject$`scaleCode`
      }
      if (!is.null(SolvencyRatingAggSecurityBodyObject$`fintoolIds`)) {
        self$`fintoolIds` <- SolvencyRatingAggSecurityBodyObject$`fintoolIds`
      }
      if (!is.null(SolvencyRatingAggSecurityBodyObject$`date`)) {
        self$`date` <- SolvencyRatingAggSecurityBodyObject$`date`
      }
      if (!is.null(SolvencyRatingAggSecurityBodyObject$`useFreezing`)) {
        self$`useFreezing` <- SolvencyRatingAggSecurityBodyObject$`useFreezing`
      }
      if (!is.null(SolvencyRatingAggSecurityBodyObject$`freezingType`)) {
        freezingTypeObject <- Object$new()
        freezingTypeObject$fromJSON(jsonlite::toJSON(SolvencyRatingAggSecurityBodyObject$freezingType, auto_unbox = TRUE))
        self$`freezingType` <- freezingTypeObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "useReinsurerRatings": %s,
           "scaleCode": %d,
           "fintoolIds": [%s],
           "date": %s,
           "useFreezing": %s,
           "freezingType": %s
        }',
        self$`useReinsurerRatings`,
        self$`scaleCode`,
        lapply(self$`fintoolIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`date`,
        self$`useFreezing`,
        self$`freezingType`$toJSON()
      )
    },
    fromJSONString = function(SolvencyRatingAggSecurityBodyJson) {
      SolvencyRatingAggSecurityBodyObject <- jsonlite::fromJSON(SolvencyRatingAggSecurityBodyJson)
      self$`useReinsurerRatings` <- SolvencyRatingAggSecurityBodyObject$`useReinsurerRatings`
      self$`scaleCode` <- SolvencyRatingAggSecurityBodyObject$`scaleCode`
      self$`fintoolIds` <- SolvencyRatingAggSecurityBodyObject$`fintoolIds`
      self$`date` <- SolvencyRatingAggSecurityBodyObject$`date`
      self$`useFreezing` <- SolvencyRatingAggSecurityBodyObject$`useFreezing`
      ObjectObject <- Object$new()
      self$`freezingType` <- ObjectObject$fromJSON(jsonlite::toJSON(SolvencyRatingAggSecurityBodyObject$freezingType, auto_unbox = TRUE))
    }
  )
)
