# API Reference United Data (RU DATA) v2.0
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' SolvencyRatingListBody Class
#'
#' @field date 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SolvencyRatingListBody <- R6::R6Class(
  'SolvencyRatingListBody',
  public = list(
    `date` = NULL,
    initialize = function(`date`){
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
    },
    toJSON = function() {
      SolvencyRatingListBodyObject <- list()
      if (!is.null(self$`date`)) {
        SolvencyRatingListBodyObject[['date']] <- self$`date`
      }

      SolvencyRatingListBodyObject
    },
    fromJSON = function(SolvencyRatingListBodyJson) {
      SolvencyRatingListBodyObject <- jsonlite::fromJSON(SolvencyRatingListBodyJson)
      if (!is.null(SolvencyRatingListBodyObject$`date`)) {
        self$`date` <- SolvencyRatingListBodyObject$`date`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "date": %s
        }',
        self$`date`
      )
    },
    fromJSONString = function(SolvencyRatingListBodyJson) {
      SolvencyRatingListBodyObject <- jsonlite::fromJSON(SolvencyRatingListBodyJson)
      self$`date` <- SolvencyRatingListBodyObject$`date`
    }
  )
)
